(setq-default pop-up-frames nil)
(setq-default pop-up-windows nil)

(advice-add 'bury-buffer :override (lambda (&optional buffer-or-name)))
(advice-add 'bury-buffer-internal :override (lambda (&optional buffer-or-name)))
(advice-add 'help-window-display-message :override (lambda (quit-part window &optional scroll)))

(add-to-list 'same-window-buffer-names "*Apropos*")
(add-to-list 'same-window-buffer-names "*Completions*")
(add-to-list 'same-window-buffer-names "*Faces*")
(add-to-list 'same-window-buffer-names "*Help*")
(add-to-list 'same-window-buffer-names "*Output*")
(add-to-list 'same-window-buffer-names "*Keymap*")
(add-to-list 'same-window-regexps ".+c")
(add-to-list 'same-window-regexps ".+cpp")
(add-to-list 'same-window-regexps ".+el")
(add-to-list 'same-window-regexps ".+el.gz")
(add-to-list 'same-window-regexps ".+h")
(add-to-list 'same-window-regexps ".+hpp")
(add-to-list 'same-window-regexps ".+ipp")

(provide 'jd:window-st.el)
