(provide 'jd:global-keys.el)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; remove the union relationship of Meta and ESC
(setq meta-prefix-char nil)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; `key-translation-map' --- `C source code'
(setf (cdr key-translation-map) nil)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; `function-key-map' --- `C source code'
(setf (cdr function-key-map) nil)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; `local-function-key-map' --- `C source code'
(setf (cdr local-function-key-map) nil)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; `global-map' --- `subr.el'
(setq jd:temp-global-map (make-sparse-keymap))
(substitute-key-definition
 'self-insert-command 'self-insert-command jd:temp-global-map global-map)
(setf (cdr global-map) nil)
(substitute-key-definition
 'self-insert-command 'self-insert-command global-map jd:temp-global-map)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; `input-decode-map' --- `C source code'
(define-key input-decode-map (kbd "C-a")  [\C-\a])
(define-key input-decode-map (kbd "C-b")  [\C-\b])
(define-key input-decode-map (kbd "C-c")  [\C-\c])
(define-key input-decode-map (kbd "C-d")  [\C-\d])
(define-key input-decode-map (kbd "C-e")  [\C-\e])
(define-key input-decode-map (kbd "C-f")  [\C-\f])
(define-key input-decode-map (kbd "C-g")  [\C-\g])
(define-key input-decode-map (kbd "C-h")  [\C-\h])
(define-key input-decode-map (kbd "C-i")  [\C-\i])
(define-key input-decode-map (kbd "C-j")  [\C-\j])
(define-key input-decode-map (kbd "C-k")  [\C-\k])
(define-key input-decode-map (kbd "C-l")  [\C-\l])
(define-key input-decode-map (kbd "C-m")  [\C-\m])
(define-key input-decode-map (kbd "C-n")  [\C-\n])
(define-key input-decode-map (kbd "C-o")  [\C-\o])
(define-key input-decode-map (kbd "C-p")  [\C-\p])
(define-key input-decode-map (kbd "C-q")  [\C-\q])
(define-key input-decode-map (kbd "C-r")  [\C-\r])
(define-key input-decode-map (kbd "C-s")  [\C-\s])
(define-key input-decode-map (kbd "C-t")  [\C-\t])
(define-key input-decode-map (kbd "C-u")  [\C-\u])
(define-key input-decode-map (kbd "C-v")  [\C-\v])
(define-key input-decode-map (kbd "C-w")  [\C-\w])
(define-key input-decode-map (kbd "C-x")  [\C-\x])
(define-key input-decode-map (kbd "C-y")  [\C-\y])
(define-key input-decode-map (kbd "C-z")  [\C-\z])
(define-key input-decode-map (kbd "C-[")  [\C-\[])
(define-key input-decode-map (kbd "C-]")  [\C-\]])
(define-key input-decode-map (kbd "C-\\") [\C-\\])
(define-key input-decode-map (kbd "C-;")  [\C-\;])
(define-key input-decode-map (kbd "C-'")  [\C-\'])
(define-key input-decode-map (kbd "C-,")  [\C-\,])
(define-key input-decode-map (kbd "C-.")  [\C-\.])
(define-key input-decode-map (kbd "C-/")  [\C-\/])
(define-key input-decode-map (kbd "C-{")  [\C-\{])
(define-key input-decode-map (kbd "C-}")  [\C-\}])
(define-key input-decode-map (kbd "C-|")  [\C-\|])
(define-key input-decode-map (kbd "C-:")  [\C-\:])
(define-key input-decode-map (kbd "C-\"") [\C-\"])
(define-key input-decode-map (kbd "C-<")  [\C-\<])
(define-key input-decode-map (kbd "C->")  [\C-\>])
(define-key input-decode-map (kbd "C-?")  [\C-\?])
(define-key input-decode-map (kbd "C-`")  [\C-\`])
(define-key input-decode-map (kbd "C-1")  [\C-\1])
(define-key input-decode-map (kbd "C-2")  [\C-\2])
(define-key input-decode-map (kbd "C-3")  [\C-\3])
(define-key input-decode-map (kbd "C-4")  [\C-\4])
(define-key input-decode-map (kbd "C-5")  [\C-\5])
(define-key input-decode-map (kbd "C-6")  [\C-\6])
(define-key input-decode-map (kbd "C-7")  [\C-\7])
(define-key input-decode-map (kbd "C-8")  [\C-\8])
(define-key input-decode-map (kbd "C-9")  [\C-\9])
(define-key input-decode-map (kbd "C-0")  [\C-\0])
(define-key input-decode-map (kbd "C--")  [\C-\-])
(define-key input-decode-map (kbd "C-=")  [\C-\=])
(define-key input-decode-map (kbd "C-~")  [\C-\~])
(define-key input-decode-map (kbd "C-!")  [\C-\!])
(define-key input-decode-map (kbd "C-@")  [\C-\@])
(define-key input-decode-map (kbd "C-#")  [\C-\#])
(define-key input-decode-map (kbd "C-$")  [\C-\$])
(define-key input-decode-map (kbd "C-%")  [\C-\%])
(define-key input-decode-map (kbd "C-^")  [\C-\^])
(define-key input-decode-map (kbd "C-&")  [\C-\&])
(define-key input-decode-map (kbd "C-*")  [\C-\*])
(define-key input-decode-map (kbd "C-(")  [\C-\(])
(define-key input-decode-map (kbd "C-)")  [\C-\)])
(define-key input-decode-map (kbd "C-_")  [\C-\_])
(define-key input-decode-map (kbd "C-+")  [\C-\+])

(define-key input-decode-map (kbd "C-S-a")  [\C-\S-\a])
(define-key input-decode-map (kbd "C-S-b")  [\C-\S-\b])
(define-key input-decode-map (kbd "C-S-c")  [\C-\S-\c])
(define-key input-decode-map (kbd "C-S-d")  [\C-\S-\d])
(define-key input-decode-map (kbd "C-S-e")  [\C-\S-\e])
(define-key input-decode-map (kbd "C-S-f")  [\C-\S-\f])
(define-key input-decode-map (kbd "C-S-g")  [\C-\S-\g])
(define-key input-decode-map (kbd "C-S-h")  [\C-\S-\h])
(define-key input-decode-map (kbd "C-S-i")  [\C-\S-\i])
(define-key input-decode-map (kbd "C-S-j")  [\C-\S-\j])
(define-key input-decode-map (kbd "C-S-k")  [\C-\S-\k])
(define-key input-decode-map (kbd "C-S-l")  [\C-\S-\l])
(define-key input-decode-map (kbd "C-S-m")  [\C-\S-\m])
(define-key input-decode-map (kbd "C-S-n")  [\C-\S-\n])
(define-key input-decode-map (kbd "C-S-o")  [\C-\S-\o])
(define-key input-decode-map (kbd "C-S-p")  [\C-\S-\p])
(define-key input-decode-map (kbd "C-S-q")  [\C-\S-\q])
(define-key input-decode-map (kbd "C-S-r")  [\C-\S-\r])
(define-key input-decode-map (kbd "C-S-s")  [\C-\S-\s])
(define-key input-decode-map (kbd "C-S-t")  [\C-\S-\t])
(define-key input-decode-map (kbd "C-S-u")  [\C-\S-\u])
(define-key input-decode-map (kbd "C-S-v")  [\C-\S-\v])
(define-key input-decode-map (kbd "C-S-w")  [\C-\S-\w])
(define-key input-decode-map (kbd "C-S-x")  [\C-\S-\x])
(define-key input-decode-map (kbd "C-S-y")  [\C-\S-\y])
(define-key input-decode-map (kbd "C-S-z")  [\C-\S-\z])
(define-key input-decode-map (kbd "C-S-[")  [\C-\S-\[])
(define-key input-decode-map (kbd "C-S-]")  [\C-\S-\]])
(define-key input-decode-map (kbd "C-S-\\") [\C-\S-\\])
(define-key input-decode-map (kbd "C-S-;")  [\C-\S-\;])
(define-key input-decode-map (kbd "C-S-'")  [\C-\S-\'])
(define-key input-decode-map (kbd "C-S-,")  [\C-\S-\,])
(define-key input-decode-map (kbd "C-S-.")  [\C-\S-\.])
(define-key input-decode-map (kbd "C-S-/")  [\C-\S-\/])
(define-key input-decode-map (kbd "C-S-{")  [\C-\S-\{])
(define-key input-decode-map (kbd "C-S-}")  [\C-\S-\}])
(define-key input-decode-map (kbd "C-S-|")  [\C-\S-\|])
(define-key input-decode-map (kbd "C-S-:")  [\C-\S-\:])
(define-key input-decode-map (kbd "C-S-\"") [\C-\S-\"])
(define-key input-decode-map (kbd "C-S-<")  [\C-\S-\<])
(define-key input-decode-map (kbd "C-S->")  [\C-\S-\>])
(define-key input-decode-map (kbd "C-S-?")  [\C-\S-\?])
(define-key input-decode-map (kbd "C-S-`")  [\C-\S-\`])
(define-key input-decode-map (kbd "C-S-1")  [\C-\S-\1])
(define-key input-decode-map (kbd "C-S-2")  [\C-\S-\2])
(define-key input-decode-map (kbd "C-S-3")  [\C-\S-\3])
(define-key input-decode-map (kbd "C-S-4")  [\C-\S-\4])
(define-key input-decode-map (kbd "C-S-5")  [\C-\S-\5])
(define-key input-decode-map (kbd "C-S-6")  [\C-\S-\6])
(define-key input-decode-map (kbd "C-S-7")  [\C-\S-\7])
(define-key input-decode-map (kbd "C-S-8")  [\C-\S-\8])
(define-key input-decode-map (kbd "C-S-9")  [\C-\S-\9])
(define-key input-decode-map (kbd "C-S-0")  [\C-\S-\0])
(define-key input-decode-map (kbd "C-S--")  [\C-\S-\-])
(define-key input-decode-map (kbd "C-S-=")  [\C-\S-\=])
(define-key input-decode-map (kbd "C-S-~")  [\C-\S-\~])
(define-key input-decode-map (kbd "C-S-!")  [\C-\S-\!])
(define-key input-decode-map (kbd "C-S-@")  [\C-\S-\@])
(define-key input-decode-map (kbd "C-S-#")  [\C-\S-\#])
(define-key input-decode-map (kbd "C-S-$")  [\C-\S-\$])
(define-key input-decode-map (kbd "C-S-%")  [\C-\S-\%])
(define-key input-decode-map (kbd "C-S-^")  [\C-\S-\^])
(define-key input-decode-map (kbd "C-S-&")  [\C-\S-\&])
(define-key input-decode-map (kbd "C-S-*")  [\C-\S-\*])
(define-key input-decode-map (kbd "C-S-(")  [\C-\S-\(])
(define-key input-decode-map (kbd "C-S-)")  [\C-\S-\)])
(define-key input-decode-map (kbd "C-S-_")  [\C-\S-\_])
(define-key input-decode-map (kbd "C-S-+")  [\C-\S-\+])

(define-key input-decode-map (kbd "M-a")  [\M-\a])
(define-key input-decode-map (kbd "M-b")  [\M-\b])
(define-key input-decode-map (kbd "M-c")  [\M-\c])
(define-key input-decode-map (kbd "M-d")  [\M-\d])
(define-key input-decode-map (kbd "M-e")  [\M-\e])
(define-key input-decode-map (kbd "M-f")  [\M-\f])
(define-key input-decode-map (kbd "M-g")  [\M-\g])
(define-key input-decode-map (kbd "M-h")  [\M-\h])
(define-key input-decode-map (kbd "M-i")  [\M-\i])
(define-key input-decode-map (kbd "M-j")  [\M-\j])
(define-key input-decode-map (kbd "M-k")  [\M-\k])
(define-key input-decode-map (kbd "M-l")  [\M-\l])
(define-key input-decode-map (kbd "M-m")  [\M-\m])
(define-key input-decode-map (kbd "M-n")  [\M-\n])
(define-key input-decode-map (kbd "M-o")  [\M-\o])
(define-key input-decode-map (kbd "M-p")  [\M-\p])
(define-key input-decode-map (kbd "M-q")  [\M-\q])
(define-key input-decode-map (kbd "M-r")  [\M-\r])
(define-key input-decode-map (kbd "M-s")  [\M-\s])
(define-key input-decode-map (kbd "M-t")  [\M-\t])
(define-key input-decode-map (kbd "M-u")  [\M-\u])
(define-key input-decode-map (kbd "M-v")  [\M-\v])
(define-key input-decode-map (kbd "M-w")  [\M-\w])
(define-key input-decode-map (kbd "M-x")  [\M-\x])
(define-key input-decode-map (kbd "M-y")  [\M-\y])
(define-key input-decode-map (kbd "M-z")  [\M-\z])
(define-key input-decode-map (kbd "M-[")  [\M-\[])
(define-key input-decode-map (kbd "M-]")  [\M-\]])
(define-key input-decode-map (kbd "M-\\") [\M-\\])
(define-key input-decode-map (kbd "M-;")  [\M-\;])
(define-key input-decode-map (kbd "M-'")  [\M-\'])
(define-key input-decode-map (kbd "M-,")  [\M-\,])
(define-key input-decode-map (kbd "M-.")  [\M-\.])
(define-key input-decode-map (kbd "M-/")  [\M-\/])
(define-key input-decode-map (kbd "M-{")  [\M-\{])
(define-key input-decode-map (kbd "M-}")  [\M-\}])
(define-key input-decode-map (kbd "M-|")  [\M-\|])
(define-key input-decode-map (kbd "M-:")  [\M-\:])
(define-key input-decode-map (kbd "M-\"") [\M-\"])
(define-key input-decode-map (kbd "M-<")  [\M-\<])
(define-key input-decode-map (kbd "M->")  [\M-\>])
(define-key input-decode-map (kbd "M-?")  [\M-\?])
(define-key input-decode-map (kbd "M-`")  [\M-\`])
(define-key input-decode-map (kbd "M-1")  [\M-\1])
(define-key input-decode-map (kbd "M-2")  [\M-\2])
(define-key input-decode-map (kbd "M-3")  [\M-\3])
(define-key input-decode-map (kbd "M-4")  [\M-\4])
(define-key input-decode-map (kbd "M-5")  [\M-\5])
(define-key input-decode-map (kbd "M-6")  [\M-\6])
(define-key input-decode-map (kbd "M-7")  [\M-\7])
(define-key input-decode-map (kbd "M-8")  [\M-\8])
(define-key input-decode-map (kbd "M-9")  [\M-\9])
(define-key input-decode-map (kbd "M-0")  [\M-\0])
(define-key input-decode-map (kbd "M--")  [\M-\-])
(define-key input-decode-map (kbd "M-=")  [\M-\=])
(define-key input-decode-map (kbd "M-~")  [\M-\~])
(define-key input-decode-map (kbd "M-!")  [\M-\!])
(define-key input-decode-map (kbd "M-@")  [\M-\@])
(define-key input-decode-map (kbd "M-#")  [\M-\#])
(define-key input-decode-map (kbd "M-$")  [\M-\$])
(define-key input-decode-map (kbd "M-%")  [\M-\%])
(define-key input-decode-map (kbd "M-^")  [\M-\^])
(define-key input-decode-map (kbd "M-&")  [\M-\&])
(define-key input-decode-map (kbd "M-*")  [\M-\*])
(define-key input-decode-map (kbd "M-(")  [\M-\(])
(define-key input-decode-map (kbd "M-)")  [\M-\)])
(define-key input-decode-map (kbd "M-_")  [\M-\_])
(define-key input-decode-map (kbd "M-+")  [\M-\+])

(define-key input-decode-map (kbd "M-A")    [\M-\S-\a])
(define-key input-decode-map (kbd "M-B")    [\M-\S-\b])
(define-key input-decode-map (kbd "M-C")    [\M-\S-\c])
(define-key input-decode-map (kbd "M-D")    [\M-\S-\d])
(define-key input-decode-map (kbd "M-E")    [\M-\S-\e])
(define-key input-decode-map (kbd "M-F")    [\M-\S-\f])
(define-key input-decode-map (kbd "M-G")    [\M-\S-\g])
(define-key input-decode-map (kbd "M-H")    [\M-\S-\h])
(define-key input-decode-map (kbd "M-I")    [\M-\S-\i])
(define-key input-decode-map (kbd "M-J")    [\M-\S-\j])
(define-key input-decode-map (kbd "M-K")    [\M-\S-\k])
(define-key input-decode-map (kbd "M-L")    [\M-\S-\l])
(define-key input-decode-map (kbd "M-M")    [\M-\S-\m])
(define-key input-decode-map (kbd "M-N")    [\M-\S-\n])
(define-key input-decode-map (kbd "M-O")    [\M-\S-\o])
(define-key input-decode-map (kbd "M-P")    [\M-\S-\p])
(define-key input-decode-map (kbd "M-Q")    [\M-\S-\q])
(define-key input-decode-map (kbd "M-R")    [\M-\S-\r])
(define-key input-decode-map (kbd "M-S")    [\M-\S-\s])
(define-key input-decode-map (kbd "M-T")    [\M-\S-\t])
(define-key input-decode-map (kbd "M-U")    [\M-\S-\u])
(define-key input-decode-map (kbd "M-V")    [\M-\S-\v])
(define-key input-decode-map (kbd "M-W")    [\M-\S-\w])
(define-key input-decode-map (kbd "M-X")    [\M-\S-\x])
(define-key input-decode-map (kbd "M-Y")    [\M-\S-\y])
(define-key input-decode-map (kbd "M-Z")    [\M-\S-\z])
(define-key input-decode-map (kbd "M-S-[")  [\M-\S-\[])
(define-key input-decode-map (kbd "M-S-]")  [\M-\S-\]])
(define-key input-decode-map (kbd "M-S-\\") [\M-\S-\\])
(define-key input-decode-map (kbd "M-S-;")  [\M-\S-\;])
(define-key input-decode-map (kbd "M-S-'")  [\M-\S-\'])
(define-key input-decode-map (kbd "M-S-,")  [\M-\S-\,])
(define-key input-decode-map (kbd "M-S-.")  [\M-\S-\.])
(define-key input-decode-map (kbd "M-S-/")  [\M-\S-\/])
(define-key input-decode-map (kbd "M-S-{")  [\M-\S-\{])
(define-key input-decode-map (kbd "M-S-}")  [\M-\S-\}])
(define-key input-decode-map (kbd "M-S-|")  [\M-\S-\|])
(define-key input-decode-map (kbd "M-S-:")  [\M-\S-\:])
(define-key input-decode-map (kbd "M-S-\"") [\M-\S-\"])
(define-key input-decode-map (kbd "M-S-<")  [\M-\S-\<])
(define-key input-decode-map (kbd "M-S->")  [\M-\S-\>])
(define-key input-decode-map (kbd "M-S-?")  [\M-\S-\?])
(define-key input-decode-map (kbd "M-S-`")  [\M-\S-\`])
(define-key input-decode-map (kbd "M-S-1")  [\M-\S-\1])
(define-key input-decode-map (kbd "M-S-2")  [\M-\S-\2])
(define-key input-decode-map (kbd "M-S-3")  [\M-\S-\3])
(define-key input-decode-map (kbd "M-S-4")  [\M-\S-\4])
(define-key input-decode-map (kbd "M-S-5")  [\M-\S-\5])
(define-key input-decode-map (kbd "M-S-6")  [\M-\S-\6])
(define-key input-decode-map (kbd "M-S-7")  [\M-\S-\7])
(define-key input-decode-map (kbd "M-S-8")  [\M-\S-\8])
(define-key input-decode-map (kbd "M-S-9")  [\M-\S-\9])
(define-key input-decode-map (kbd "M-S-0")  [\M-\S-\0])
(define-key input-decode-map (kbd "M-S--")  [\M-\S-\-])
(define-key input-decode-map (kbd "M-S-=")  [\M-\S-\=])
(define-key input-decode-map (kbd "M-S-~")  [\M-\S-\~])
(define-key input-decode-map (kbd "M-S-!")  [\M-\S-\!])
(define-key input-decode-map (kbd "M-S-@")  [\M-\S-\@])
(define-key input-decode-map (kbd "M-S-#")  [\M-\S-\#])
(define-key input-decode-map (kbd "M-S-$")  [\M-\S-\$])
(define-key input-decode-map (kbd "M-S-%")  [\M-\S-\%])
(define-key input-decode-map (kbd "M-S-^")  [\M-\S-\^])
(define-key input-decode-map (kbd "M-S-&")  [\M-\S-\&])
(define-key input-decode-map (kbd "M-S-*")  [\M-\S-\*])
(define-key input-decode-map (kbd "M-S-(")  [\M-\S-\(])
(define-key input-decode-map (kbd "M-S-)")  [\M-\S-\)])
(define-key input-decode-map (kbd "M-S-_")  [\M-\S-\_])
(define-key input-decode-map (kbd "M-S-+")  [\M-\S-\+])

(define-key input-decode-map (kbd "C-M-a")  [\C-\M-\a])
(define-key input-decode-map (kbd "C-M-b")  [\C-\M-\b])
(define-key input-decode-map (kbd "C-M-c")  [\C-\M-\c])
(define-key input-decode-map (kbd "C-M-d")  [\C-\M-\d])
(define-key input-decode-map (kbd "C-M-e")  [\C-\M-\e])
(define-key input-decode-map (kbd "C-M-f")  [\C-\M-\f])
(define-key input-decode-map (kbd "C-M-g")  [\C-\M-\g])
(define-key input-decode-map (kbd "C-M-h")  [\C-\M-\h])
(define-key input-decode-map (kbd "C-M-i")  [\C-\M-\i])
(define-key input-decode-map (kbd "C-M-j")  [\C-\M-\j])
(define-key input-decode-map (kbd "C-M-k")  [\C-\M-\k])
(define-key input-decode-map (kbd "C-M-l")  [\C-\M-\l])
(define-key input-decode-map (kbd "C-M-m")  [\C-\M-\m])
(define-key input-decode-map (kbd "C-M-n")  [\C-\M-\n])
(define-key input-decode-map (kbd "C-M-o")  [\C-\M-\o])
(define-key input-decode-map (kbd "C-M-p")  [\C-\M-\p])
(define-key input-decode-map (kbd "C-M-q")  [\C-\M-\q])
(define-key input-decode-map (kbd "C-M-r")  [\C-\M-\r])
(define-key input-decode-map (kbd "C-M-s")  [\C-\M-\s])
(define-key input-decode-map (kbd "C-M-t")  [\C-\M-\t])
(define-key input-decode-map (kbd "C-M-u")  [\C-\M-\u])
(define-key input-decode-map (kbd "C-M-v")  [\C-\M-\v])
(define-key input-decode-map (kbd "C-M-w")  [\C-\M-\w])
(define-key input-decode-map (kbd "C-M-x")  [\C-\M-\x])
(define-key input-decode-map (kbd "C-M-y")  [\C-\M-\y])
(define-key input-decode-map (kbd "C-M-z")  [\C-\M-\z])
(define-key input-decode-map (kbd "C-M-[")  [\C-\M-\[])
(define-key input-decode-map (kbd "C-M-]")  [\C-\M-\]])
(define-key input-decode-map (kbd "C-M-\\") [\C-\M-\\])
(define-key input-decode-map (kbd "C-M-;")  [\C-\M-\;])
(define-key input-decode-map (kbd "C-M-'")  [\C-\M-\'])
(define-key input-decode-map (kbd "C-M-,")  [\C-\M-\,])
(define-key input-decode-map (kbd "C-M-.")  [\C-\M-\.])
(define-key input-decode-map (kbd "C-M-/")  [\C-\M-\/])
(define-key input-decode-map (kbd "C-M-{")  [\C-\M-\{])
(define-key input-decode-map (kbd "C-M-}")  [\C-\M-\}])
(define-key input-decode-map (kbd "C-M-|")  [\C-\M-\|])
(define-key input-decode-map (kbd "C-M-:")  [\C-\M-\:])
(define-key input-decode-map (kbd "C-M-\"") [\C-\M-\"])
(define-key input-decode-map (kbd "C-M-<")  [\C-\M-\<])
(define-key input-decode-map (kbd "C-M->")  [\C-\M-\>])
(define-key input-decode-map (kbd "C-M-?")  [\C-\M-\?])
(define-key input-decode-map (kbd "C-M-`")  [\C-\M-\`])
(define-key input-decode-map (kbd "C-M-1")  [\C-\M-\1])
(define-key input-decode-map (kbd "C-M-2")  [\C-\M-\2])
(define-key input-decode-map (kbd "C-M-3")  [\C-\M-\3])
(define-key input-decode-map (kbd "C-M-4")  [\C-\M-\4])
(define-key input-decode-map (kbd "C-M-5")  [\C-\M-\5])
(define-key input-decode-map (kbd "C-M-6")  [\C-\M-\6])
(define-key input-decode-map (kbd "C-M-7")  [\C-\M-\7])
(define-key input-decode-map (kbd "C-M-8")  [\C-\M-\8])
(define-key input-decode-map (kbd "C-M-9")  [\C-\M-\9])
(define-key input-decode-map (kbd "C-M-0")  [\C-\M-\0])
(define-key input-decode-map (kbd "C-M--")  [\C-\M-\-])
(define-key input-decode-map (kbd "C-M-=")  [\C-\M-\=])
(define-key input-decode-map (kbd "C-M-~")  [\C-\M-\~])
(define-key input-decode-map (kbd "C-M-!")  [\C-\M-\!])
(define-key input-decode-map (kbd "C-M-@")  [\C-\M-\@])
(define-key input-decode-map (kbd "C-M-#")  [\C-\M-\#])
(define-key input-decode-map (kbd "C-M-$")  [\C-\M-\$])
(define-key input-decode-map (kbd "C-M-%")  [\C-\M-\%])
(define-key input-decode-map (kbd "C-M-^")  [\C-\M-\^])
(define-key input-decode-map (kbd "C-M-&")  [\C-\M-\&])
(define-key input-decode-map (kbd "C-M-*")  [\C-\M-\*])
(define-key input-decode-map (kbd "C-M-(")  [\C-\M-\(])
(define-key input-decode-map (kbd "C-M-)")  [\C-\M-\)])
(define-key input-decode-map (kbd "C-M-_")  [\C-\M-\_])
(define-key input-decode-map (kbd "C-M-+")  [\C-\M-\+])

(define-key input-decode-map (kbd "C-M-S-a")  [\C-\M-\S-\a])
(define-key input-decode-map (kbd "C-M-S-b")  [\C-\M-\S-\b])
(define-key input-decode-map (kbd "C-M-S-c")  [\C-\M-\S-\c])
(define-key input-decode-map (kbd "C-M-S-d")  [\C-\M-\S-\d])
(define-key input-decode-map (kbd "C-M-S-e")  [\C-\M-\S-\e])
(define-key input-decode-map (kbd "C-M-S-f")  [\C-\M-\S-\f])
(define-key input-decode-map (kbd "C-M-S-g")  [\C-\M-\S-\g])
(define-key input-decode-map (kbd "C-M-S-h")  [\C-\M-\S-\h])
(define-key input-decode-map (kbd "C-M-S-i")  [\C-\M-\S-\i])
(define-key input-decode-map (kbd "C-M-S-j")  [\C-\M-\S-\j])
(define-key input-decode-map (kbd "C-M-S-k")  [\C-\M-\S-\k])
(define-key input-decode-map (kbd "C-M-S-l")  [\C-\M-\S-\l])
(define-key input-decode-map (kbd "C-M-S-m")  [\C-\M-\S-\m])
(define-key input-decode-map (kbd "C-M-S-n")  [\C-\M-\S-\n])
(define-key input-decode-map (kbd "C-M-S-o")  [\C-\M-\S-\o])
(define-key input-decode-map (kbd "C-M-S-p")  [\C-\M-\S-\p])
(define-key input-decode-map (kbd "C-M-S-q")  [\C-\M-\S-\q])
(define-key input-decode-map (kbd "C-M-S-r")  [\C-\M-\S-\r])
(define-key input-decode-map (kbd "C-M-S-s")  [\C-\M-\S-\s])
(define-key input-decode-map (kbd "C-M-S-t")  [\C-\M-\S-\t])
(define-key input-decode-map (kbd "C-M-S-u")  [\C-\M-\S-\u])
(define-key input-decode-map (kbd "C-M-S-v")  [\C-\M-\S-\v])
(define-key input-decode-map (kbd "C-M-S-w")  [\C-\M-\S-\w])
(define-key input-decode-map (kbd "C-M-S-x")  [\C-\M-\S-\x])
(define-key input-decode-map (kbd "C-M-S-y")  [\C-\M-\S-\y])
(define-key input-decode-map (kbd "C-M-S-z")  [\C-\M-\S-\z])
(define-key input-decode-map (kbd "C-M-S-[")  [\C-\M-\S-\[])
(define-key input-decode-map (kbd "C-M-S-]")  [\C-\M-\S-\]])
(define-key input-decode-map (kbd "C-M-S-\\") [\C-\M-\S-\\])
(define-key input-decode-map (kbd "C-M-S-;")  [\C-\M-\S-\;])
(define-key input-decode-map (kbd "C-M-S-'")  [\C-\M-\S-\'])
(define-key input-decode-map (kbd "C-M-S-,")  [\C-\M-\S-\,])
(define-key input-decode-map (kbd "C-M-S-.")  [\C-\M-\S-\.])
(define-key input-decode-map (kbd "C-M-S-/")  [\C-\M-\S-\/])
(define-key input-decode-map (kbd "C-M-S-{")  [\C-\M-\S-\{])
(define-key input-decode-map (kbd "C-M-S-}")  [\C-\M-\S-\}])
(define-key input-decode-map (kbd "C-M-S-|")  [\C-\M-\S-\|])
(define-key input-decode-map (kbd "C-M-S-:")  [\C-\M-\S-\:])
(define-key input-decode-map (kbd "C-M-S-\"") [\C-\M-\S-\"])
(define-key input-decode-map (kbd "C-M-S-<")  [\C-\M-\S-\<])
(define-key input-decode-map (kbd "C-M-S->")  [\C-\M-\S-\>])
(define-key input-decode-map (kbd "C-M-S-?")  [\C-\M-\S-\?])
(define-key input-decode-map (kbd "C-M-S-`")  [\C-\M-\S-\`])
(define-key input-decode-map (kbd "C-M-S-1")  [\C-\M-\S-\1])
(define-key input-decode-map (kbd "C-M-S-2")  [\C-\M-\S-\2])
(define-key input-decode-map (kbd "C-M-S-3")  [\C-\M-\S-\3])
(define-key input-decode-map (kbd "C-M-S-4")  [\C-\M-\S-\4])
(define-key input-decode-map (kbd "C-M-S-5")  [\C-\M-\S-\5])
(define-key input-decode-map (kbd "C-M-S-6")  [\C-\M-\S-\6])
(define-key input-decode-map (kbd "C-M-S-7")  [\C-\M-\S-\7])
(define-key input-decode-map (kbd "C-M-S-8")  [\C-\M-\S-\8])
(define-key input-decode-map (kbd "C-M-S-9")  [\C-\M-\S-\9])
(define-key input-decode-map (kbd "C-M-S-0")  [\C-\M-\S-\0])
(define-key input-decode-map (kbd "C-M-S--")  [\C-\M-\S-\-])
(define-key input-decode-map (kbd "C-M-S-=")  [\C-\M-\S-\=])
(define-key input-decode-map (kbd "C-M-S-~")  [\C-\M-\S-\~])
(define-key input-decode-map (kbd "C-M-S-!")  [\C-\M-\S-\!])
(define-key input-decode-map (kbd "C-M-S-@")  [\C-\M-\S-\@])
(define-key input-decode-map (kbd "C-M-S-#")  [\C-\M-\S-\#])
(define-key input-decode-map (kbd "C-M-S-$")  [\C-\M-\S-\$])
(define-key input-decode-map (kbd "C-M-S-%")  [\C-\M-\S-\%])
(define-key input-decode-map (kbd "C-M-S-^")  [\C-\M-\S-\^])
(define-key input-decode-map (kbd "C-M-S-&")  [\C-\M-\S-\&])
(define-key input-decode-map (kbd "C-M-S-*")  [\C-\M-\S-\*])
(define-key input-decode-map (kbd "C-M-S-(")  [\C-\M-\S-\(])
(define-key input-decode-map (kbd "C-M-S-)")  [\C-\M-\S-\)])
(define-key input-decode-map (kbd "C-M-S-_")  [\C-\M-\S-\_])
(define-key input-decode-map (kbd "C-M-S-+")  [\C-\M-\S-\+])

(define-key input-decode-map (kbd "<backspace>")       (kbd "<jd:bks>"))
(define-key input-decode-map (kbd "S-<backspace>")     (kbd "<jd:S-bks>"))
(define-key input-decode-map (kbd "C-<backspace>")     (kbd "<jd:C-bks>"))
(define-key input-decode-map (kbd "C-S-<backspace>")   (kbd "<jd:C-S-bks>"))
(define-key input-decode-map (kbd "M-<backspace>")     (kbd "<jd:M-bks>"))
(define-key input-decode-map (kbd "M-S-<backspace>")   (kbd "<jd:M-S-bks>"))
(define-key input-decode-map (kbd "C-M-<backspace>")   (kbd "<jd:C-M-bks>"))
(define-key input-decode-map (kbd "C-M-S-<backspace>") (kbd "<jd:C-M-S-bks>"))

(define-key input-decode-map (kbd "<escape>")       (kbd "<jd:esc>"))
(define-key input-decode-map (kbd "S-<escape>")     (kbd "<jd:S-esc>"))
(define-key input-decode-map (kbd "C-<escape>")     (kbd "<jd:C-esc>"))
(define-key input-decode-map (kbd "C-S-<escape>")   (kbd "<jd:C-S-esc>"))
(define-key input-decode-map (kbd "M-<escape>")     (kbd "<jd:M-esc>"))
(define-key input-decode-map (kbd "M-S-<escape>")   (kbd "<jd:M-S-esc>"))
(define-key input-decode-map (kbd "C-M-<escape>")   (kbd "<jd:C-M-esc>"))
(define-key input-decode-map (kbd "C-M-S-<escape>") (kbd "<jd:C-M-S-esc>"))

(define-key input-decode-map (kbd "<return>")       (kbd "<jd:ret>"))
(define-key input-decode-map (kbd "S-<return>")     (kbd "<jd:S-ret>"))
(define-key input-decode-map (kbd "C-<return>")     (kbd "<jd:C-ret>"))
(define-key input-decode-map (kbd "C-S-<return>")   (kbd "<jd:C-S-ret>"))
(define-key input-decode-map (kbd "M-<return>")     (kbd "<jd:M-ret>"))
(define-key input-decode-map (kbd "M-S-<return>")   (kbd "<jd:M-S-ret>"))
(define-key input-decode-map (kbd "C-M-<return>")   (kbd "<jd:C-M-ret>"))
(define-key input-decode-map (kbd "C-M-S-<return>") (kbd "<jd:C-M-S-ret>"))

(define-key input-decode-map (kbd "<SPC>")       (kbd "<jd:spc>"))
(define-key input-decode-map (kbd "S-<SPC>")     (kbd "<jd:S-spc>"))
(define-key input-decode-map (kbd "C-<SPC>")     (kbd "<jd:C-spc>"))
(define-key input-decode-map (kbd "C-S-<SPC>")   (kbd "<jd:C-S-spc>"))
(define-key input-decode-map (kbd "M-<SPC>")     (kbd "<jd:M-spc>"))
(define-key input-decode-map (kbd "M-S-<SPC>")   (kbd "<jd:M-S-spc>"))
(define-key input-decode-map (kbd "C-M-<SPC>")   (kbd "<jd:C-M-spc>"))
(define-key input-decode-map (kbd "C-M-S-<SPC>") (kbd "<jd:C-M-S-spc>"))

(define-key input-decode-map (kbd "<tab>")               (kbd "<jd:tab>"))
(define-key input-decode-map (kbd "S-<iso-lefttab>")     (kbd "<jd:S-tab>"))
(define-key input-decode-map (kbd "C-<tab>")             (kbd "<jd:C-tab>"))
(define-key input-decode-map (kbd "C-S-<iso-lefttab>")   (kbd "<jd:C-S-tab>"))
(define-key input-decode-map (kbd "M-<tab>")             (kbd "<jd:M-tab>"))
(define-key input-decode-map (kbd "M-S-<iso-lefttab>")   (kbd "<jd:M-S-tab>"))
(define-key input-decode-map (kbd "C-M-<tab>")           (kbd "<jd:C-M-tab>"))
(define-key input-decode-map (kbd "C-M-S-<iso-lefttab>") (kbd "<jd:C-M-S-tab>"))

;; (for in the future when I get the hang of Elisp)
;; (define-key input-decode-map (kbd "<mouse-1>")       (kbd "<jd:m1>"))
;; (define-key input-decode-map (kbd "<mouse-4>")       (kbd "<jd:m4>"))
;; (define-key input-decode-map (kbd "<mouse-5>")       (kbd "<jd:m5>"))
;; (define-key input-decode-map (kbd "<down-mouse-1>")  (kbd "<jd:down-m1>"))
;; (define-key input-decode-map (kbd "<drag-mouse-1>")  (kbd "<jd:drag-m1>"))
;; (define-key input-decode-map (kbd "<mode-line>")     (kbd "<jd:ml>"))
;; (define-key input-decode-map (kbd "<vertical-line>") (kbd "<jd:vl>"))

