;; Faces.
(defvar dired-directory)
(defvar dired-flagged)
(defvar dired-header)
(defvar dired-ignored)
(defvar dired-mark)
(defvar dired-marked)
(defvar dired-perm-write)
(defvar dired-symlink)
(defvar dired-warning)

;; Customization variables.
(defvar dired-after-readin-hook)
(defvar dired-always-read-filesystem)
(defvar dired-auto-revert-buffer)
(defvar dired-before-readin-hook)
(defvar dired-chmod-program)
(defvar dired-chown-program)
(defvar dired-copy-preserve-time)
(defvar dired-dnd-protocol-alist)
(defvar dired-dwim-target)
(defvar dired-garbage-files-regexp)
(defvar dired-hide-details-hide-information-lines)
(defvar dired-hide-details-hide-symlink-targets)
(defvar dired-initial-position-hook)
(defvar dired-keep-marker-copy)
(defvar dired-keep-marker-hardlink)
(defvar dired-keep-marker-rename)
(defvar dired-keep-marker-symlink)
(defvar dired-listing-switches)
(defvar dired-load-hook)
(defvar dired-ls-F-marks-symlinks)
(defvar dired-mode-hook)
(defvar dired-no-confirm)
(defvar dired-recursive-copies)
(defvar dired-recursive-deletes)
(defvar dired-subdir-switches)
(defvar dired-touch-program)
(defvar dired-trivial-filenames)
(defvar dired-use-ls-dired)

(defun jd:dired-mode-hook ()
  (font-lock-mode 1)
  (idle-highlight-mode 1))

(add-hook 'dired-mode-hook 'jd:dired-mode-hook)

(provide 'jd:dired-st)
