;; Faces.
(defvar sh-escaped-newline)
(defvar sh-heredoc)
(defvar sh-quoted-exec)

;; Customization Variables.
(defvar sh-alias-alist)
(defvar sh-ancestor-alist)
(defvar sh-assignment-regexp)
(defvar sh-backslash-align)
(defvar sh-backslash-column)
(defvar sh-basic-offset)
(defvar sh-beginning-of-command)
(defvar sh-blink)
(defvar sh-builtins)
(defvar sh-dynamic-complete-functions)
(defvar sh-end-of-command)
(defvar sh-first-lines-indent)
(defvar sh-here-document-word)
(defvar sh-imenu-generic-expression)
(defvar sh-indent-after-case)
(defvar sh-indent-after-continuation)
(defvar sh-indent-after-do)
(defvar sh-indent-after-done)
(defvar sh-indent-after-else)
(defvar sh-indent-after-function)
(defvar sh-indent-after-if)
(defvar sh-indent-after-loop-construct)
(defvar sh-indent-after-open)
(defvar sh-indent-after-switch)
(defvar sh-indent-comment)
(defvar sh-indent-for-case-alt)
(defvar sh-indent-for-case-label)
(defvar sh-indent-for-continuation)
(defvar sh-indent-for-do)
(defvar sh-indent-for-done)
(defvar sh-indent-for-else)
(defvar sh-indent-for-fi)
(defvar sh-indent-for-then)
(defvar sh-leading-keywords)
(defvar sh-learn-basic-offset)
(defvar sh-mode-hook)
(defvar sh-other-keywords)
(defvar sh-popup-occur-buffer)
(defvar sh-remember-variable-min)
(defvar sh-set-shell-hook)
(defvar sh-shell-arg)
(defvar sh-shell-file)

(defun jd:sh-mode-hook ()
  (electric-pair-mode 1)
  (font-lock-mode 1)
  (idle-highlight-mode 1))

(add-hook 'sh-mode-hook 'jd:sh-mode-hook)

(jd:provide-feature jd:sh-script-st)
