;;; Author: John DeBord

(defconst jd:path-prefix
  (concat (getenv "HOME") "/.emacs.d/"))

(defconst jd:elc-prefix
  (concat jd:path-prefix ".elc/"))

(defconst jd:site-lisp-prefix
  "/home/johndebord/install/share/emacs/26.3.50/lisp/")

(defconst jd:load-from-byte-compiled-dir-p
  (if (directory-files jd:path-prefix nil ".+\\.elc")
      t
    nil))

(defconst jd:global-prefix
  (if jd:load-from-byte-compiled-dir-p
      (concat jd:path-prefix ".elc/config/global/")
    (concat jd:path-prefix "config/global/")))

(defconst jd:global-elisp-files-prefix
  (concat jd:path-prefix "config/global/"))

(defconst jd:external-prefix
  (if jd:load-from-byte-compiled-dir-p
      (concat jd:path-prefix ".elc/config/external/")
    (concat jd:path-prefix "config/external/")))

(defconst jd:external-elisp-files-prefix
  (concat jd:path-prefix "config/external/"))

(defconst jd:internal-prefix
  (if jd:load-from-byte-compiled-dir-p
      (concat jd:path-prefix ".elc/config/internal/")
    (concat jd:path-prefix "config/internal/")))

(defconst jd:internal-elisp-files-prefix
  (concat jd:path-prefix "config/internal/"))

(defconst jd:elpa-prefix
  (concat jd:path-prefix "config/external/elpa/"))

(with-temp-buffer
  (insert-file-contents (concat (getenv "HOME") "/.authinfo"))
  (let* ((line (split-string (buffer-string) "\n"))
         (username (nth 0 line))
         (password (nth 1 line)))
    (defconst jd:irc-nickname username)
    (defconst jd:irc-password password)))

(setq-default package-user-dir jd:elpa-prefix)
(package-initialize)
(setq-default package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                                 ("melpa" . "http://melpa.milkbox.net/packages/")
                                 ("marmalade" . "http://marmalade-repo.org/packages/")))

;;; `alloc.c`
(setq-default gc-cons-threshold 64000000)

;;; `buffer.c`
(setq-default default-directory jd:path-prefix)
(setq-default truncate-lines nil)
(setq-default fill-column 80)
(put 'erase-buffer 'disabled nil)

;;; `callproc.c`
(setq-default exec-path
              (list "/home/johndebord/install/bin"
                    "/bin"
                    "/sbin"
                    "/usr/bin"
                    "/usr/sbin"
                    "/usr/local/bin"
                    "/usr/local/sbin"))

;;; `editfns.c`
(put 'narrow-to-region 'disabled nil)

;;; `fns.c`
(defalias 'yes-or-no-p 'y-or-n-p)

;;; `frame.c`
(setq-default make-pointer-invisible nil)
(add-to-list 'default-frame-alist '(fullscreen . maximized))

;;; `indent.c`
(setq-default indent-tabs-mode nil)

;;; `keyboard.c`
(setq-default echo-keystrokes 0.001)
(setq-default meta-prefix-char nil)
(setq-default show-help-function nil)

;;; `minibuf.c`
(setq-default enable-recursive-minibuffers t)

;;; `xdisp.c`
(setq-default hscroll-margin 2)
(setq-default hscroll-step 14)
(setq-default x-stretch-cursor 1)

(defmacro jd:load-feature (feature &rest prefixes)
  `(if jd:load-from-byte-compiled-dir-p
       (load (concat ,@prefixes (symbol-name ',feature) ".elc"))
     (load (concat ,@prefixes (symbol-name ',feature) ".el"))))

(jd:load-feature jd:external-config jd:external-prefix)
(jd:load-feature jd:global-config jd:global-prefix)
(jd:load-feature jd:internal-config jd:internal-prefix)

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#131313" :foreground "#e6e6e6" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 110 :width normal :foundry "ibm" :family "Courier"))))
 '(border ((t (:background "purple" :foreground "black"))))
 '(buffer-menu-buffer ((t (:weight bold))))
 '(button ((t (:background "#d3d3d3" :foreground "#000000" :box (:line-width 1 :style released-button) :weight normal))))
 '(c-annotation-face ((t (:background "purple" :foreground "black"))))
 '(c-nonbreakable-space-face ((t (:background "purple" :foreground "black"))) t)
 '(calendar-month-header ((t (:background "purple" :foreground "black"))))
 '(calendar-today ((t (:background "purple" :foreground "black"))))
 '(calendar-weekday-header ((t (:background "purple" :foreground "black"))))
 '(calendar-weekend-header ((t (:background "purple" :foreground "black"))))
 '(change-log-acknowledgment ((t nil)))
 '(change-log-conditionals ((t (:background "purple" :foreground "black"))))
 '(change-log-date ((t nil)))
 '(change-log-email ((t nil)))
 '(change-log-file ((t (:background "purple" :foreground "black"))))
 '(change-log-function ((t (:background "purple" :foreground "black"))))
 '(change-log-list ((t (:background "purple" :foreground "black"))))
 '(change-log-name ((t nil)))
 '(comint-highlight-input ((t (:background "#323232" :foreground "#e6e6e6"))))
 '(comint-highlight-prompt ((t (:foreground "#e6e6e6"))))
 '(company-echo ((t (:background "purple" :foreground "black"))) t)
 '(company-echo-common ((t (:background "purple" :foreground "black"))))
 '(company-preview ((t (:background "purple" :foreground "black"))))
 '(company-preview-common ((t (:background "purple" :foreground "black"))))
 '(company-preview-search ((t (:background "purple" :foreground "black"))))
 '(company-scrollbar-bg ((t (:background "#232323"))))
 '(company-scrollbar-fg ((t (:background "#e6e6e6"))))
 '(company-template-field ((t (:background "purple" :foreground "black"))))
 '(company-tooltip ((t (:background "#232323"))))
 '(company-tooltip-annotation ((t (:background "#232323"))))
 '(company-tooltip-annotation-selection ((t (:background "#535353"))))
 '(company-tooltip-common ((t (:background "#232323" :underline "#FFFFFF"))))
 '(company-tooltip-common-selection ((t (:background "#535353" :underline "#FFFFFF"))))
 '(company-tooltip-mouse ((t (:background "#535353"))))
 '(company-tooltip-search ((t (:background "purple" :foreground "black"))))
 '(company-tooltip-search-selection ((t (:background "purple" :foreground "black"))))
 '(company-tooltip-selection ((t (:background "#535353"))))
 '(compilation-column-number ((t nil)))
 '(compilation-error ((t (:foreground "#ff0000" :weight bold))))
 '(compilation-info ((t (:foreground "#569cd6"))))
 '(compilation-line-number ((t nil)))
 '(compilation-mode-line-exit ((t (:foreground "#00cc00" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#ff0000" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#ff7400" :weight bold))))
 '(compilation-warning ((t (:foreground "#ff7400" :weight bold))))
 '(completions-annotations ((t (:slant italic))))
 '(completions-common-part ((t nil)))
 '(completions-first-difference ((t (:weight bold))))
 '(css-property ((t (:background "purple" :foreground "black"))))
 '(css-proprietary-property ((t (:background "purple" :foreground "black"))))
 '(css-selector ((t (:background "purple" :foreground "black"))))
 '(cua-global-mark ((t (:background "purple" :foreground "black"))))
 '(cua-rectangle ((t (:background "purple" :foreground "black"))))
 '(cua-rectangle-noselect ((t (:background "purple" :foreground "black"))))
 '(cursor ((t (:background "#ffffff"))))
 '(custom-button ((t (:background "#d3d3d3" :foreground "#000000" :box (:line-width 1 :style released-button) :weight normal))))
 '(custom-button-mouse ((t (:background "#d3d3d3" :foreground "#000000" :box (:line-width 1 :style released-button) :weight normal))))
 '(custom-button-pressed ((t (:background "#d3d3d3" :foreground "#000000" :box (:line-width 1 :style released-button) :weight normal))))
 '(custom-button-pressed-unraised ((t (:background "purple" :foreground "black"))))
 '(custom-button-unraised ((t (:background "purple" :foreground "black"))))
 '(custom-changed ((t (:background "purple" :foreground "black"))))
 '(custom-comment ((t (:background "purple" :foreground "black"))))
 '(custom-comment-tag ((t (:background "purple" :foreground "black"))))
 '(custom-documentation ((t nil)))
 '(custom-face-tag ((t (:foreground "#569cd6"))))
 '(custom-group-subtitle ((t (:background "purple" :foreground "black"))))
 '(custom-group-tag ((t (:foreground "#569cd6"))))
 '(custom-group-tag-1 ((t (:background "purple" :foreground "black"))))
 '(custom-invalid ((t (:background "purple" :foreground "black"))))
 '(custom-link ((t (:background "#d3d3d3" :foreground "#000000" :box (:line-width 1 :style released-button)))))
 '(custom-modified ((t (:background "purple" :foreground "black"))))
 '(custom-rogue ((t (:background "purple" :foreground "black"))))
 '(custom-saved ((t (:background "purple" :foreground "black"))))
 '(custom-set ((t (:background "purple" :foreground "black"))))
 '(custom-state ((t (:foreground "#00cc00"))))
 '(custom-themed ((t (:background "purple" :foreground "black"))))
 '(custom-variable-button ((t (:background "purple" :foreground "black"))))
 '(custom-variable-tag ((t (:foreground "#569cd6"))))
 '(custom-visibility ((t (:background "#d3d3d3" :foreground "#000000" :box (:line-width 1 :style released-button) :weight normal :height 0.8))))
 '(diary ((t (:background "purple" :foreground "black"))))
 '(diff-added ((t (:foreground "#00cc00"))))
 '(diff-changed ((t (:background "purple" :foreground "black"))))
 '(diff-context ((t nil)))
 '(diff-file-header ((t (:foreground "#5c5c5c"))))
 '(diff-function ((t (:background "purple" :foreground "black"))))
 '(diff-header ((t (:foreground "#5c5c5c"))))
 '(diff-hunk-header ((t (:foreground "#5c5c5c"))))
 '(diff-index ((t (:background "purple" :foreground "black"))))
 '(diff-indicator-added ((t (:foreground "#5c5c5c"))))
 '(diff-indicator-changed ((t (:foreground "#5c5c5c"))))
 '(diff-indicator-removed ((t (:foreground "#5c5c5c"))))
 '(diff-nonexistent ((t (:background "purple" :foreground "black"))))
 '(diff-refine-added ((t (:background "purple" :foreground "black"))))
 '(diff-refine-changed ((t (:background "purple" :foreground "black"))))
 '(diff-refine-removed ((t (:background "purple" :foreground "black"))))
 '(diff-removed ((t (:foreground "#ff0000"))))
 '(dired-directory ((t nil)))
 '(dired-flagged ((t (:background "purple" :foreground "black"))))
 '(dired-header ((t (:foreground "#569cd6"))))
 '(dired-ignored ((t (:background "purple" :foreground "black"))))
 '(dired-mark ((t (:background "purple" :foreground "black"))))
 '(dired-marked ((t (:background "purple" :foreground "black"))))
 '(dired-perm-write ((t nil)))
 '(dired-symlink ((t nil)))
 '(dired-warning ((t (:background "purple" :foreground "black"))))
 '(eldoc-highlight-function-argument ((t (:weight bold))))
 '(error ((t (:foreground "#ff0000"))))
 '(escape-glyph ((t (:foreground "#00ffff"))))
 '(eshell-ls-archive ((t (:foreground "#bd63c5"))))
 '(eshell-ls-backup ((t (:foreground "#5c5c5c"))))
 '(eshell-ls-clutter ((t (:background "purple" :foreground "black"))))
 '(eshell-ls-directory ((t (:foreground "#569cd6"))))
 '(eshell-ls-executable ((t (:foreground "#00cc00"))))
 '(eshell-ls-missing ((t (:foreground "#ff0000"))))
 '(eshell-ls-product ((t nil)))
 '(eshell-ls-readonly ((t (:foreground "#5c5c5c"))))
 '(eshell-ls-special ((t (:foreground "#d6c556"))))
 '(eshell-ls-symlink ((t (:foreground "#4ec9b0"))))
 '(eshell-ls-unreadable ((t nil)))
 '(eshell-prompt ((t (:foreground "#569cd6"))))
 '(ffap ((t (:background "purple" :foreground "black"))))
 '(file-name-shadow ((t (:foreground "#acacac"))))
 '(fixed-pitch ((t nil)))
 '(fixed-pitch-serif ((t (:background "purple" :foreground "black"))))
 '(flycheck-error ((t (:underline (:color "#ff0000" :style wave)))))
 '(flycheck-error-list-checker-name ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-column-number ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-error ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-highlight ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-id ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-id-with-explainer ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-info ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-line-number ((t (:background "purple" :foreground "black"))))
 '(flycheck-error-list-warning ((t (:background "purple" :foreground "black"))))
 '(flycheck-fringe-error ((t (:background "#ff0000" :foreground "#000000"))))
 '(flycheck-fringe-info ((t (:background "#00cc00" :foreground "#000000"))))
 '(flycheck-fringe-warning ((t (:background "#ff7400" :foreground "#000000"))))
 '(flycheck-info ((t (:underline (:color "#00cc00" :style wave)))))
 '(flycheck-warning ((t (:underline (:color "#ff7400" :style wave)))))
 '(flymake-error ((t (:underline (:color "#ff0000" :style wave)))))
 '(flymake-warning ((t (:underline (:color "#ff7400" :style wave)))))
 '(font-lock-builtin-face ((t (:foreground "#569cd6"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#424242"))))
 '(font-lock-comment-face ((t (:foreground "#424242"))))
 '(font-lock-comment-symbol-face ((t (:foreground "#727272"))))
 '(font-lock-constant-face ((t (:foreground "#569cd6"))))
 '(font-lock-doc-face ((t (:foreground "#424242"))))
 '(font-lock-function-name-face ((t nil)))
 '(font-lock-keyword-face ((t (:foreground "#569cd6"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#9b9b9b"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#b5cea8"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b5cea8"))))
 '(font-lock-string-face ((t (:foreground "#d69d85"))))
 '(font-lock-type-face ((t (:foreground "#4ec9b0"))))
 '(font-lock-variable-name-face ((t nil)))
 '(font-lock-warning-face ((t (:foreground "#ff7400"))))
 '(fringe ((t nil)))
 '(git-commit-comment-action ((t (:background "purple" :foreground "black"))))
 '(git-commit-comment-branch-local ((t (:background "purple" :foreground "black"))))
 '(git-commit-comment-branch-remote ((t (:background "purple" :foreground "black"))))
 '(git-commit-comment-detached ((t (:background "purple" :foreground "black"))))
 '(git-commit-comment-file ((t (:background "purple" :foreground "black"))))
 '(git-commit-comment-heading ((t (:background "purple" :foreground "black"))))
 '(git-commit-known-pseudo-header ((t (:background "purple" :foreground "black"))))
 '(git-commit-nonempty-second-line ((t (:background "purple" :foreground "black"))))
 '(git-commit-note ((t (:background "purple" :foreground "black"))))
 '(git-commit-overlong-summary ((t (:background "purple" :foreground "black"))))
 '(git-commit-pseudo-header ((t (:background "purple" :foreground "black"))))
 '(git-commit-summary ((t (:background "purple" :foreground "black"))))
 '(glyphless-char ((t (:foreground "#00ffff"))))
 '(header-line ((t nil)))
 '(help-argument-name ((t (:slant italic))))
 '(hi-blue-b ((t (:foreground "blue1" :weight bold))))
 '(hi-yellow ((t (:background "yellow1" :foreground "black"))))
 '(highlight ((t (:background "#535353"))))
 '(hl-line ((t (:background "#535353"))))
 '(holiday ((t (:background "purple" :foreground "black"))))
 '(homoglyph ((t (:foreground "cyan"))))
 '(idle-highlight ((t (:background "#323232" :underline "#00cc00"))))
 '(info-header-node ((t (:background "purple" :foreground "black"))))
 '(info-header-xref ((t (:background "purple" :foreground "black"))))
 '(info-index-match ((t (:background "purple" :foreground "black"))))
 '(info-menu-header ((t (:background "purple" :foreground "black"))))
 '(info-menu-star ((t (:background "purple" :foreground "black"))))
 '(info-node ((t (:background "purple" :foreground "black"))))
 '(info-title-1 ((t (:background "purple" :foreground "black"))))
 '(info-title-2 ((t (:background "purple" :foreground "black"))))
 '(info-title-3 ((t (:background "purple" :foreground "black"))))
 '(info-title-4 ((t (:background "purple" :foreground "black"))))
 '(info-xref ((t (:background "purple" :foreground "black"))))
 '(info-xref-visited ((t (:background "purple" :foreground "black"))))
 '(isearch ((t (:background "#535353"))))
 '(isearch-fail ((t (:background "purple" :foreground "black"))))
 '(ivy-action ((t (:background "purple" :foreground "black"))))
 '(ivy-confirm-face ((t (:background "purple" :foreground "black"))))
 '(ivy-current-match ((t (:background "#535353"))))
 '(ivy-cursor ((t (:background "purple" :foreground "black"))))
 '(ivy-highlight-face ((t nil)))
 '(ivy-match-required-face ((t (:background "purple" :foreground "black"))))
 '(ivy-minibuffer-match-face-1 ((t (:underline "#BE8A2D"))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit ivy-minibuffer-match-face-1))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit ivy-minibuffer-match-face-1))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit ivy-minibuffer-match-face-1))))
 '(ivy-minibuffer-match-highlight ((t (:background "#535353"))))
 '(ivy-modified-buffer ((t (:foreground "#ff7400"))))
 '(ivy-modified-outside-buffer ((t (:foreground "#ff0000"))))
 '(ivy-prompt-match ((t (:background "purple" :foreground "black"))))
 '(ivy-remote ((t (:background "purple" :foreground "black"))))
 '(ivy-subdir ((t nil)))
 '(ivy-virtual ((t (:background "purple" :foreground "black"))))
 '(lazy-highlight ((t (:background "#535353"))))
 '(link ((t (:background "#d3d3d3" :foreground "#000000" :box (:line-width 1 :style released-button) :weight normal))))
 '(link-visited ((t (:background "purple" :foreground "black"))))
 '(linum ((t (:inherit nil :stipple nil :background "#131313" :foreground "#424242" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1.0 :width normal))))
 '(log-edit-header ((t (:background "purple" :foreground "black"))))
 '(log-edit-summary ((t (:background "purple" :foreground "black"))))
 '(log-edit-unknown-header ((t (:background "purple" :foreground "black"))))
 '(magit-bisect-bad ((t (:background "purple" :foreground "black"))))
 '(magit-bisect-good ((t (:background "purple" :foreground "black"))))
 '(magit-bisect-skip ((t (:background "purple" :foreground "black"))))
 '(magit-blame-date ((t (:background "purple" :foreground "black"))) t)
 '(magit-blame-dimmed ((t (:background "purple" :foreground "black"))))
 '(magit-blame-hash ((t (:background "purple" :foreground "black"))) t)
 '(magit-blame-heading ((t (:background "purple" :foreground "black"))))
 '(magit-blame-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-blame-margin ((t (:background "purple" :foreground "black"))))
 '(magit-blame-name ((t (:background "purple" :foreground "black"))) t)
 '(magit-blame-summary ((t (:background "purple" :foreground "black"))) t)
 '(magit-branch-current ((t (:background "purple" :foreground "black"))))
 '(magit-branch-local ((t (:background "purple" :foreground "black"))))
 '(magit-branch-remote ((t (:background "purple" :foreground "black"))))
 '(magit-branch-remote-head ((t (:background "purple" :foreground "black"))))
 '(magit-cherry-equivalent ((t (:background "purple" :foreground "black"))))
 '(magit-cherry-unmatched ((t (:background "purple" :foreground "black"))))
 '(magit-diff-added ((t (:background "purple" :foreground "black"))))
 '(magit-diff-added-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-base ((t (:background "purple" :foreground "black"))))
 '(magit-diff-base-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-conflict-heading ((t (:background "purple" :foreground "black"))))
 '(magit-diff-context ((t (:background "purple" :foreground "black"))))
 '(magit-diff-context-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-file-heading ((t (:background "purple" :foreground "black"))))
 '(magit-diff-file-heading-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-file-heading-selection ((t (:background "purple" :foreground "black"))))
 '(magit-diff-hunk-heading ((t (:background "purple" :foreground "black"))))
 '(magit-diff-hunk-heading-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-hunk-heading-selection ((t (:background "purple" :foreground "black"))))
 '(magit-diff-hunk-region ((t (:background "purple" :foreground "black"))))
 '(magit-diff-lines-boundary ((t (:background "purple" :foreground "black"))))
 '(magit-diff-lines-heading ((t (:background "purple" :foreground "black"))))
 '(magit-diff-our ((t (:background "purple" :foreground "black"))))
 '(magit-diff-our-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-removed ((t (:background "purple" :foreground "black"))))
 '(magit-diff-removed-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-their ((t (:background "purple" :foreground "black"))))
 '(magit-diff-their-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-diff-whitespace-warning ((t (:background "purple" :foreground "black"))))
 '(magit-diffstat-added ((t (:background "purple" :foreground "black"))))
 '(magit-diffstat-removed ((t (:background "purple" :foreground "black"))))
 '(magit-dimmed ((t (:background "purple" :foreground "black"))))
 '(magit-filename ((t (:background "purple" :foreground "black"))))
 '(magit-hash ((t (:background "purple" :foreground "black"))))
 '(magit-head ((t (:background "purple" :foreground "black"))))
 '(magit-header-line ((t (:background "purple" :foreground "black"))))
 '(magit-header-line-key ((t (:background "purple" :foreground "black"))))
 '(magit-header-line-log-select ((t (:background "purple" :foreground "black"))))
 '(magit-keyword ((t (:background "purple" :foreground "black"))))
 '(magit-log-author ((t (:background "purple" :foreground "black"))))
 '(magit-log-date ((t (:background "purple" :foreground "black"))))
 '(magit-log-graph ((t (:background "purple" :foreground "black"))))
 '(magit-mode-line-process ((t (:background "purple" :foreground "black"))))
 '(magit-mode-line-process-error ((t (:background "purple" :foreground "black"))))
 '(magit-popup-argument ((t (:background "purple" :foreground "black"))))
 '(magit-popup-disabled-argument ((t (:background "purple" :foreground "black"))))
 '(magit-popup-heading ((t (:background "purple" :foreground "black"))))
 '(magit-popup-key ((t (:background "purple" :foreground "black"))))
 '(magit-popup-option-value ((t (:background "purple" :foreground "black"))))
 '(magit-process-ng ((t (:background "purple" :foreground "black"))))
 '(magit-process-ok ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-amend ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-checkout ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-cherry-pick ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-commit ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-merge ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-other ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-rebase ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-remote ((t (:background "purple" :foreground "black"))))
 '(magit-reflog-reset ((t (:background "purple" :foreground "black"))))
 '(magit-refname ((t (:background "purple" :foreground "black"))))
 '(magit-refname-stash ((t (:background "purple" :foreground "black"))))
 '(magit-refname-wip ((t (:background "purple" :foreground "black"))))
 '(magit-section-heading ((t (:background "purple" :foreground "black"))))
 '(magit-section-heading-selection ((t (:background "purple" :foreground "black"))))
 '(magit-section-highlight ((t (:background "purple" :foreground "black"))))
 '(magit-section-secondary-heading ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-done ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-drop ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-exec ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-head ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-onto ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-part ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-pick ((t (:background "purple" :foreground "black"))))
 '(magit-sequence-stop ((t (:background "purple" :foreground "black"))))
 '(magit-signature-bad ((t (:background "purple" :foreground "black"))))
 '(magit-signature-error ((t (:background "purple" :foreground "black"))))
 '(magit-signature-expired ((t (:background "purple" :foreground "black"))))
 '(magit-signature-expired-key ((t (:background "purple" :foreground "black"))))
 '(magit-signature-good ((t (:background "purple" :foreground "black"))))
 '(magit-signature-revoked ((t (:background "purple" :foreground "black"))))
 '(magit-signature-untrusted ((t (:background "purple" :foreground "black"))))
 '(magit-tag ((t (:background "purple" :foreground "black"))))
 '(makefile-makepp-perl ((t (:background "purple" :foreground "black"))))
 '(makefile-shell ((t nil)) t)
 '(makefile-space ((t nil)))
 '(makefile-targets ((t (:foreground "#569cd6"))))
 '(markdown-blockquote-face ((t (:background "purple" :foreground "black"))))
 '(markdown-bold-face ((t (:background "purple" :foreground "black"))))
 '(markdown-code-face ((t nil)))
 '(markdown-comment-face ((t (:background "purple" :foreground "black"))))
 '(markdown-footnote-marker-face ((t (:background "purple" :foreground "black"))))
 '(markdown-footnote-text-face ((t (:background "purple" :foreground "black"))))
 '(markdown-gfm-checkbox-face ((t (:background "purple" :foreground "black"))))
 '(markdown-header-delimiter-face ((t (:background "purple" :foreground "black"))))
 '(markdown-header-face ((t (:background "purple" :foreground "black"))))
 '(markdown-header-face-1 ((t (:background "purple" :foreground "black"))))
 '(markdown-header-face-2 ((t (:background "purple" :foreground "black"))))
 '(markdown-header-face-3 ((t (:background "purple" :foreground "black"))))
 '(markdown-header-face-4 ((t (:background "purple" :foreground "black"))))
 '(markdown-header-face-5 ((t (:background "purple" :foreground "black"))))
 '(markdown-header-face-6 ((t (:background "purple" :foreground "black"))))
 '(markdown-header-rule-face ((t (:background "purple" :foreground "black"))))
 '(markdown-highlight-face ((t (:background "purple" :foreground "black"))))
 '(markdown-hr-face ((t (:background "purple" :foreground "black"))))
 '(markdown-inline-code-face ((t (:inherit markdown-code-face font-lock-constant-face t))))
 '(markdown-italic-face ((t (:background "purple" :foreground "black"))))
 '(markdown-language-info-face ((t (:background "purple" :foreground "black"))))
 '(markdown-language-keyword-face ((t (:background "purple" :foreground "black"))))
 '(markdown-line-break-face ((t (:background "purple" :foreground "black"))))
 '(markdown-link-face ((t (:background "purple" :foreground "black"))))
 '(markdown-link-title-face ((t (:background "purple" :foreground "black"))))
 '(markdown-list-face ((t (:background "purple" :foreground "black"))))
 '(markdown-markup-face ((t (:background "purple" :foreground "black"))))
 '(markdown-math-face ((t (:background "purple" :foreground "black"))))
 '(markdown-metadata-key-face ((t (:background "purple" :foreground "black"))))
 '(markdown-metadata-value-face ((t (:background "purple" :foreground "black"))))
 '(markdown-missing-link-face ((t (:background "purple" :foreground "black"))))
 '(markdown-plain-url-face ((t (:background "purple" :foreground "black"))))
 '(markdown-pre-face ((t (:background "purple" :foreground "black"))))
 '(markdown-reference-face ((t (:background "purple" :foreground "black"))))
 '(markdown-strike-through-face ((t (:background "purple" :foreground "black"))))
 '(markdown-url-face ((t (:background "purple" :foreground "black"))))
 '(match ((t (:background "#323232"))))
 '(menu ((t (:background "purple" :foreground "black"))))
 '(message-cited-text ((t (:background "purple" :foreground "black"))))
 '(message-header-cc ((t (:background "purple" :foreground "black"))))
 '(message-header-name ((t (:background "purple" :foreground "black"))))
 '(message-header-newsgroups ((t (:background "purple" :foreground "black"))))
 '(message-header-other ((t (:background "purple" :foreground "black"))))
 '(message-header-subject ((t (:background "purple" :foreground "black"))))
 '(message-header-to ((t (:background "purple" :foreground "black"))))
 '(message-header-xheader ((t (:background "purple" :foreground "black"))))
 '(message-mml ((t (:background "purple" :foreground "black"))))
 '(message-separator ((t (:background "purple" :foreground "black"))))
 '(minibuffer-prompt ((t nil)))
 '(mm-command-output ((t (:background "purple" :foreground "black"))))
 '(mode-line ((t (:background "#e6e6e6" :foreground "#000000"))))
 '(mode-line-emphasis ((t (:background "#535353"))))
 '(mode-line-highlight ((t (:background "#535353"))))
 '(mode-line-inactive ((t (:background "#323232" :foreground "#dcdcdc"))))
 '(mouse ((t nil)))
 '(next-error ((t (:background "#535353"))))
 '(nobreak-space ((t nil)))
 '(nxml-attribute-colon ((t (:background "purple" :foreground "black"))))
 '(nxml-attribute-local-name ((t (:background "purple" :foreground "black"))))
 '(nxml-attribute-prefix ((t (:background "purple" :foreground "black"))))
 '(nxml-attribute-value ((t (:background "purple" :foreground "black"))))
 '(nxml-attribute-value-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-cdata-section-CDATA ((t (:background "purple" :foreground "black"))))
 '(nxml-cdata-section-content ((t (:background "purple" :foreground "black"))))
 '(nxml-cdata-section-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-char-ref-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-char-ref-number ((t (:background "purple" :foreground "black"))))
 '(nxml-comment-content ((t (:background "purple" :foreground "black"))))
 '(nxml-comment-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-delimited-data ((t (:background "purple" :foreground "black"))))
 '(nxml-delimiter ((t (:background "purple" :foreground "black"))) t)
 '(nxml-element-colon ((t (:background "purple" :foreground "black"))) t)
 '(nxml-element-local-name ((t (:background "purple" :foreground "black"))))
 '(nxml-element-prefix ((t (:background "purple" :foreground "black"))))
 '(nxml-entity-ref-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-entity-ref-name ((t (:background "purple" :foreground "black"))))
 '(nxml-glyph ((t (:background "purple" :foreground "black"))))
 '(nxml-hash ((t (:background "purple" :foreground "black"))))
 '(nxml-heading ((t (:background "purple" :foreground "black"))))
 '(nxml-markup-declaration-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-name ((t (:background "purple" :foreground "black"))))
 '(nxml-namespace-attribute-colon ((t (:background "purple" :foreground "black"))))
 '(nxml-namespace-attribute-prefix ((t (:background "purple" :foreground "black"))))
 '(nxml-namespace-attribute-value ((t (:background "purple" :foreground "black"))))
 '(nxml-namespace-attribute-value-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-namespace-attribute-xmlns ((t (:background "purple" :foreground "black"))))
 '(nxml-outline-active-indicator ((t (:background "purple" :foreground "black"))))
 '(nxml-outline-ellipsis ((t (:background "purple" :foreground "black"))))
 '(nxml-outline-indicator ((t (:background "purple" :foreground "black"))))
 '(nxml-processing-instruction-content ((t (:background "purple" :foreground "black"))))
 '(nxml-processing-instruction-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-processing-instruction-target ((t (:background "purple" :foreground "black"))))
 '(nxml-prolog-keyword ((t (:background "purple" :foreground "black"))))
 '(nxml-prolog-literal-content ((t (:background "purple" :foreground "black"))))
 '(nxml-prolog-literal-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-ref ((t (:background "purple" :foreground "black"))))
 '(nxml-tag-delimiter ((t (:background "purple" :foreground "black"))))
 '(nxml-tag-slash ((t (:background "purple" :foreground "black"))))
 '(nxml-text ((t (:background "purple" :foreground "black"))) t)
 '(org-agenda-calendar-event ((t (:background "purple" :foreground "black"))))
 '(org-agenda-calendar-sexp ((t (:background "purple" :foreground "black"))))
 '(org-agenda-clocking ((t (:background "purple" :foreground "black"))) t)
 '(org-agenda-column-dateline ((t (:background "purple" :foreground "black"))))
 '(org-agenda-current-time ((t (:background "purple" :foreground "black"))) t)
 '(org-agenda-date ((t (:background "purple" :foreground "black"))) t)
 '(org-agenda-date-today ((t (:background "purple" :foreground "black"))) t)
 '(org-agenda-date-weekend ((t (:background "purple" :foreground "black"))) t)
 '(org-agenda-diary ((t (:background "purple" :foreground "black"))))
 '(org-agenda-dimmed-todo-face ((t (:background "purple" :foreground "black"))))
 '(org-agenda-done ((t (:background "purple" :foreground "black"))))
 '(org-agenda-filter-category ((t (:background "purple" :foreground "black"))))
 '(org-agenda-filter-regexp ((t (:background "purple" :foreground "black"))))
 '(org-agenda-filter-tags ((t (:background "purple" :foreground "black"))))
 '(org-agenda-restriction-lock ((t (:background "purple" :foreground "black"))))
 '(org-agenda-structure ((t (:background "purple" :foreground "black"))))
 '(org-archived ((t (:background "purple" :foreground "black"))))
 '(org-block ((t (:background "purple" :foreground "black"))))
 '(org-block-background ((t (:background "purple" :foreground "black"))))
 '(org-block-begin-line ((t (:background "purple" :foreground "black"))) t)
 '(org-block-end-line ((t (:background "purple" :foreground "black"))) t)
 '(org-checkbox ((t (:background "purple" :foreground "black"))))
 '(org-checkbox-statistics-done ((t (:background "purple" :foreground "black"))) t)
 '(org-checkbox-statistics-todo ((t (:background "purple" :foreground "black"))) t)
 '(org-clock-overlay ((t (:background "purple" :foreground "black"))))
 '(org-code ((t (:background "purple" :foreground "black"))))
 '(org-column ((t (:background "purple" :foreground "black"))))
 '(org-column-title ((t (:background "purple" :foreground "black"))))
 '(org-date ((t (:background "purple" :foreground "black"))))
 '(org-date-selected ((t (:background "purple" :foreground "black"))))
 '(org-default ((t (:background "purple" :foreground "black"))))
 '(org-document-info ((t (:background "purple" :foreground "black"))))
 '(org-document-info-keyword ((t (:background "purple" :foreground "black"))))
 '(org-document-title ((t (:background "purple" :foreground "black"))))
 '(org-done ((t (:background "purple" :foreground "black"))))
 '(org-drawer ((t (:background "purple" :foreground "black"))))
 '(org-ellipsis ((t (:background "purple" :foreground "black"))))
 '(org-footnote ((t (:background "purple" :foreground "black"))))
 '(org-formula ((t (:background "purple" :foreground "black"))))
 '(org-headline-done ((t (:background "purple" :foreground "black"))))
 '(org-hide ((t (:background "purple" :foreground "black"))))
 '(org-latex-and-related ((t (:background "purple" :foreground "black"))))
 '(org-level-1 ((t (:background "purple" :foreground "black"))))
 '(org-level-2 ((t (:background "purple" :foreground "black"))))
 '(org-level-3 ((t (:background "purple" :foreground "black"))))
 '(org-level-4 ((t (:background "purple" :foreground "black"))))
 '(org-level-5 ((t (:background "purple" :foreground "black"))))
 '(org-level-6 ((t (:background "purple" :foreground "black"))))
 '(org-level-7 ((t (:background "purple" :foreground "black"))))
 '(org-level-8 ((t (:background "purple" :foreground "black"))))
 '(org-link ((t (:background "purple" :foreground "black"))))
 '(org-list-dt ((t (:background "purple" :foreground "black"))))
 '(org-macro ((t (:background "purple" :foreground "black"))))
 '(org-meta-line ((t (:background "purple" :foreground "black"))))
 '(org-mode-line-clock ((t (:background "purple" :foreground "black"))) t)
 '(org-mode-line-clock-overrun ((t (:background "purple" :foreground "black"))) t)
 '(org-priority ((t (:background "purple" :foreground "black"))))
 '(org-property-value ((t (:background "purple" :foreground "black"))) t)
 '(org-quote ((t (:background "purple" :foreground "black"))) t)
 '(org-scheduled ((t (:background "purple" :foreground "black"))))
 '(org-scheduled-previously ((t (:background "purple" :foreground "black"))))
 '(org-scheduled-today ((t (:background "purple" :foreground "black"))))
 '(org-sexp-date ((t (:background "purple" :foreground "black"))))
 '(org-special-keyword ((t (:background "purple" :foreground "black"))))
 '(org-table ((t (:background "purple" :foreground "black"))))
 '(org-tag ((t (:background "purple" :foreground "black"))))
 '(org-tag-group ((t (:background "purple" :foreground "black"))))
 '(org-target ((t (:background "purple" :foreground "black"))))
 '(org-time-grid ((t (:background "purple" :foreground "black"))))
 '(org-todo ((t (:background "purple" :foreground "black"))))
 '(org-upcoming-deadline ((t (:background "purple" :foreground "black"))))
 '(org-verbatim ((t (:background "purple" :foreground "black"))))
 '(org-verse ((t (:background "purple" :foreground "black"))) t)
 '(org-warning ((t (:background "purple" :foreground "black"))))
 '(outline-1 ((t (:background "purple" :foreground "black"))))
 '(outline-2 ((t (:background "purple" :foreground "black"))))
 '(outline-3 ((t (:background "purple" :foreground "black"))))
 '(outline-4 ((t (:background "purple" :foreground "black"))))
 '(outline-5 ((t (:background "purple" :foreground "black"))))
 '(outline-6 ((t (:background "purple" :foreground "black"))))
 '(outline-7 ((t (:background "purple" :foreground "black"))))
 '(outline-8 ((t (:background "purple" :foreground "black"))))
 '(package-description ((t nil)))
 '(package-help-section-name ((t (:background "purple" :foreground "black"))))
 '(package-status-avail-obso ((t (:background "purple" :foreground "black"))))
 '(package-status-available ((t (:background "purple" :foreground "black"))))
 '(package-status-built-in ((t (:background "purple" :foreground "black"))))
 '(package-status-dependency ((t (:background "purple" :foreground "black"))))
 '(package-status-disabled ((t (:background "purple" :foreground "black"))))
 '(package-status-external ((t (:background "purple" :foreground "black"))))
 '(package-status-held ((t (:background "purple" :foreground "black"))))
 '(package-status-incompat ((t (:background "purple" :foreground "black"))))
 '(package-status-installed ((t (:background "purple" :foreground "black"))))
 '(package-status-new ((t nil)))
 '(package-status-unsigned ((t (:background "purple" :foreground "black"))))
 '(prolog-builtin-face ((t (:background "purple" :foreground "black"))))
 '(prolog-exception-face ((t (:background "purple" :foreground "black"))))
 '(prolog-exit-face ((t (:background "purple" :foreground "black"))))
 '(prolog-redo-face ((t (:background "purple" :foreground "black"))))
 '(prolog-warning-face ((t (:background "purple" :foreground "black"))))
 '(query-replace ((t (:background "#535353"))))
 '(rcirc-my-nick ((t (:foreground "#569cd6"))))
 '(rcirc-nick-in-message ((t (:foreground "#569cd6"))))
 '(rcirc-nick-in-message-full-line ((t nil)))
 '(rcirc-prompt ((t nil)))
 '(rcirc-server ((t (:foreground "#424242"))))
 '(rcirc-server-prefix ((t (:foreground "#424242"))))
 '(reb-match-0 ((t (:background "purple" :foreground "black"))))
 '(reb-match-1 ((t (:background "purple" :foreground "black"))))
 '(reb-match-2 ((t (:background "purple" :foreground "black"))))
 '(reb-match-3 ((t (:background "purple" :foreground "black"))))
 '(region ((t (:background "#535353"))))
 '(rng-error ((t (:background "purple" :foreground "black"))))
 '(scroll-bar ((t (:background "purple" :foreground "black"))))
 '(secondary-selection ((t (:background "purple" :foreground "black"))))
 '(sgml-namespace ((t (:background "purple" :foreground "black"))))
 '(sh-escaped-newline ((t (:foreground "#d69d85"))))
 '(sh-heredoc ((t (:background "purple" :foreground "black"))))
 '(sh-quoted-exec ((t (:foreground "#00cc00"))))
 '(shadow ((t (:foreground "#acacac"))))
 '(show-paren-match ((t (:background "#898888"))))
 '(show-paren-mismatch ((t (:foreground "#ff0000"))))
 '(smerge-base ((t (:background "purple" :foreground "black"))))
 '(smerge-lower ((t (:background "#00cc00" :foreground "#000000"))))
 '(smerge-markers ((t (:background "#222222"))))
 '(smerge-mine ((t (:background "purple" :foreground "black"))) t)
 '(smerge-other ((t (:background "purple" :foreground "black"))) t)
 '(smerge-refined-added ((t (:background "#bdffbd" :foreground "#000000"))))
 '(smerge-refined-changed ((t (:background "#ff8a8a" :foreground "#000000"))))
 '(smerge-refined-removed ((t (:background "#ff8a8a" :foreground "#000000"))))
 '(smerge-upper ((t (:background "#ff0000" :foreground "#000000"))))
 '(speedbar-button-face ((t nil)))
 '(speedbar-directory-face ((t (:foreground "#569cd6"))))
 '(speedbar-file-face ((t nil)))
 '(speedbar-highlight-face ((t (:background "#323232"))))
 '(speedbar-selected-face ((t (:underline t))))
 '(speedbar-separator-face ((t (:background "purple" :foreground "black"))))
 '(speedbar-tag-face ((t nil)))
 '(strokes-char ((t (:background "purple" :foreground "black"))))
 '(subscript ((t (:background "purple" :foreground "black"))))
 '(success ((t (:foreground "#00cc00" :weight bold))))
 '(superscript ((t (:background "purple" :foreground "black"))))
 '(swiper-background-match-face-1 ((t (:background "#BE8A2D" :foreground "#192033"))))
 '(swiper-background-match-face-2 ((t (:inherit swiper-background-match-face-1))))
 '(swiper-background-match-face-3 ((t (:inherit swiper-background-match-face-1))))
 '(swiper-background-match-face-4 ((t (:inherit swiper-background-match-face-1))))
 '(swiper-line-face ((t (:background "#535353"))))
 '(swiper-match-face-1 ((t (:background "#BE8A2D"))))
 '(swiper-match-face-2 ((t (:background "#BE8A2D"))))
 '(swiper-match-face-3 ((t (:background "#BE8A2D"))))
 '(swiper-match-face-4 ((t (:background "#BE8A2D"))))
 '(term ((t (:background "purple" :foreground "black"))))
 '(term-bold ((t (:background "purple" :foreground "black"))))
 '(term-color-black ((t (:background "purple" :foreground "black"))))
 '(term-color-blue ((t (:background "purple" :foreground "black"))))
 '(term-color-cyan ((t (:background "purple" :foreground "black"))))
 '(term-color-green ((t (:background "purple" :foreground "black"))))
 '(term-color-magenta ((t (:background "purple" :foreground "black"))))
 '(term-color-red ((t (:background "purple" :foreground "black"))))
 '(term-color-white ((t (:background "purple" :foreground "black"))))
 '(term-color-yellow ((t (:background "purple" :foreground "black"))))
 '(term-underline ((t (:background "purple" :foreground "black"))))
 '(tex-math ((t (:background "purple" :foreground "black"))))
 '(tex-verbatim ((t (:background "purple" :foreground "black"))))
 '(tmm-inactive ((t (:background "purple" :foreground "black"))))
 '(tool-bar ((t (:background "purple" :foreground "black"))))
 '(tooltip ((t (:background "#e6e6e6" :foreground "#000000"))))
 '(trailing-whitespace ((t (:background "#ff0000"))))
 '(tty-menu-disabled-face ((t (:background "purple" :foreground "black"))))
 '(tty-menu-enabled-face ((t (:background "purple" :foreground "black"))))
 '(tty-menu-selected-face ((t (:background "purple" :foreground "black"))))
 '(underline ((t (:underline "#e6e6e6"))))
 '(variable-pitch ((t (:background "purple" :foreground "black"))))
 '(vc-conflict-state ((t (:weight bold))))
 '(vc-edited-state ((t (:background "#e6e6e6" :foreground "#000000"))))
 '(vc-locally-added-state ((t (:background "purple" :foreground "black"))))
 '(vc-locked-state ((t (:background "purple" :foreground "black"))))
 '(vc-missing-state ((t (:background "purple" :foreground "black"))))
 '(vc-needs-update-state ((t (:background "purple" :foreground "black"))))
 '(vc-removed-state ((t (:background "purple" :foreground "black"))))
 '(vc-state-base ((t (:background "purple" :foreground "black"))))
 '(vc-up-to-date-state ((t (:inherit greenvc-state-base))))
 '(vertical-border ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-attribute-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-directive-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-enumvalue-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-function-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-generic-/constant-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-prompt-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-reserved-words-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-translate-off-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-type-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-font-lock-variable-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-architecture-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-architecture-selected-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-configuration-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-configuration-selected-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-entity-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-entity-selected-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-instantiation-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-instantiation-selected-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-library-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-package-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-package-selected-face ((t (:background "purple" :foreground "black"))))
 '(vhdl-speedbar-subprogram-face ((t (:background "purple" :foreground "black"))))
 '(warning ((t (:foreground "#ff7400"))))
 '(widget-button ((t (:background "purple" :foreground "black"))))
 '(widget-button-pressed ((t (:background "purple" :foreground "black"))))
 '(widget-documentation ((t (:background "purple" :foreground "black"))))
 '(widget-field ((t (:background "#d3d3d3" :foreground "#000000"))))
 '(widget-inactive ((t (:background "purple" :foreground "black"))))
 '(widget-single-line-field ((t (:background "purple" :foreground "black"))))
 '(window-divider ((t (:background "purple" :foreground "black"))))
 '(window-divider-first-pixel ((t (:background "purple" :foreground "black"))))
 '(window-divider-last-pixel ((t (:background "purple" :foreground "black"))))
 '(wolfram-pod-title ((t (:foreground "#d6c556"))))
 '(wolfram-query ((t (:foreground "#569cd6"))))
 '(xref-file-header ((t (:foreground "#569cd6"))))
 '(xref-match ((t (:background "#BE8A2D" :foreground "#192033"))))
 '(yas--field-debug-face ((t (:background "#898888"))) t)
 '(yas-field-highlight-face ((t (:background "#535353")))))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (company-lsp lsp-mode rmsbolt ivy-rtags flycheck-rtags company-rtags rtags cmake-ide flycheck yasnippet sr-speedbar modern-cpp-font-lock gnuplot-mode counsel company)))
 '(safe-local-variable-values (quote ((flycheck-disabled-checkers emacs-lisp-checkdoc)))))
