(defalias 'ff 'find-file)
(setq auto-save-file-name-transforms `(("*" ,(concat jd:path-prefix "file-backups/") t)))
(setq backup-by-copying t)
(setq backup-directory-alist `(("*" . ,(concat jd:path-prefix "file-backups/"))))
(setq large-file-warning-threshold nil)
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.ipp\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.\\(gp\\|gnuplot\\)$" . gnuplot-mode))
(add-to-list 'auto-mode-alist '("[Mm]akefile\\'" . makefile-mode))

(provide 'jd:files-st.el)
