;; Customization variables.
(defvar after-save-hook)
(defvar auto-mode-case-fold)
(defvar auto-save-default)
(defvar auto-save-visited-interval)
(defvar automount-dir-prefix)
(defvar backup-by-copying-when-linked)
(defvar backup-by-copying-when-mismatch)
(defvar backup-by-copying-when-privileged-mismatch)
(defvar before-save-hook)
(defvar break-hardlink-on-save)
(defvar buffer-offer-save)
(defvar change-major-mode-with-file-name)
(defvar confirm-kill-emacs)
(defvar confirm-kill-processes)
(defvar confirm-nonexistent-file-or-buffer)
(defvar delete-old-versions)
(defvar directory-abbrev-alist)
(defvar directory-free-space-args)
(defvar directory-free-space-program)
(defvar dired-kept-versions)
(defvar enable-local-eval)
(defvar enable-local-variables)
(defvar enable-remote-dir-locals)
(defvar file-name-at-point-functions)
(defvar file-precious-flag)
(defvar find-directory-functions)
(defvar find-file-existing-other-name)
(defvar find-file-hook)
(defvar find-file-run-dired)
(defvar find-file-suppress-same-file-warnings)
(defvar find-file-visit-truename)
(defvar find-file-wildcards)
(defvar kept-new-versions)
(defvar kept-old-versions)
(defvar kill-emacs-query-functions)
(defvar large-file-warning-threshold)
(defvar list-directory-brief-switches)
(defvar list-directory-verbose-switches)
(defvar make-backup-file-name-function)
(defvar make-backup-files)
(defvar mode-require-final-newline)
(defvar mounted-file-systems)
(defvar out-of-memory-warning-percentage)
(defvar remote-file-name-inhibit-cache)
(defvar require-final-newline)
(defvar revert-without-query)
(defvar safe-local-eval-forms)
(defvar safe-local-variable-values)
(defvar save-abbrevs)
(defvar save-some-buffers-default-predicate)
(defvar small-temporary-file-directory)
(defvar trash-directory)
(defvar user-emacs-directory-warning)
(defvar version-control)
(defvar view-read-only)

(setq-default auto-save-file-name-transforms
              `((".*" ,(concat jd:path-prefix "autosaves/") t)))
(setq-default backup-by-copying t)
(setq-default backup-directory-alist
              `((".*" . ,(concat jd:path-prefix "backups/"))))
(setq-default delete-auto-save-files nil)
(setq-default remote-shell-program
              (purecopy "ssh"))

(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.hpp\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.c\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.cpp\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.ipp\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.gp\\'" . gnuplot-mode))
(add-to-list 'auto-mode-alist '("[Mm]akefile\\'" . makefile-mode))

(provide 'jd:files-st)
