;; Faces.
(defvar isearch)
(defvar isearch-fail)
(defvar lazy-highlight)

;; Customization variables.
(defvar isearch-allow-prefix)
(defvar isearch-allow-scroll)
(defvar isearch-hide-immediately)
(defvar isearch-lazy-highlight)
(defvar isearch-resume-in-command-history)
(defvar lazy-highlight-cleanup)
(defvar lazy-highlight-initial-delay)
(defvar lazy-highlight-interval)
(defvar lazy-highlight-max-at-a-time)
(defvar regexp-search-ring-max)
(defvar search-default-mode)
(defvar search-exit-option)
(defvar search-highlight)
(defvar search-invisible)
(defvar search-nonincremental-instead)
(defvar search-ring-max)
(defvar search-ring-update)
(defvar search-slow-speed)
(defvar search-slow-window-lines)
(defvar search-upper-case)
(defvar search-whitespace-regexp)

(jd:provide-feature jd:isearch-st)
