(jd:load-feature jd:buffer-movement jd:global-prefix)
(jd:load-feature jd:construct-folder jd:global-prefix)
(jd:load-feature jd:cpp-print jd:global-prefix)
(jd:load-feature jd:cursor-movement jd:global-prefix)
(jd:load-feature jd:describe jd:global-prefix)
(jd:load-feature jd:establish-theme jd:global-prefix)
(jd:load-feature jd:global-definitions jd:global-prefix)
(jd:load-feature jd:global-key-translations jd:global-prefix)
(jd:load-feature jd:global-keybindings jd:global-prefix)
(jd:load-feature jd:mode-line-format jd:global-prefix)
(jd:load-feature jd:incredible jd:global-prefix)

(jd:provide-feature jd:global-config)
