(jd:load-feature jd:buffer-movement (concat jd:global-prefix "/"))
(jd:load-feature jd:construct-folder (concat jd:global-prefix "/"))
(jd:load-feature jd:cpp-print (concat jd:global-prefix "/"))
(jd:load-feature jd:cursor-movement (concat jd:global-prefix "/"))
(jd:load-feature jd:describe (concat jd:global-prefix "/"))
(jd:load-feature jd:establish-theme (concat jd:global-prefix "/"))
(jd:load-feature jd:global-definitions (concat jd:global-prefix "/"))
(jd:load-feature jd:global-key-translations (concat jd:global-prefix "/"))
(jd:load-feature jd:global-keybindings (concat jd:global-prefix "/"))
(jd:load-feature jd:mode-line-format (concat jd:global-prefix "/"))
(jd:load-feature jd:incredible (concat jd:global-prefix "/"))

(jd:provide-feature jd:global-config)
