(define-prefix-command 'jd:c-h-prefix-key)
(define-prefix-command 'jd:c-x-prefix-key)

(define-key global-map (kbd "<C-a>")     'mark-whole-buffer)
;; (define-key global-map (kbd "<C-b>")  ')
;; (define-key global-map (kbd "<C-c>")  ')
;; (define-key global-map (kbd "<C-d>")  ')
;; (define-key global-map (kbd "<C-e>")  ')
(define-key global-map (kbd "<C-f>")     'swiper)
(define-key global-map (kbd "<C-g>")     'jd:incredibly-smart-keyboard-quit)
(define-key global-map (kbd "<C-h>")     'jd:c-h-prefix-key)
(define-key global-map (kbd "<C-i>")     'jd:scroll-up)
(define-key global-map (kbd "<C-j>")     'backward-sexp)
(define-key global-map (kbd "<C-k>")     'jd:scroll-down)
(define-key global-map (kbd "<C-l>")     'forward-sexp)
;; (define-key global-map (kbd "<C-m>")  ')
(define-key global-map (kbd "<C-n>")     'jd:transpose-line-down)
(define-key global-map (kbd "<C-o>")     'end-of-buffer)
;; (define-key global-map (kbd "<C-p>")  ')
(define-key global-map (kbd "<C-q>")     'quoted-insert)
;; (define-key global-map (kbd "<C-r>")  ')
(define-key global-map (kbd "<C-s>")     'save-buffer)
(define-key global-map (kbd "<C-t>")     'split-window-right)
(define-key global-map (kbd "<C-u>")     'beginning-of-buffer)
;; (define-key global-map (kbd "<C-v>")  ')
(define-key global-map (kbd "<C-w>")     'delete-window)
(define-key global-map (kbd "<C-x>")     'jd:c-x-prefix-key)
;; (define-key global-map (kbd "<C-y>")  ')
;; (define-key global-map (kbd "<C-z>")  ')
;; (define-key global-map (kbd "<C-[>")  ')
;; (define-key global-map (kbd "<C-]>")  ')
;; (define-key global-map (kbd "<C-\\>") ')
;; (define-key global-map (kbd "<C-;>")  ')
;; (define-key global-map (kbd "<C-'>")  ')
;; (define-key global-map (kbd "<C-,>")  ')
;; (define-key global-map (kbd "<C-.>")  ')
(define-key global-map (kbd "<C-/>")     'comment-region)
;; (define-key global-map (kbd "<C-{>")  ')
;; (define-key global-map (kbd "<C-}>")  ')
;; (define-key global-map (kbd "<C-|>")  ')
;; (define-key global-map (kbd "<C-:>")  ')
;; (define-key global-map (kbd "<C-\">") ')
;; (define-key global-map (kbd "<C-<>")  ')
;; (define-key global-map (kbd "<C->>")  ')
(define-key global-map (kbd "<C-?>")     'uncomment-region)
;; (define-key global-map (kbd "<C-`>")  ')
(define-key global-map (kbd "<C-1>")     'jd:jump-to-register-1)
(define-key global-map (kbd "<C-2>")     'jd:jump-to-register-2)
(define-key global-map (kbd "<C-3>")     'jd:jump-to-register-3)
(define-key global-map (kbd "<C-4>")     'jd:jump-to-register-4)
(define-key global-map (kbd "<C-5>")     'jd:jump-to-register-5)
(define-key global-map (kbd "<C-6>")     'jd:jump-to-register-6)
(define-key global-map (kbd "<C-7>")     'jd:jump-to-register-7)
(define-key global-map (kbd "<C-8>")     'jd:jump-to-register-8)
(define-key global-map (kbd "<C-9>")     'jd:jump-to-register-9)
;; (define-key global-map (kbd "<C-0>")  ')
;; (define-key global-map (kbd "<C-->")  ')
(define-key global-map (kbd "<C-=>")     'universal-argument)
;; (define-key global-map (kbd "<C-~>")  ')
;; (define-key global-map (kbd "<C-!>")  ')
;; (define-key global-map (kbd "<C-@>")  ')
;; (define-key global-map (kbd "<C-#>")  ')
;; (define-key global-map (kbd "<C-$>")  ')
;; (define-key global-map (kbd "<C-%>")  ')
;; (define-key global-map (kbd "<C-^>")  ')
;; (define-key global-map (kbd "<C-&>")  ')
;; (define-key global-map (kbd "<C-*>")  ')
;; (define-key global-map (kbd "<C-(>")  ')
;; (define-key global-map (kbd "<C-)>")  ')
;; (define-key global-map (kbd "<C-_>")  ')
;; (define-key global-map (kbd "<C-+>")  ')

;; (define-key global-map (kbd "<C-S-a>")  ')
;; (define-key global-map (kbd "<C-S-b>")  ')
;; (define-key global-map (kbd "<C-S-c>")  ')
;; (define-key global-map (kbd "<C-S-d>")  ')
;; (define-key global-map (kbd "<C-S-e>")  ')
(define-key global-map (kbd "<C-S-f>")     'swiper-query-replace)
;; (define-key global-map (kbd "<C-S-g>")  ')
;; (define-key global-map (kbd "<C-S-h>")  ')
;; (define-key global-map (kbd "<C-S-i>")  ')
;; (define-key global-map (kbd "<C-S-j>")  ')
;; (define-key global-map (kbd "<C-S-k>")  ')
;; (define-key global-map (kbd "<C-S-l>")  ')
;; (define-key global-map (kbd "<C-S-m>")  ')
(define-key global-map (kbd "<C-S-n>")     'jd:transpose-line-up)
;; (define-key global-map (kbd "<C-S-o>")  ')
;; (define-key global-map (kbd "<C-S-p>")  ')
;; (define-key global-map (kbd "<C-S-q>")  ')
;; (define-key global-map (kbd "<C-S-r>")  ')
;; (define-key global-map (kbd "<C-S-s>")  ')
(define-key global-map (kbd "<C-S-t>")     'split-window-below)
;; (define-key global-map (kbd "<C-S-u>")  ')
;; (define-key global-map (kbd "<C-S-v>")  ')
;; (define-key global-map (kbd "<C-S-w>")  ')
;; (define-key global-map (kbd "<C-S-x>")  ')
;; (define-key global-map (kbd "<C-S-y>")  ')
;; (define-key global-map (kbd "<C-S-z>")  ')
;; (define-key global-map (kbd "<C-S-[>")  ')
;; (define-key global-map (kbd "<C-S-]>")  ')
;; (define-key global-map (kbd "<C-S-\\>") ')
;; (define-key global-map (kbd "<C-S-;>")  ')
;; (define-key global-map (kbd "<C-S-'>")  ')
;; (define-key global-map (kbd "<C-S-,>")  ')
;; (define-key global-map (kbd "<C-S-.>")  ')
;; (define-key global-map (kbd "<C-S-/>")  ')
;; (define-key global-map (kbd "<C-S-{>")  ')
;; (define-key global-map (kbd "<C-S-}>")  ')
;; (define-key global-map (kbd "<C-S-|>")  ')
;; (define-key global-map (kbd "<C-S-:>")  ')
;; (define-key global-map (kbd "<C-S-\">") ')
;; (define-key global-map (kbd "<C-S-<>")  ')
;; (define-key global-map (kbd "<C-S->>")  ')
;; (define-key global-map (kbd "<C-S-?>")  ')
;; (define-key global-map (kbd "<C-S-`>")  ')
;; (define-key global-map (kbd "<C-S-1>")  ')
;; (define-key global-map (kbd "<C-S-2>")  ')
;; (define-key global-map (kbd "<C-S-3>")  ')
;; (define-key global-map (kbd "<C-S-4>")  ')
;; (define-key global-map (kbd "<C-S-5>")  ')
;; (define-key global-map (kbd "<C-S-6>")  ')
;; (define-key global-map (kbd "<C-S-7>")  ')
;; (define-key global-map (kbd "<C-S-8>")  ')
;; (define-key global-map (kbd "<C-S-9>")  ')
;; (define-key global-map (kbd "<C-S-0>")  ')
;; (define-key global-map (kbd "<C-S-->")  ')
;; (define-key global-map (kbd "<C-S-=>")  ')
;; (define-key global-map (kbd "<C-S-~>")  ')
;; (define-key global-map (kbd "<C-S-!>")  ')
;; (define-key global-map (kbd "<C-S-@>")  ')
;; (define-key global-map (kbd "<C-S-#>")  ')
;; (define-key global-map (kbd "<C-S-$>")  ')
;; (define-key global-map (kbd "<C-S-%>")  ')
;; (define-key global-map (kbd "<C-S-^>")  ')
;; (define-key global-map (kbd "<C-S-&>")  ')
;; (define-key global-map (kbd "<C-S-*>")  ')
;; (define-key global-map (kbd "<C-S-(>")  ')
;; (define-key global-map (kbd "<C-S-)>")  ')
;; (define-key global-map (kbd "<C-S-_>")  ')
;; (define-key global-map (kbd "<C-S-+>")  ')

;; (define-key global-map (kbd "<M-a>")  ')
;; (define-key global-map (kbd "<M-b>")  ')
;; (define-key global-map (kbd "<M-c>")  ')
;; (define-key global-map (kbd "<M-d>")  ')
;; (define-key global-map (kbd "<M-e>")  ')
(define-key global-map (kbd "<M-f>")     'jd:counsel-find-file)
;; (define-key global-map (kbd "<M-g>")  ')
(define-key global-map (kbd "<M-h>")     'jd:xref-find-definitions)
(define-key global-map (kbd "<M-i>")     'previous-line)
(define-key global-map (kbd "<M-j>")     'backward-char)
(define-key global-map (kbd "<M-k>")     'next-line)
(define-key global-map (kbd "<M-l>")     'forward-char)
;; (define-key global-map (kbd "<M-m>")  ')
(define-key global-map (kbd "<M-n>")     'jd:transpose-char-right)
(define-key global-map (kbd "<M-o>")     'end-of-line)
;; (define-key global-map (kbd "<M-p>")  ')
;; (define-key global-map (kbd "<M-q>")  ')
;; (define-key global-map (kbd "<M-r>")  ')
;; (define-key global-map (kbd "<M-s>")  ')
;; (define-key global-map (kbd "<M-t>")  ')
(define-key global-map (kbd "<M-u>")     'back-to-indentation)
;; (define-key global-map (kbd "<M-v>")  ')
(define-key global-map (kbd "<M-w>")     'delete-other-windows)
(define-key global-map (kbd "<M-x>")     'counsel-M-x)
;; (define-key global-map (kbd "<M-y>")  ')
;; (define-key global-map (kbd "<M-z>")  ')
;; (define-key global-map (kbd "<M-[>")  ')
;; (define-key global-map (kbd "<M-]>")  ')
;; (define-key global-map (kbd "<M-\\>") ')
(define-key global-map (kbd "<M-;>")     'recenter)
;; (define-key global-map (kbd "<M-'>")  ')
;; (define-key global-map (kbd "<M-,>")  ')
;; (define-key global-map (kbd "<M-.>")  ')
(define-key global-map (kbd "<M-/>")     'jd:copy-and-comment-out)
;; (define-key global-map (kbd "<M-{>")  ')
;; (define-key global-map (kbd "<M-}>")  ')
;; (define-key global-map (kbd "<M-|>")  ')
;; (define-key global-map (kbd "<M-:>")  ')
;; (define-key global-map (kbd "<M-\">") ')
;; (define-key global-map (kbd "<M-<>")  ')
;; (define-key global-map (kbd "<M->>")  ')
;; (define-key global-map (kbd "<M-?>")  ')
;; (define-key global-map (kbd "<M-`>")  ')
;; (define-key global-map (kbd "<M-1>")  ')
;; (define-key global-map (kbd "<M-2>")  ')
;; (define-key global-map (kbd "<M-3>")  ')
;; (define-key global-map (kbd "<M-4>")  ')
;; (define-key global-map (kbd "<M-5>")  ')
;; (define-key global-map (kbd "<M-6>")  ')
;; (define-key global-map (kbd "<M-7>")  ')
;; (define-key global-map (kbd "<M-8>")  ')
;; (define-key global-map (kbd "<M-9>")  ')
;; (define-key global-map (kbd "<M-0>")  ')
;; (define-key global-map (kbd "<M-->")  ')
;; (define-key global-map (kbd "<M-=>")  ')
;; (define-key global-map (kbd "<M-~>")  ')
;; (define-key global-map (kbd "<M-!>")  ')
;; (define-key global-map (kbd "<M-@>")  ')
;; (define-key global-map (kbd "<M-#>")  ')
;; (define-key global-map (kbd "<M-$>")  ')
;; (define-key global-map (kbd "<M-%>")  ')
;; (define-key global-map (kbd "<M-^>")  ')
;; (define-key global-map (kbd "<M-&>")  ')
;; (define-key global-map (kbd "<M-*>")  ')
;; (define-key global-map (kbd "<M-(>")  ')
;; (define-key global-map (kbd "<M-)>")  ')
;; (define-key global-map (kbd "<M-_>")  ')
;; (define-key global-map (kbd "<M-+>")  ')

;; (define-key global-map (kbd "<M-S-a>")  ')
;; (define-key global-map (kbd "<M-S-b>")  ')
;; (define-key global-map (kbd "<M-S-c>")  ')
;; (define-key global-map (kbd "<M-S-d>")  ')
;; (define-key global-map (kbd "<M-S-e>")  ')
;; (define-key global-map (kbd "<M-S-f>")  ')
;; (define-key global-map (kbd "<M-S-g>")  ')
(define-key global-map (kbd "<M-S-h>")     'xref-pop-marker-stack)
;; (define-key global-map (kbd "<M-S-i>")  ')
;; (define-key global-map (kbd "<M-S-j>")  ')
;; (define-key global-map (kbd "<M-S-k>")  ')
;; (define-key global-map (kbd "<M-S-l>")  ')
;; (define-key global-map (kbd "<M-S-m>")  ')
(define-key global-map (kbd "<M-S-n>")     'jd:transpose-char-left)
;; (define-key global-map (kbd "<M-S-o>")  ')
;; (define-key global-map (kbd "<M-S-p>")  ')
;; (define-key global-map (kbd "<M-S-q>")  ')
;; (define-key global-map (kbd "<M-S-r>")  ')
;; (define-key global-map (kbd "<M-S-s>")  ')
;; (define-key global-map (kbd "<M-S-t>")  ')
;; (define-key global-map (kbd "<M-S-u>")  ')
;; (define-key global-map (kbd "<M-S-v>")  ')
;; (define-key global-map (kbd "<M-S-w>")  ')
;; (define-key global-map (kbd "<M-S-x>")  ')
;; (define-key global-map (kbd "<M-S-y>")  ')
;; (define-key global-map (kbd "<M-S-z>")  ')
;; (define-key global-map (kbd "<M-S-[>")  ')
;; (define-key global-map (kbd "<M-S-]>")  ')
;; (define-key global-map (kbd "<M-S-\\>") ')
;; (define-key global-map (kbd "<M-S-;>")  ')
;; (define-key global-map (kbd "<M-S-'>")  ')
;; (define-key global-map (kbd "<M-S-,>")  ')
;; (define-key global-map (kbd "<M-S-.>")  ')
;; (define-key global-map (kbd "<M-S-/>")  ')
;; (define-key global-map (kbd "<M-S-{>")  ')
;; (define-key global-map (kbd "<M-S-}>")  ')
;; (define-key global-map (kbd "<M-S-|>")  ')
;; (define-key global-map (kbd "<M-S-:>")  ')
;; (define-key global-map (kbd "<M-S-\">") ')
;; (define-key global-map (kbd "<M-S-<>")  ')
;; (define-key global-map (kbd "<M-S->>")  ')
;; (define-key global-map (kbd "<M-S-?>")  ')
;; (define-key global-map (kbd "<M-S-`>")  ')
;; (define-key global-map (kbd "<M-S-1>")  ')
;; (define-key global-map (kbd "<M-S-2>")  ')
;; (define-key global-map (kbd "<M-S-3>")  ')
;; (define-key global-map (kbd "<M-S-4>")  ')
;; (define-key global-map (kbd "<M-S-5>")  ')
;; (define-key global-map (kbd "<M-S-6>")  ')
;; (define-key global-map (kbd "<M-S-7>")  ')
;; (define-key global-map (kbd "<M-S-8>")  ')
;; (define-key global-map (kbd "<M-S-9>")  ')
;; (define-key global-map (kbd "<M-S-0>")  ')
;; (define-key global-map (kbd "<M-S-->")  ')
;; (define-key global-map (kbd "<M-S-=>")  ')
;; (define-key global-map (kbd "<M-S-~>")  ')
;; (define-key global-map (kbd "<M-S-!>")  ')
;; (define-key global-map (kbd "<M-S-@>")  ')
;; (define-key global-map (kbd "<M-S-#>")  ')
;; (define-key global-map (kbd "<M-S-$>")  ')
;; (define-key global-map (kbd "<M-S-%>")  ')
;; (define-key global-map (kbd "<M-S-^>")  ')
;; (define-key global-map (kbd "<M-S-&>")  ')
;; (define-key global-map (kbd "<M-S-*>")  ')
;; (define-key global-map (kbd "<M-S-(>")  ')
;; (define-key global-map (kbd "<M-S-)>")  ')
;; (define-key global-map (kbd "<M-S-_>")  ')
;; (define-key global-map (kbd "<M-S-+>")  ')

;; (define-key global-map (kbd "<C-M-a>")  ')
;; (define-key global-map (kbd "<C-M-b>")  ')
;; (define-key global-map (kbd "<C-M-c>")  ')
;; (define-key global-map (kbd "<C-M-d>")  ')
;; (define-key global-map (kbd "<C-M-e>")  ')
(define-key global-map (kbd "<C-M-f>")     'counsel-switch-buffer)
;; (define-key global-map (kbd "<C-M-g>")  ')
(define-key global-map (kbd "<C-M-h>")     'jd:xref-find-references)
(define-key global-map (kbd "<C-M-i>")     'jd:scroll-up-line)
(define-key global-map (kbd "<C-M-j>")     'backward-word)
(define-key global-map (kbd "<C-M-k>")     'jd:scroll-down-line)
(define-key global-map (kbd "<C-M-l>")     'forward-word)
;; (define-key global-map (kbd "<C-M-m>")  ')
(define-key global-map (kbd "<C-M-n>")     'transpose-words)
;; (define-key global-map (kbd "<C-M-o>")  ')
;; (define-key global-map (kbd "<C-M-p>")  ')
;; (define-key global-map (kbd "<C-M-q>")  ')
;; (define-key global-map (kbd "<C-M-r>")  ')
;; (define-key global-map (kbd "<C-M-s>")  ')
;; (define-key global-map (kbd "<C-M-t>")  ')
;; (define-key global-map (kbd "<C-M-u>")  ')
;; (define-key global-map (kbd "<C-M-v>")  ')
;; (define-key global-map (kbd "<C-M-w>")  ')
(define-key global-map (kbd "<C-M-x>")     'counsel-minibuffer-history)
;; (define-key global-map (kbd "<C-M-y>")  ')
;; (define-key global-map (kbd "<C-M-z>")  ')
;; (define-key global-map (kbd "<C-M-[>")  ')
;; (define-key global-map (kbd "<C-M-]>")  ')
;; (define-key global-map (kbd "<C-M-\\>") ')
;; (define-key global-map (kbd "<C-M-;>")  ')
;; (define-key global-map (kbd "<C-M-'>")  ')
;; (define-key global-map (kbd "<C-M-,>")  ')
;; (define-key global-map (kbd "<C-M-.>")  ')
;; (define-key global-map (kbd "<C-M-/>")  ')
;; (define-key global-map (kbd "<C-M-{>")  ')
;; (define-key global-map (kbd "<C-M-}>")  ')
;; (define-key global-map (kbd "<C-M-|>")  ')
;; (define-key global-map (kbd "<C-M-:>")  ')
;; (define-key global-map (kbd "<C-M-\">") ')
;; (define-key global-map (kbd "<C-M-<>")  ')
;; (define-key global-map (kbd "<C-M->>")  ')
;; (define-key global-map (kbd "<C-M-?>")  ')
;; (define-key global-map (kbd "<C-M-`>")  ')
;; (define-key global-map (kbd "<C-M-1>")  ')
;; (define-key global-map (kbd "<C-M-2>")  ')
;; (define-key global-map (kbd "<C-M-3>")  ')
;; (define-key global-map (kbd "<C-M-4>")  ')
;; (define-key global-map (kbd "<C-M-5>")  ')
;; (define-key global-map (kbd "<C-M-6>")  ')
;; (define-key global-map (kbd "<C-M-7>")  ')
;; (define-key global-map (kbd "<C-M-8>")  ')
;; (define-key global-map (kbd "<C-M-9>")  ')
;; (define-key global-map (kbd "<C-M-0>")  ')
;; (define-key global-map (kbd "<C-M-->")  ')
;; (define-key global-map (kbd "<C-M-=>")  ')
;; (define-key global-map (kbd "<C-M-~>")  ')
;; (define-key global-map (kbd "<C-M-!>")  ')
;; (define-key global-map (kbd "<C-M-@>")  ')
;; (define-key global-map (kbd "<C-M-#>")  ')
;; (define-key global-map (kbd "<C-M-$>")  ')
;; (define-key global-map (kbd "<C-M-%>")  ')
;; (define-key global-map (kbd "<C-M-^>")  ')
;; (define-key global-map (kbd "<C-M-&>")  ')
;; (define-key global-map (kbd "<C-M-*>")  ')
;; (define-key global-map (kbd "<C-M-(>")  ')
;; (define-key global-map (kbd "<C-M-)>")  ')
;; (define-key global-map (kbd "<C-M-_>")  ')
;; (define-key global-map (kbd "<C-M-+>")  ')

;; (define-key global-map (kbd "<C-M-S-a>")  ')
;; (define-key global-map (kbd "<C-M-S-b>")  ')
;; (define-key global-map (kbd "<C-M-S-c>")  ')
;; (define-key global-map (kbd "<C-M-S-d>")  ')
;; (define-key global-map (kbd "<C-M-S-e>")  ')
;; (define-key global-map (kbd "<C-M-S-f>")  ')
;; (define-key global-map (kbd "<C-M-S-g>")  ')
;; (define-key global-map (kbd "<C-M-S-h>")  ')
;; (define-key global-map (kbd "<C-M-S-i>")  ')
;; (define-key global-map (kbd "<C-M-S-j>")  ')
;; (define-key global-map (kbd "<C-M-S-k>")  ')
;; (define-key global-map (kbd "<C-M-S-l>")  ')
;; (define-key global-map (kbd "<C-M-S-m>")  ')
;; (define-key global-map (kbd "<C-M-S-n>")  ')
;; (define-key global-map (kbd "<C-M-S-o>")  ')
;; (define-key global-map (kbd "<C-M-S-p>")  ')
;; (define-key global-map (kbd "<C-M-S-q>")  ')
;; (define-key global-map (kbd "<C-M-S-r>")  ')
;; (define-key global-map (kbd "<C-M-S-s>")  ')
;; (define-key global-map (kbd "<C-M-S-t>")  ')
;; (define-key global-map (kbd "<C-M-S-u>")  ')
;; (define-key global-map (kbd "<C-M-S-v>")  ')
;; (define-key global-map (kbd "<C-M-S-w>")  ')
;; (define-key global-map (kbd "<C-M-S-x>")  ')
;; (define-key global-map (kbd "<C-M-S-y>")  ')
;; (define-key global-map (kbd "<C-M-S-z>")  ')
;; (define-key global-map (kbd "<C-M-S-[>")  ')
;; (define-key global-map (kbd "<C-M-S-]>")  ')
;; (define-key global-map (kbd "<C-M-S-\\>") ')
;; (define-key global-map (kbd "<C-M-S-;>")  ')
;; (define-key global-map (kbd "<C-M-S-'>")  ')
;; (define-key global-map (kbd "<C-M-S-,>")  ')
;; (define-key global-map (kbd "<C-M-S-.>")  ')
;; (define-key global-map (kbd "<C-M-S-/>")  ')
;; (define-key global-map (kbd "<C-M-S-{>")  ')
;; (define-key global-map (kbd "<C-M-S-}>")  ')
;; (define-key global-map (kbd "<C-M-S-|>")  ')
;; (define-key global-map (kbd "<C-M-S-:>")  ')
;; (define-key global-map (kbd "<C-M-S-\">") ')
;; (define-key global-map (kbd "<C-M-S-<>")  ')
;; (define-key global-map (kbd "<C-M-S->>")  ')
;; (define-key global-map (kbd "<C-M-S-?>")  ')
;; (define-key global-map (kbd "<C-M-S-`>")  ')
;; (define-key global-map (kbd "<C-M-S-1>")  ')
;; (define-key global-map (kbd "<C-M-S-2>")  ')
;; (define-key global-map (kbd "<C-M-S-3>")  ')
;; (define-key global-map (kbd "<C-M-S-4>")  ')
;; (define-key global-map (kbd "<C-M-S-5>")  ')
;; (define-key global-map (kbd "<C-M-S-6>")  ')
;; (define-key global-map (kbd "<C-M-S-7>")  ')
;; (define-key global-map (kbd "<C-M-S-8>")  ')
;; (define-key global-map (kbd "<C-M-S-9>")  ')
;; (define-key global-map (kbd "<C-M-S-0>")  ')
;; (define-key global-map (kbd "<C-M-S-->")  ')
;; (define-key global-map (kbd "<C-M-S-=>")  ')
;; (define-key global-map (kbd "<C-M-S-~>")  ')
;; (define-key global-map (kbd "<C-M-S-!>")  ')
;; (define-key global-map (kbd "<C-M-S-@>")  ')
;; (define-key global-map (kbd "<C-M-S-#>")  ')
;; (define-key global-map (kbd "<C-M-S-$>")  ')
;; (define-key global-map (kbd "<C-M-S-%>")  ')
;; (define-key global-map (kbd "<C-M-S-^>")  ')
;; (define-key global-map (kbd "<C-M-S-&>")  ')
;; (define-key global-map (kbd "<C-M-S-*>")  ')
;; (define-key global-map (kbd "<C-M-S-(>")  ')
;; (define-key global-map (kbd "<C-M-S-)>")  ')
;; (define-key global-map (kbd "<C-M-S-_>")  ')
;; (define-key global-map (kbd "<C-M-S-+>")  ')

;; (define-key global-map (kbd "<H-a>")  ')
;; (define-key global-map (kbd "<H-b>")  ')
;; (define-key global-map (kbd "<H-c>")  ')
;; (define-key global-map (kbd "<H-d>")  ')
;; (define-key global-map (kbd "<H-e>")  ')
;; (define-key global-map (kbd "<H-f>")  ')
;; (define-key global-map (kbd "<H-g>")  ')
;; (define-key global-map (kbd "<H-h>")  ')
;; (define-key global-map (kbd "<H-i>")  ')
;; (define-key global-map (kbd "<H-j>")  ')
;; (define-key global-map (kbd "<H-k>")  ')
;; (define-key global-map (kbd "<H-l>")  ')
;; (define-key global-map (kbd "<H-m>")  ')
;; (define-key global-map (kbd "<H-n>")  ')
;; (define-key global-map (kbd "<H-o>")  ')
;; (define-key global-map (kbd "<H-p>")  ')
;; (define-key global-map (kbd "<H-q>")  ')
;; (define-key global-map (kbd "<H-r>")  ')
;; (define-key global-map (kbd "<H-s>")  ')
;; (define-key global-map (kbd "<H-t>")  ')
;; (define-key global-map (kbd "<H-u>")  ')
;; (define-key global-map (kbd "<H-v>")  ')
;; (define-key global-map (kbd "<H-w>")  ')
;; (define-key global-map (kbd "<H-x>")  ')
;; (define-key global-map (kbd "<H-y>")  ')
;; (define-key global-map (kbd "<H-z>")  ')
;; (define-key global-map (kbd "<H-[>")  ')
;; (define-key global-map (kbd "<H-]>")  ')
;; (define-key global-map (kbd "<H-\\>") ')
;; (define-key global-map (kbd "<H-;>")  ')
;; (define-key global-map (kbd "<H-'>")  ')
;; (define-key global-map (kbd "<H-,>")  ')
;; (define-key global-map (kbd "<H-.>")  ')
;; (define-key global-map (kbd "<H-/>")  ')
;; (define-key global-map (kbd "<H-{>")  ')
;; (define-key global-map (kbd "<H-}>")  ')
;; (define-key global-map (kbd "<H-|>")  ')
;; (define-key global-map (kbd "<H-:>")  ')
;; (define-key global-map (kbd "<H-\">") ')
;; (define-key global-map (kbd "<H-<>")  ')
;; (define-key global-map (kbd "<H->>")  ')
;; (define-key global-map (kbd "<H-?>")  ')
;; (define-key global-map (kbd "<H-`>")  ')
;; (define-key global-map (kbd "<H-1>")  ')
;; (define-key global-map (kbd "<H-2>")  ')
;; (define-key global-map (kbd "<H-3>")  ')
;; (define-key global-map (kbd "<H-4>")  ')
;; (define-key global-map (kbd "<H-5>")  ')
;; (define-key global-map (kbd "<H-6>")  ')
;; (define-key global-map (kbd "<H-7>")  ')
;; (define-key global-map (kbd "<H-8>")  ')
;; (define-key global-map (kbd "<H-9>")  ')
;; (define-key global-map (kbd "<H-0>")  ')
;; (define-key global-map (kbd "<H-->")  ')
;; (define-key global-map (kbd "<H-=>")  ')
;; (define-key global-map (kbd "<H-~>")  ')
;; (define-key global-map (kbd "<H-!>")  ')
;; (define-key global-map (kbd "<H-@>")  ')
;; (define-key global-map (kbd "<H-#>")  ')
;; (define-key global-map (kbd "<H-$>")  ')
;; (define-key global-map (kbd "<H-%>")  ')
;; (define-key global-map (kbd "<H-^>")  ')
;; (define-key global-map (kbd "<H-&>")  ')
;; (define-key global-map (kbd "<H-*>")  ')
;; (define-key global-map (kbd "<H-(>")  ')
;; (define-key global-map (kbd "<H-)>")  ')
;; (define-key global-map (kbd "<H-_>")  ')
;; (define-key global-map (kbd "<H-+>")  ')

;; (define-key global-map (kbd "<H-S-a>")  ')
;; (define-key global-map (kbd "<H-S-b>")  ')
;; (define-key global-map (kbd "<H-S-c>")  ')
;; (define-key global-map (kbd "<H-S-d>")  ')
;; (define-key global-map (kbd "<H-S-e>")  ')
;; (define-key global-map (kbd "<H-S-f>")  ')
;; (define-key global-map (kbd "<H-S-g>")  ')
;; (define-key global-map (kbd "<H-S-h>")  ')
;; (define-key global-map (kbd "<H-S-i>")  ')
;; (define-key global-map (kbd "<H-S-j>")  ')
;; (define-key global-map (kbd "<H-S-k>")  ')
;; (define-key global-map (kbd "<H-S-l>")  ')
;; (define-key global-map (kbd "<H-S-m>")  ')
;; (define-key global-map (kbd "<H-S-n>")  ')
;; (define-key global-map (kbd "<H-S-o>")  ')
;; (define-key global-map (kbd "<H-S-p>")  ')
;; (define-key global-map (kbd "<H-S-q>")  ')
;; (define-key global-map (kbd "<H-S-r>")  ')
;; (define-key global-map (kbd "<H-S-s>")  ')
;; (define-key global-map (kbd "<H-S-t>")  ')
;; (define-key global-map (kbd "<H-S-u>")  ')
;; (define-key global-map (kbd "<H-S-v>")  ')
;; (define-key global-map (kbd "<H-S-w>")  ')
;; (define-key global-map (kbd "<H-S-x>")  ')
;; (define-key global-map (kbd "<H-S-y>")  ')
;; (define-key global-map (kbd "<H-S-z>")  ')
;; (define-key global-map (kbd "<H-S-[>")  ')
;; (define-key global-map (kbd "<H-S-]>")  ')
;; (define-key global-map (kbd "<H-S-\\>") ')
;; (define-key global-map (kbd "<H-S-;>")  ')
;; (define-key global-map (kbd "<H-S-'>")  ')
;; (define-key global-map (kbd "<H-S-,>")  ')
;; (define-key global-map (kbd "<H-S-.>")  ')
;; (define-key global-map (kbd "<H-S-/>")  ')
;; (define-key global-map (kbd "<H-S-{>")  ')
;; (define-key global-map (kbd "<H-S-}>")  ')
;; (define-key global-map (kbd "<H-S-|>")  ')
;; (define-key global-map (kbd "<H-S-:>")  ')
;; (define-key global-map (kbd "<H-S-\">") ')
;; (define-key global-map (kbd "<H-S-<>")  ')
;; (define-key global-map (kbd "<H-S->>")  ')
;; (define-key global-map (kbd "<H-S-?>")  ')
;; (define-key global-map (kbd "<H-S-`>")  ')
;; (define-key global-map (kbd "<H-S-1>")  ')
;; (define-key global-map (kbd "<H-S-2>")  ')
;; (define-key global-map (kbd "<H-S-3>")  ')
;; (define-key global-map (kbd "<H-S-4>")  ')
;; (define-key global-map (kbd "<H-S-5>")  ')
;; (define-key global-map (kbd "<H-S-6>")  ')
;; (define-key global-map (kbd "<H-S-7>")  ')
;; (define-key global-map (kbd "<H-S-8>")  ')
;; (define-key global-map (kbd "<H-S-9>")  ')
;; (define-key global-map (kbd "<H-S-0>")  ')
;; (define-key global-map (kbd "<H-S-->")  ')
;; (define-key global-map (kbd "<H-S-=>")  ')
;; (define-key global-map (kbd "<H-S-~>")  ')
;; (define-key global-map (kbd "<H-S-!>")  ')
;; (define-key global-map (kbd "<H-S-@>")  ')
;; (define-key global-map (kbd "<H-S-#>")  ')
;; (define-key global-map (kbd "<H-S-$>")  ')
;; (define-key global-map (kbd "<H-S-%>")  ')
;; (define-key global-map (kbd "<H-S-^>")  ')
;; (define-key global-map (kbd "<H-S-&>")  ')
;; (define-key global-map (kbd "<H-S-*>")  ')
;; (define-key global-map (kbd "<H-S-(>")  ')
;; (define-key global-map (kbd "<H-S-)>")  ')
;; (define-key global-map (kbd "<H-S-_>")  ')
;; (define-key global-map (kbd "<H-S-+>")  ')

;; (define-key global-map (kbd "<s-a>")  ')
;; (define-key global-map (kbd "<s-b>")  ')
;; (define-key global-map (kbd "<s-c>")  ')
;; (define-key global-map (kbd "<s-d>")  ')
;; (define-key global-map (kbd "<s-e>")  ')
;; (define-key global-map (kbd "<s-f>")  ')
;; (define-key global-map (kbd "<s-g>")  ')
;; (define-key global-map (kbd "<s-h>")  ')
;; (define-key global-map (kbd "<s-i>")  ')
;; (define-key global-map (kbd "<s-j>")  ')
;; (define-key global-map (kbd "<s-k>")  ')
;; (define-key global-map (kbd "<s-l>")  ')
;; (define-key global-map (kbd "<s-m>")  ')
;; (define-key global-map (kbd "<s-n>")  ')
;; (define-key global-map (kbd "<s-o>")  ')
;; (define-key global-map (kbd "<s-p>")  ')
;; (define-key global-map (kbd "<s-q>")  ')
;; (define-key global-map (kbd "<s-r>")  ')
;; (define-key global-map (kbd "<s-s>")  ')
;; (define-key global-map (kbd "<s-t>")  ')
;; (define-key global-map (kbd "<s-u>")  ')
;; (define-key global-map (kbd "<s-v>")  ')
;; (define-key global-map (kbd "<s-w>")  ')
;; (define-key global-map (kbd "<s-x>")  ')
;; (define-key global-map (kbd "<s-y>")  ')
;; (define-key global-map (kbd "<s-z>")  ')
;; (define-key global-map (kbd "<s-[>")  ')
;; (define-key global-map (kbd "<s-]>")  ')
;; (define-key global-map (kbd "<s-\\>") ')
;; (define-key global-map (kbd "<s-;>")  ')
;; (define-key global-map (kbd "<s-'>")  ')
;; (define-key global-map (kbd "<s-,>")  ')
;; (define-key global-map (kbd "<s-.>")  ')
;; (define-key global-map (kbd "<s-/>")  ')
;; (define-key global-map (kbd "<s-{>")  ')
;; (define-key global-map (kbd "<s-}>")  ')
;; (define-key global-map (kbd "<s-|>")  ')
;; (define-key global-map (kbd "<s-:>")  ')
;; (define-key global-map (kbd "<s-\">") ')
;; (define-key global-map (kbd "<s-<>")  ')
;; (define-key global-map (kbd "<s->>")  ')
;; (define-key global-map (kbd "<s-?>")  ')
;; (define-key global-map (kbd "<s-`>")  ')
;; (define-key global-map (kbd "<s-1>")  ')
;; (define-key global-map (kbd "<s-2>")  ')
;; (define-key global-map (kbd "<s-3>")  ')
;; (define-key global-map (kbd "<s-4>")  ')
;; (define-key global-map (kbd "<s-5>")  ')
;; (define-key global-map (kbd "<s-6>")  ')
;; (define-key global-map (kbd "<s-7>")  ')
;; (define-key global-map (kbd "<s-8>")  ')
;; (define-key global-map (kbd "<s-9>")  ')
;; (define-key global-map (kbd "<s-0>")  ')
;; (define-key global-map (kbd "<s-->")  ')
;; (define-key global-map (kbd "<s-=>")  ')
;; (define-key global-map (kbd "<s-~>")  ')
;; (define-key global-map (kbd "<s-!>")  ')
;; (define-key global-map (kbd "<s-@>")  ')
;; (define-key global-map (kbd "<s-#>")  ')
;; (define-key global-map (kbd "<s-$>")  ')
;; (define-key global-map (kbd "<s-%>")  ')
;; (define-key global-map (kbd "<s-^>")  ')
;; (define-key global-map (kbd "<s-&>")  ')
;; (define-key global-map (kbd "<s-*>")  ')
;; (define-key global-map (kbd "<s-(>")  ')
;; (define-key global-map (kbd "<s-)>")  ')
;; (define-key global-map (kbd "<s-_>")  ')
;; (define-key global-map (kbd "<s-+>")  ')

;; (define-key global-map (kbd "<s-S-a>")  ')
;; (define-key global-map (kbd "<s-S-b>")  ')
;; (define-key global-map (kbd "<s-S-c>")  ')
;; (define-key global-map (kbd "<s-S-d>")  ')
;; (define-key global-map (kbd "<s-S-e>")  ')
;; (define-key global-map (kbd "<s-S-f>")  ')
;; (define-key global-map (kbd "<s-S-g>")  ')
;; (define-key global-map (kbd "<s-S-h>")  ')
;; (define-key global-map (kbd "<s-S-i>")  ')
;; (define-key global-map (kbd "<s-S-j>")  ')
;; (define-key global-map (kbd "<s-S-k>")  ')
;; (define-key global-map (kbd "<s-S-l>")  ')
;; (define-key global-map (kbd "<s-S-m>")  ')
;; (define-key global-map (kbd "<s-S-n>")  ')
;; (define-key global-map (kbd "<s-S-o>")  ')
;; (define-key global-map (kbd "<s-S-p>")  ')
;; (define-key global-map (kbd "<s-S-q>")  ')
;; (define-key global-map (kbd "<s-S-r>")  ')
;; (define-key global-map (kbd "<s-S-s>")  ')
;; (define-key global-map (kbd "<s-S-t>")  ')
;; (define-key global-map (kbd "<s-S-u>")  ')
;; (define-key global-map (kbd "<s-S-v>")  ')
;; (define-key global-map (kbd "<s-S-w>")  ')
;; (define-key global-map (kbd "<s-S-x>")  ')
;; (define-key global-map (kbd "<s-S-y>")  ')
;; (define-key global-map (kbd "<s-S-z>")  ')
;; (define-key global-map (kbd "<s-S-[>")  ')
;; (define-key global-map (kbd "<s-S-]>")  ')
;; (define-key global-map (kbd "<s-S-\\>") ')
;; (define-key global-map (kbd "<s-S-;>")  ')
;; (define-key global-map (kbd "<s-S-'>")  ')
;; (define-key global-map (kbd "<s-S-,>")  ')
;; (define-key global-map (kbd "<s-S-.>")  ')
;; (define-key global-map (kbd "<s-S-/>")  ')
;; (define-key global-map (kbd "<s-S-{>")  ')
;; (define-key global-map (kbd "<s-S-}>")  ')
;; (define-key global-map (kbd "<s-S-|>")  ')
;; (define-key global-map (kbd "<s-S-:>")  ')
;; (define-key global-map (kbd "<s-S-\">") ')
;; (define-key global-map (kbd "<s-S-<>")  ')
;; (define-key global-map (kbd "<s-S->>")  ')
;; (define-key global-map (kbd "<s-S-?>")  ')
;; (define-key global-map (kbd "<s-S-`>")  ')
;; (define-key global-map (kbd "<s-S-1>")  ')
;; (define-key global-map (kbd "<s-S-2>")  ')
;; (define-key global-map (kbd "<s-S-3>")  ')
;; (define-key global-map (kbd "<s-S-4>")  ')
;; (define-key global-map (kbd "<s-S-5>")  ')
;; (define-key global-map (kbd "<s-S-6>")  ')
;; (define-key global-map (kbd "<s-S-7>")  ')
;; (define-key global-map (kbd "<s-S-8>")  ')
;; (define-key global-map (kbd "<s-S-9>")  ')
;; (define-key global-map (kbd "<s-S-0>")  ')
;; (define-key global-map (kbd "<s-S-->")  ')
;; (define-key global-map (kbd "<s-S-=>")  ')
;; (define-key global-map (kbd "<s-S-~>")  ')
;; (define-key global-map (kbd "<s-S-!>")  ')
;; (define-key global-map (kbd "<s-S-@>")  ')
;; (define-key global-map (kbd "<s-S-#>")  ')
;; (define-key global-map (kbd "<s-S-$>")  ')
;; (define-key global-map (kbd "<s-S-%>")  ')
;; (define-key global-map (kbd "<s-S-^>")  ')
;; (define-key global-map (kbd "<s-S-&>")  ')
;; (define-key global-map (kbd "<s-S-*>")  ')
;; (define-key global-map (kbd "<s-S-(>")  ')
;; (define-key global-map (kbd "<s-S-)>")  ')
;; (define-key global-map (kbd "<s-S-_>")  ')
;; (define-key global-map (kbd "<s-S-+>")  ')

(define-key global-map (kbd "<jd:bks>")          'jd:delete-backward-char)
(define-key global-map (kbd "<jd:S-bks>")        'jd:delete-backward-char)
(define-key global-map (kbd "<jd:C-bks>")        'jd:delete-backward-word-and-reset-state-variables)
;; (define-key global-map (kbd "<jd:C-S-bks>")   ')
(define-key global-map (kbd "<jd:M-bks>")        'delete-char)
;; (define-key global-map (kbd "<jd:M-S-bks>")   ')
(define-key global-map (kbd "<jd:C-M-bks>")      'jd:incredibly-smart-backspace)
;; (define-key global-map (kbd "<jd:C-M-S-bks>") ')
;; (define-key global-map (kbd "<jd:s-bks>")     ')
;; (define-key global-map (kbd "<jd:s-S-bks>")   ')
;; (define-key global-map (kbd "<jd:H-bks>")     ')
;; (define-key global-map (kbd "<jd:H-S-bks>")   ')

;; (define-key global-map (kbd "<jd:esc>")       ')
;; (define-key global-map (kbd "<jd:S-esc>")     ')
;; (define-key global-map (kbd "<jd:C-esc>")     ')
;; (define-key global-map (kbd "<jd:C-S-esc>")   ')
;; (define-key global-map (kbd "<jd:M-esc>")     ')
;; (define-key global-map (kbd "<jd:M-S-esc>")   ')
;; (define-key global-map (kbd "<jd:C-M-esc>")   ')
;; (define-key global-map (kbd "<jd:C-M-S-esc>") ')
;; (define-key global-map (kbd "<jd:s-esc>")     ')
;; (define-key global-map (kbd "<jd:s-S-esc>")   ')
;; (define-key global-map (kbd "<jd:H-esc>")     ')
;; (define-key global-map (kbd "<jd:H-S-esc>")   ')

(define-key global-map (kbd "<jd:ret>")          'newline)
;; (define-key global-map (kbd "<jd:S-ret>")     ')
;; (define-key global-map (kbd "<jd:C-ret>")     ')
;; (define-key global-map (kbd "<jd:C-S-ret>")   ')
(define-key global-map (kbd "<jd:M-ret>")        'open-line)
;; (define-key global-map (kbd "<jd:M-S-ret>")   ')
;; (define-key global-map (kbd "<jd:C-M-ret>")   ')
;; (define-key global-map (kbd "<jd:C-M-S-ret>") ')
;; (define-key global-map (kbd "<jd:s-ret>")     ')
;; (define-key global-map (kbd "<jd:s-S-ret>")   ')
;; (define-key global-map (kbd "<jd:H-ret>")     ')
;; (define-key global-map (kbd "<jd:H-S-ret>")   ')

(define-key global-map (kbd "<jd:spc>")          'jd:self-insert-space)
(define-key global-map (kbd "<jd:S-spc>")        'jd:self-insert-space)
;; (define-key global-map (kbd "<jd:C-spc>")     ')
;; (define-key global-map (kbd "<jd:C-S-spc>")   ')
(define-key global-map (kbd "<jd:M-spc>")        'jd:select-window-and-macro-swap-buffers)
;; (define-key global-map (kbd "<jd:M-S-spc>")   ')
;; (define-key global-map (kbd "<jd:C-M-spc>")   ')
;; (define-key global-map (kbd "<jd:C-M-S-spc>") ')
;; (define-key global-map (kbd "<jd:s-spc>")     ')
;; (define-key global-map (kbd "<jd:s-S-spc>")   ')
;; (define-key global-map (kbd "<jd:H-spc>")     ')
;; (define-key global-map (kbd "<jd:H-S-spc>")   ')

(define-key global-map (kbd "<jd:tab>")          'jd:incredibly-smart-tab)
;; (define-key global-map (kbd "<jd:S-tab>")     ')
(define-key global-map (kbd "<jd:C-tab>")        'jd:window-forward)
(define-key global-map (kbd "<jd:C-S-tab>")      'jd:window-backward)
;; (define-key global-map (kbd "<jd:M-tab>")     ')
;; (define-key global-map (kbd "<jd:M-S-tab>")   ')
;; (define-key global-map (kbd "<jd:C-M-tab>")   ')
;; (define-key global-map (kbd "<jd:C-M-S-tab>") ')
;; (define-key global-map (kbd "<jd:s-tab>")     ')
;; (define-key global-map (kbd "<jd:s-S-tab>")   ')
;; (define-key global-map (kbd "<jd:H-tab>")     ')
;; (define-key global-map (kbd "<jd:H-S-tab>")   ')

(define-key global-map (kbd "<mouse-1>")                         'mouse-set-point)
(define-key global-map (kbd "<down-mouse-1>")                    'mouse-drag-region)
(define-key global-map (kbd "<drag-mouse-1>")                    'mouse-set-region)
;; (define-key global-map (kbd "<vertical-line> <mouse-1>")      ')
(define-key global-map (kbd "<vertical-line> <down-mouse-1>")    'mouse-drag-vertical-line)
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-1>") ')
(define-key global-map (kbd "<mode-line> <mouse-1>")             'mouse-select-window)
(define-key global-map (kbd "<mode-line> <down-mouse-1>")        'mouse-drag-mode-line)
;; (define-key global-map (kbd "<mode-line> <drag-mouse-1>")     ')

;; (define-key global-map (kbd "<mouse-2>")                      ')
;; (define-key global-map (kbd "<down-mouse-2>")                 ')
;; (define-key global-map (kbd "<drag-mouse-2>")                 ')
;; (define-key global-map (kbd "<vertical-line> <mouse-2>")      ')
;; (define-key global-map (kbd "<vertical-line> <down-mouse-2>") ')
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-2>") ')
;; (define-key global-map (kbd "<mode-line>     <mouse-2>")      ')
;; (define-key global-map (kbd "<mode-line>     <down-mouse-2>") ')
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-2>") ')

;; (define-key global-map (kbd "<mouse-3>")                      ')
;; (define-key global-map (kbd "<down-mouse-3>")                 ')
;; (define-key global-map (kbd "<drag-mouse-3>")                 ')
;; (define-key global-map (kbd "<vertical-line> <mouse-3>")      ')
;; (define-key global-map (kbd "<vertical-line> <down-mouse-3>") ')
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-3>") ')
;; (define-key global-map (kbd "<mode-line>     <mouse-3>")      ')
;; (define-key global-map (kbd "<mode-line>     <down-mouse-3>") ')
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-3>") ')

(define-key global-map (kbd "<mouse-4>")                         'mwheel-scroll)
;; (define-key global-map (kbd "<down-mouse-4>")                 ')
;; (define-key global-map (kbd "<drag-mouse-4>")                 ')
;; (define-key global-map (kbd "<vertical-line> <mouse-4>")      ')
;; (define-key global-map (kbd "<vertical-line> <down-mouse-4>") ')
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-4>") ')
;; (define-key global-map (kbd "<mode-line>     <mouse-4>")      ')
;; (define-key global-map (kbd "<mode-line>     <down-mouse-4>") ')
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-4>") ')

(define-key global-map (kbd "<mouse-5>")                         'mwheel-scroll)
;; (define-key global-map (kbd "<down-mouse-5>")                 ')
;; (define-key global-map (kbd "<drag-mouse-5>")                 ')
;; (define-key global-map (kbd "<vertical-line> <mouse-5>")      ')
;; (define-key global-map (kbd "<vertical-line> <down-mouse-5>") ')
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-5>") ')
;; (define-key global-map (kbd "<mode-line> <mouse-5>")          ')
;; (define-key global-map (kbd "<mode-line> <down-mouse-5>")     ')
;; (define-key global-map (kbd "<mode-line> <drag-mouse-5>")     ')

(define-key global-map (kbd "<C-h> a") 'counsel-apropos)
(define-key global-map (kbd "<C-h> b") 'jd:describe-bindings)
(define-key global-map (kbd "<C-h> c") 'apropos-command)
(define-key global-map (kbd "<C-h> d") 'apropos-documentation)
(define-key global-map (kbd "<C-h> f") 'counsel-describe-function)
(define-key global-map (kbd "<C-h> k") 'describe-key)
(define-key global-map (kbd "<C-h> l") 'view-lossage)
(define-key global-map (kbd "<C-h> m") 'describe-mode)
(define-key global-map (kbd "<C-h> p") 'describe-package)
(define-key global-map (kbd "<C-h> s") 'describe-symbol)
(define-key global-map (kbd "<C-h> v") 'counsel-describe-variable)
(define-key global-map (kbd "<C-h> y") 'jd:describe-keymap)

(define-key global-map (kbd "<C-x> l")        'goto-line)
(define-key global-map (kbd "<C-x> o")        'jd:copy-line-and-goto-end)
(define-key global-map (kbd "<C-x> r")        'point-to-register)
(define-key global-map (kbd "<C-x> u")        'jd:copy-line-and-goto-beg)
(define-key global-map (kbd "<C-x> 1")        'jd:point-to-register-1)
(define-key global-map (kbd "<C-x> 2")        'jd:point-to-register-2)
(define-key global-map (kbd "<C-x> 3")        'jd:point-to-register-3)
(define-key global-map (kbd "<C-x> 4")        'jd:point-to-register-4)
(define-key global-map (kbd "<C-x> 5")        'jd:point-to-register-5)
(define-key global-map (kbd "<C-x> 6")        'jd:point-to-register-6)
(define-key global-map (kbd "<C-x> 7")        'jd:point-to-register-7)
(define-key global-map (kbd "<C-x> 8")        'jd:point-to-register-8)
(define-key global-map (kbd "<C-x> 9")        'jd:point-to-register-9)
(define-key global-map (kbd "<C-x> 0")        'jd:reset-registers)
(define-key global-map (kbd "<C-x> <jd:bks>") 'jd:delete-line)
(define-key global-map (kbd "<C-x> <jd:tab>") 'jd:indent-region)
(define-key global-map (kbd "<C-x> <f4>")     'kmacro-edit-macro)

(define-key global-map (kbd "<C-x> <C-c>") 'save-buffers-kill-terminal)
(define-key global-map (kbd "<C-x> <C-s>") 'write-file)
(define-key global-map (kbd "<C-x> <C-w>") 'kill-buffer)

(define-key global-map (kbd "<C-x> <C-S-w>") 'delete-frame)

(define-key global-map (kbd "<C-x> <M-x>") 'eval-expression)

(define-key global-map (kbd "<f2>")  'eshell)
(define-key global-map (kbd "<f3>")  'kmacro-start-macro)
(define-key global-map (kbd "<f4>")  'kmacro-end-or-call-macro)
(define-key global-map (kbd "<f5>")  'kill-ring-save)
(define-key global-map (kbd "<f6>")  'kill-region)

(define-key global-map (kbd "<down>")  'next-line)
(define-key global-map (kbd "<left>")  'backward-char)
(define-key global-map (kbd "<right>") 'forward-char)
(define-key global-map (kbd "<up>")    'previous-line)

(define-key global-map (kbd "<wheel-left>")  'jd:scroll-right)
(define-key global-map (kbd "<wheel-right>") 'jd:scroll-left)

(define-key global-map (kbd "<C-x> <mouse-1>") 'jd:swap-windows)

(define-key minibuffer-local-map (kbd "<C-g>")    'minibuffer-keyboard-quit)
(define-key minibuffer-local-map (kbd "<C-M-i>")  'previous-history-element)
(define-key minibuffer-local-map (kbd "<C-M-k>")  'next-history-element)
(define-key minibuffer-local-map (kbd "<jd:ret>") 'exit-minibuffer)
(define-key minibuffer-local-map (kbd "<jd:spc>") 'jd:self-insert-space)
(define-key minibuffer-local-map (kbd "<jd:tab>") 'minibuffer-complete)
(define-key minibuffer-local-map (kbd "<jd:C-ret>") 'exit-minibuffer)

(provide 'jd:global-keybindings)
