(cond
 ((string-equal system-type "darwin")
  (jd:mac-keys))
 ((string-equal system-type "gnu/linux")
  (if (string-match-p "Windows" (getenv "PATH"))
      (jd:linux-keys)
    (jd:linux-keys))))

(define-prefix-command 'jd:c-h-prefix-key)
(define-prefix-command 'jd:c-x-prefix-key)

(add-hook 'post-self-insert-hook
          (lambda ()
            (setq jd:company-select nil)))

(define-key global-map (kbd "<C-a>")  'mark-whole-buffer)
;; (define-key global-map (kbd "<C-b>")  'undefined)
;; (define-key global-map (kbd "<C-c>")  'undefined)
;; (define-key global-map (kbd "<C-d>")  'undefined)
;; (define-key global-map (kbd "<C-e>")  'undefined)
(define-key global-map (kbd "<C-f>")  'swiper)
(define-key global-map (kbd "<C-g>")
  (lambda ()
    (interactive)
    (if (equal (yas--field-p (yas-current-field)) t)
        (yas-exit-all-snippets)
      (keyboard-quit))))
(define-key global-map (kbd "<C-h>")  'jd:c-h-prefix-key)
(define-key global-map (kbd "<C-i>")  'jd:scroll-up)
(define-key global-map (kbd "<C-j>")  'backward-sexp)
(define-key global-map (kbd "<C-k>")  'jd:scroll-down)
(define-key global-map (kbd "<C-l>")  'forward-sexp)
;; (define-key global-map (kbd "<C-m>")  'undefined)
(define-key global-map (kbd "<C-n>")  'jd:transpose-line-down)
(define-key global-map (kbd "<C-o>")  'end-of-buffer)
;; (define-key global-map (kbd "<C-p>")  'undefined)
(define-key global-map (kbd "<C-q>")  'quoted-insert)
;; (define-key global-map (kbd "<C-r>")  'undefined)
(define-key global-map (kbd "<C-s>")  'save-buffer)
(define-key global-map (kbd "<C-t>")  'split-window-right)
(define-key global-map (kbd "<C-u>")  'beginning-of-buffer)
;; (define-key global-map (kbd "<C-v>")  'undefined)
(define-key global-map (kbd "<C-w>")  'delete-window)
(define-key global-map (kbd "<C-x>")  'jd:c-x-prefix-key)
;; (define-key global-map (kbd "<C-y>")  'undefined)
;; (define-key global-map (kbd "<C-z>")  'undefined)
;; (define-key global-map (kbd "<C-[>")  'undefined)
;; (define-key global-map (kbd "<C-]>")  'undefined)
;; (define-key global-map (kbd "<C-\\>") 'undefined)
;; (define-key global-map (kbd "<C-;>")  'undefined)
;; (define-key global-map (kbd "<C-'>")  'undefined)
;; (define-key global-map (kbd "<C-,>")  'undefined)
;; (define-key global-map (kbd "<C-.>")  'undefined)
(define-key global-map (kbd "<C-/>")  'comment-region)
;; (define-key global-map (kbd "<C-{>")  'undefined)
;; (define-key global-map (kbd "<C-}>")  'undefined)
;; (define-key global-map (kbd "<C-|>")  'undefined)
;; (define-key global-map (kbd "<C-:>")  'undefined)
;; (define-key global-map (kbd "<C-\">") 'undefined)
;; (define-key global-map (kbd "<C-<>")  'undefined)
;; (define-key global-map (kbd "<C->>")  'undefined)
(define-key global-map (kbd "<C-?>")  'uncomment-region)
;; (define-key global-map (kbd "<C-`>")  'undefined)
(define-key global-map (kbd "<C-1>")  (lambda () (interactive) (jump-to-register 1)))
(define-key global-map (kbd "<C-2>")  (lambda () (interactive) (jump-to-register 2)))
(define-key global-map (kbd "<C-3>")  (lambda () (interactive) (jump-to-register 3)))
(define-key global-map (kbd "<C-4>")  (lambda () (interactive) (jump-to-register 4)))
(define-key global-map (kbd "<C-5>")  (lambda () (interactive) (jump-to-register 5)))
(define-key global-map (kbd "<C-6>")  (lambda () (interactive) (jump-to-register 6)))
(define-key global-map (kbd "<C-7>")  (lambda () (interactive) (jump-to-register 7)))
(define-key global-map (kbd "<C-8>")  (lambda () (interactive) (jump-to-register 8)))
(define-key global-map (kbd "<C-9>")  (lambda () (interactive) (jump-to-register 9)))
;; (define-key global-map (kbd "<C-0>")  'undefined)
;; (define-key global-map (kbd "<C-->")  'undefined)
(define-key global-map (kbd "<C-=>")  'universal-argument)
;; (define-key global-map (kbd "<C-~>")  'undefined)
;; (define-key global-map (kbd "<C-!>")  'undefined)
;; (define-key global-map (kbd "<C-@>")  'undefined)
;; (define-key global-map (kbd "<C-#>")  'undefined)
;; (define-key global-map (kbd "<C-$>")  'undefined)
;; (define-key global-map (kbd "<C-%>")  'undefined)
;; (define-key global-map (kbd "<C-^>")  'undefined)
;; (define-key global-map (kbd "<C-&>")  'undefined)
;; (define-key global-map (kbd "<C-*>")  'undefined)
;; (define-key global-map (kbd "<C-(>")  'undefined)
;; (define-key global-map (kbd "<C-)>")  'undefined)
;; (define-key global-map (kbd "<C-_>")  'undefined)
;; (define-key global-map (kbd "<C-+>")  'undefined)

;; (define-key global-map (kbd "<C-S-a>")  'undefined)
;; (define-key global-map (kbd "<C-S-b>")  'undefined)
;; (define-key global-map (kbd "<C-S-c>")  'undefined)
;; (define-key global-map (kbd "<C-S-d>")  'undefined)
;; (define-key global-map (kbd "<C-S-e>")  'undefined)
(define-key global-map (kbd "<C-S-f>")  'swiper-query-replace)
;; (define-key global-map (kbd "<C-S-g>")  'undefined)
;; (define-key global-map (kbd "<C-S-h>")  'undefined)
;; (define-key global-map (kbd "<C-S-i>")  'undefined)
;; (define-key global-map (kbd "<C-S-j>")  'undefined)
;; (define-key global-map (kbd "<C-S-k>")  'undefined)
;; (define-key global-map (kbd "<C-S-l>")  'undefined)
;; (define-key global-map (kbd "<C-S-m>")  'undefined)
(define-key global-map (kbd "<C-S-n>")  'jd:transpose-line-up)
;; (define-key global-map (kbd "<C-S-o>")  'undefined)
;; (define-key global-map (kbd "<C-S-p>")  'undefined)
;; (define-key global-map (kbd "<C-S-q>")  'undefined)
;; (define-key global-map (kbd "<C-S-r>")  'undefined)
;; (define-key global-map (kbd "<C-S-s>")  'undefined)
(define-key global-map (kbd "<C-S-t>")  'split-window-below)
;; (define-key global-map (kbd "<C-S-u>")  'undefined)
;; (define-key global-map (kbd "<C-S-v>")  'undefined)
;; (define-key global-map (kbd "<C-S-w>")  'undefined)
;; (define-key global-map (kbd "<C-S-x>")  'undefined)
;; (define-key global-map (kbd "<C-S-y>")  'undefined)
;; (define-key global-map (kbd "<C-S-z>")  'undefined)
;; (define-key global-map (kbd "<C-S-[>")  'undefined)
;; (define-key global-map (kbd "<C-S-]>")  'undefined)
;; (define-key global-map (kbd "<C-S-\\>") 'undefined)
;; (define-key global-map (kbd "<C-S-;>")  'undefined)
;; (define-key global-map (kbd "<C-S-'>")  'undefined)
;; (define-key global-map (kbd "<C-S-,>")  'undefined)
;; (define-key global-map (kbd "<C-S-.>")  'undefined)
;; (define-key global-map (kbd "<C-S-/>")  'undefined)
;; (define-key global-map (kbd "<C-S-{>")  'undefined)
;; (define-key global-map (kbd "<C-S-}>")  'undefined)
;; (define-key global-map (kbd "<C-S-|>")  'undefined)
;; (define-key global-map (kbd "<C-S-:>")  'undefined)
;; (define-key global-map (kbd "<C-S-\">") 'undefined)
;; (define-key global-map (kbd "<C-S-<>")  'undefined)
;; (define-key global-map (kbd "<C-S->>")  'undefined)
;; (define-key global-map (kbd "<C-S-?>")  'undefined)
;; (define-key global-map (kbd "<C-S-`>")  'undefined)
;; (define-key global-map (kbd "<C-S-1>")  'undefined)
;; (define-key global-map (kbd "<C-S-2>")  'undefined)
;; (define-key global-map (kbd "<C-S-3>")  'undefined)
;; (define-key global-map (kbd "<C-S-4>")  'undefined)
;; (define-key global-map (kbd "<C-S-5>")  'undefined)
;; (define-key global-map (kbd "<C-S-6>")  'undefined)
;; (define-key global-map (kbd "<C-S-7>")  'undefined)
;; (define-key global-map (kbd "<C-S-8>")  'undefined)
;; (define-key global-map (kbd "<C-S-9>")  'undefined)
;; (define-key global-map (kbd "<C-S-0>")  'undefined)
;; (define-key global-map (kbd "<C-S-->")  'undefined)
;; (define-key global-map (kbd "<C-S-=>")  'undefined)
;; (define-key global-map (kbd "<C-S-~>")  'undefined)
;; (define-key global-map (kbd "<C-S-!>")  'undefined)
;; (define-key global-map (kbd "<C-S-@>")  'undefined)
;; (define-key global-map (kbd "<C-S-#>")  'undefined)
;; (define-key global-map (kbd "<C-S-$>")  'undefined)
;; (define-key global-map (kbd "<C-S-%>")  'undefined)
;; (define-key global-map (kbd "<C-S-^>")  'undefined)
;; (define-key global-map (kbd "<C-S-&>")  'undefined)
;; (define-key global-map (kbd "<C-S-*>")  'undefined)
;; (define-key global-map (kbd "<C-S-(>")  'undefined)
;; (define-key global-map (kbd "<C-S-)>")  'undefined)
;; (define-key global-map (kbd "<C-S-_>")  'undefined)
;; (define-key global-map (kbd "<C-S-+>")  'undefined)

;; (define-key global-map (kbd "<M-a>")  'undefined)
;; (define-key global-map (kbd "<M-b>")  'undefined)
;; (define-key global-map (kbd "<M-c>")  'undefined)
;; (define-key global-map (kbd "<M-d>")  'undefined)
;; (define-key global-map (kbd "<M-e>")  'undefined)
(define-key global-map (kbd "<M-f>")  'counsel-find-file)
;; (define-key global-map (kbd "<M-g>")  'undefined)
(define-key global-map (kbd "<M-h>")  'jd:xref-find-definitions)
(define-key global-map (kbd "<M-i>")  'previous-line)
(define-key global-map (kbd "<M-j>")  'backward-char)
(define-key global-map (kbd "<M-k>")  'next-line)
(define-key global-map (kbd "<M-l>")  'forward-char)
;; (define-key global-map (kbd "<M-m>")  'undefined)
(define-key global-map (kbd "<M-n>")  'jd:transpose-char-right)
(define-key global-map (kbd "<M-o>")  'end-of-line)
;; (define-key global-map (kbd "<M-p>")  'undefined)
;; (define-key global-map (kbd "<M-q>")  'undefined)
;; (define-key global-map (kbd "<M-r>")  'undefined)
;; (define-key global-map (kbd "<M-s>")  'undefined)
;; (define-key global-map (kbd "<M-t>")  'undefined)
(define-key global-map (kbd "<M-u>")  'back-to-indentation)
;; (define-key global-map (kbd "<M-v>")  'undefined)
(define-key global-map (kbd "<M-w>")  'delete-other-windows)
(define-key global-map (kbd "<M-x>")  'counsel-M-x)
;; (define-key global-map (kbd "<M-y>")  'undefined)
;; (define-key global-map (kbd "<M-z>")  'undefined)
;; (define-key global-map (kbd "<M-[>")  'undefined)
;; (define-key global-map (kbd "<M-]>")  'undefined)
;; (define-key global-map (kbd "<M-\\>") 'undefined)
(define-key global-map (kbd "<M-;>")  'recenter)
;; (define-key global-map (kbd "<M-'>")  'undefined)
;; (define-key global-map (kbd "<M-,>")  'undefined)
;; (define-key global-map (kbd "<M-.>")  'undefined)
;; (define-key global-map (kbd "<M-/>")  'undefined)
;; (define-key global-map (kbd "<M-{>")  'undefined)
;; (define-key global-map (kbd "<M-}>")  'undefined)
;; (define-key global-map (kbd "<M-|>")  'undefined)
;; (define-key global-map (kbd "<M-:>")  'undefined)
;; (define-key global-map (kbd "<M-\">") 'undefined)
;; (define-key global-map (kbd "<M-<>")  'undefined)
;; (define-key global-map (kbd "<M->>")  'undefined)
;; (define-key global-map (kbd "<M-?>")  'undefined)
;; (define-key global-map (kbd "<M-`>")  'undefined)
;; (define-key global-map (kbd "<M-1>")  'undefined)
;; (define-key global-map (kbd "<M-2>")  'undefined)
;; (define-key global-map (kbd "<M-3>")  'undefined)
;; (define-key global-map (kbd "<M-4>")  'undefined)
;; (define-key global-map (kbd "<M-5>")  'undefined)
;; (define-key global-map (kbd "<M-6>")  'undefined)
;; (define-key global-map (kbd "<M-7>")  'undefined)
;; (define-key global-map (kbd "<M-8>")  'undefined)
;; (define-key global-map (kbd "<M-9>")  'undefined)
;; (define-key global-map (kbd "<M-0>")  'undefined)
;; (define-key global-map (kbd "<M-->")  'undefined)
;; (define-key global-map (kbd "<M-=>")  'undefined)
;; (define-key global-map (kbd "<M-~>")  'undefined)
;; (define-key global-map (kbd "<M-!>")  'undefined)
;; (define-key global-map (kbd "<M-@>")  'undefined)
;; (define-key global-map (kbd "<M-#>")  'undefined)
;; (define-key global-map (kbd "<M-$>")  'undefined)
;; (define-key global-map (kbd "<M-%>")  'undefined)
;; (define-key global-map (kbd "<M-^>")  'undefined)
;; (define-key global-map (kbd "<M-&>")  'undefined)
;; (define-key global-map (kbd "<M-*>")  'undefined)
;; (define-key global-map (kbd "<M-(>")  'undefined)
;; (define-key global-map (kbd "<M-)>")  'undefined)
;; (define-key global-map (kbd "<M-_>")  'undefined)
;; (define-key global-map (kbd "<M-+>")  'undefined)

;; (define-key global-map (kbd "<M-S-a>")  'undefined)
;; (define-key global-map (kbd "<M-S-b>")  'undefined)
;; (define-key global-map (kbd "<M-S-c>")  'undefined)
;; (define-key global-map (kbd "<M-S-d>")  'undefined)
;; (define-key global-map (kbd "<M-S-e>")  'undefined)
;; (define-key global-map (kbd "<M-S-f>")  'undefined)
;; (define-key global-map (kbd "<M-S-g>")  'undefined)
(define-key global-map (kbd "<M-S-h>")  'xref-pop-marker-stack)
;; (define-key global-map (kbd "<M-S-i>")  'undefined)
;; (define-key global-map (kbd "<M-S-j>")  'undefined)
;; (define-key global-map (kbd "<M-S-k>")  'undefined)
;; (define-key global-map (kbd "<M-S-l>")  'undefined)
;; (define-key global-map (kbd "<M-S-m>")  'undefined)
(define-key global-map (kbd "<M-S-n>")  'jd:transpose-char-left)
;; (define-key global-map (kbd "<M-S-o>")  'undefined)
;; (define-key global-map (kbd "<M-S-p>")  'undefined)
;; (define-key global-map (kbd "<M-S-q>")  'undefined)
;; (define-key global-map (kbd "<M-S-r>")  'undefined)
;; (define-key global-map (kbd "<M-S-s>")  'undefined)
;; (define-key global-map (kbd "<M-S-t>")  'undefined)
;; (define-key global-map (kbd "<M-S-u>")  'undefined)
;; (define-key global-map (kbd "<M-S-v>")  'undefined)
;; (define-key global-map (kbd "<M-S-w>")  'undefined)
;; (define-key global-map (kbd "<M-S-x>")  'undefined)
;; (define-key global-map (kbd "<M-S-y>")  'undefined)
;; (define-key global-map (kbd "<M-S-z>")  'undefined)
;; (define-key global-map (kbd "<M-S-[>")  'undefined)
;; (define-key global-map (kbd "<M-S-]>")  'undefined)
;; (define-key global-map (kbd "<M-S-\\>") 'undefined)
;; (define-key global-map (kbd "<M-S-;>")  'undefined)
;; (define-key global-map (kbd "<M-S-'>")  'undefined)
;; (define-key global-map (kbd "<M-S-,>")  'undefined)
;; (define-key global-map (kbd "<M-S-.>")  'undefined)
;; (define-key global-map (kbd "<M-S-/>")  'undefined)
;; (define-key global-map (kbd "<M-S-{>")  'undefined)
;; (define-key global-map (kbd "<M-S-}>")  'undefined)
;; (define-key global-map (kbd "<M-S-|>")  'undefined)
;; (define-key global-map (kbd "<M-S-:>")  'undefined)
;; (define-key global-map (kbd "<M-S-\">") 'undefined)
;; (define-key global-map (kbd "<M-S-<>")  'undefined)
;; (define-key global-map (kbd "<M-S->>")  'undefined)
;; (define-key global-map (kbd "<M-S-?>")  'undefined)
;; (define-key global-map (kbd "<M-S-`>")  'undefined)
;; (define-key global-map (kbd "<M-S-1>")  'undefined)
;; (define-key global-map (kbd "<M-S-2>")  'undefined)
;; (define-key global-map (kbd "<M-S-3>")  'undefined)
;; (define-key global-map (kbd "<M-S-4>")  'undefined)
;; (define-key global-map (kbd "<M-S-5>")  'undefined)
;; (define-key global-map (kbd "<M-S-6>")  'undefined)
;; (define-key global-map (kbd "<M-S-7>")  'undefined)
;; (define-key global-map (kbd "<M-S-8>")  'undefined)
;; (define-key global-map (kbd "<M-S-9>")  'undefined)
;; (define-key global-map (kbd "<M-S-0>")  'undefined)
;; (define-key global-map (kbd "<M-S-->")  'undefined)
;; (define-key global-map (kbd "<M-S-=>")  'undefined)
;; (define-key global-map (kbd "<M-S-~>")  'undefined)
;; (define-key global-map (kbd "<M-S-!>")  'undefined)
;; (define-key global-map (kbd "<M-S-@>")  'undefined)
;; (define-key global-map (kbd "<M-S-#>")  'undefined)
;; (define-key global-map (kbd "<M-S-$>")  'undefined)
;; (define-key global-map (kbd "<M-S-%>")  'undefined)
;; (define-key global-map (kbd "<M-S-^>")  'undefined)
;; (define-key global-map (kbd "<M-S-&>")  'undefined)
;; (define-key global-map (kbd "<M-S-*>")  'undefined)
;; (define-key global-map (kbd "<M-S-(>")  'undefined)
;; (define-key global-map (kbd "<M-S-)>")  'undefined)
;; (define-key global-map (kbd "<M-S-_>")  'undefined)
;; (define-key global-map (kbd "<M-S-+>")  'undefined)

;; (define-key global-map (kbd "<C-M-a>")  'undefined)
;; (define-key global-map (kbd "<C-M-b>")  'undefined)
;; (define-key global-map (kbd "<C-M-c>")  'undefined)
;; (define-key global-map (kbd "<C-M-d>")  'undefined)
;; (define-key global-map (kbd "<C-M-e>")  'undefined)
(define-key global-map (kbd "<C-M-f>") 'counsel-switch-buffer)
;; (define-key global-map (kbd "<C-M-g>")  'undefined)
(define-key global-map (kbd "<C-M-h>")  'jd:xref-find-references)
(define-key global-map (kbd "<C-M-i>")
  (lambda ()
    (interactive "^")
    (scroll-down-line 1)
    (next-line -1)))
(define-key global-map (kbd "<C-M-j>")  'backward-word)
(define-key global-map (kbd "<C-M-k>")
  (lambda ()
    (interactive "^")
    (scroll-down-line -1)
    (next-line 1)))
(define-key global-map (kbd "<C-M-l>")  'forward-word)
;; (define-key global-map (kbd "<C-M-m>")  'undefined)
(define-key global-map (kbd "<C-M-n>")  'transpose-words)
;; (define-key global-map (kbd "<C-M-o>")  'undefined)
;; (define-key global-map (kbd "<C-M-p>")  'undefined)
;; (define-key global-map (kbd "<C-M-q>")  'undefined)
;; (define-key global-map (kbd "<C-M-r>")  'undefined)
;; (define-key global-map (kbd "<C-M-s>")  'undefined)
;; (define-key global-map (kbd "<C-M-t>")  'undefined)
;; (define-key global-map (kbd "<C-M-u>")  'undefined)
;; (define-key global-map (kbd "<C-M-v>")  'undefined)
;; (define-key global-map (kbd "<C-M-w>")  'undefined)
(define-key global-map (kbd "<C-M-x>")  'counsel-minibuffer-history)
;; (define-key global-map (kbd "<C-M-y>")  'undefined)
;; (define-key global-map (kbd "<C-M-z>")  'undefined)
;; (define-key global-map (kbd "<C-M-[>")  'undefined)
;; (define-key global-map (kbd "<C-M-]>")  'undefined)
;; (define-key global-map (kbd "<C-M-\\>") 'undefined)
;; (define-key global-map (kbd "<C-M-;>")  'undefined)
;; (define-key global-map (kbd "<C-M-'>")  'undefined)
;; (define-key global-map (kbd "<C-M-,>")  'undefined)
;; (define-key global-map (kbd "<C-M-.>")  'undefined)
;; (define-key global-map (kbd "<C-M-/>")  'undefined)
;; (define-key global-map (kbd "<C-M-{>")  'undefined)
;; (define-key global-map (kbd "<C-M-}>")  'undefined)
;; (define-key global-map (kbd "<C-M-|>")  'undefined)
;; (define-key global-map (kbd "<C-M-:>")  'undefined)
;; (define-key global-map (kbd "<C-M-\">") 'undefined)
;; (define-key global-map (kbd "<C-M-<>")  'undefined)
;; (define-key global-map (kbd "<C-M->>")  'undefined)
;; (define-key global-map (kbd "<C-M-?>")  'undefined)
;; (define-key global-map (kbd "<C-M-`>")  'undefined)
;; (define-key global-map (kbd "<C-M-1>")  'undefined)
;; (define-key global-map (kbd "<C-M-2>")  'undefined)
;; (define-key global-map (kbd "<C-M-3>")  'undefined)
;; (define-key global-map (kbd "<C-M-4>")  'undefined)
;; (define-key global-map (kbd "<C-M-5>")  'undefined)
;; (define-key global-map (kbd "<C-M-6>")  'undefined)
;; (define-key global-map (kbd "<C-M-7>")  'undefined)
;; (define-key global-map (kbd "<C-M-8>")  'undefined)
;; (define-key global-map (kbd "<C-M-9>")  'undefined)
;; (define-key global-map (kbd "<C-M-0>")  'undefined)
;; (define-key global-map (kbd "<C-M-->")  'undefined)
;; (define-key global-map (kbd "<C-M-=>")  'undefined)
;; (define-key global-map (kbd "<C-M-~>")  'undefined)
;; (define-key global-map (kbd "<C-M-!>")  'undefined)
;; (define-key global-map (kbd "<C-M-@>")  'undefined)
;; (define-key global-map (kbd "<C-M-#>")  'undefined)
;; (define-key global-map (kbd "<C-M-$>")  'undefined)
;; (define-key global-map (kbd "<C-M-%>")  'undefined)
;; (define-key global-map (kbd "<C-M-^>")  'undefined)
;; (define-key global-map (kbd "<C-M-&>")  'undefined)
;; (define-key global-map (kbd "<C-M-*>")  'undefined)
;; (define-key global-map (kbd "<C-M-(>")  'undefined)
;; (define-key global-map (kbd "<C-M-)>")  'undefined)
;; (define-key global-map (kbd "<C-M-_>")  'undefined)
;; (define-key global-map (kbd "<C-M-+>")  'undefined)

;; (define-key global-map (kbd "<C-M-S-a>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-b>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-c>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-d>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-e>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-f>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-g>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-h>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-i>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-j>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-k>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-l>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-m>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-n>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-o>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-p>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-q>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-r>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-s>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-t>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-u>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-v>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-w>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-x>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-y>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-z>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-[>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-]>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-\\>") 'undefined)
;; (define-key global-map (kbd "<C-M-S-;>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-'>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-,>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-.>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-/>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-{>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-}>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-|>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-:>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-\">") 'undefined)
;; (define-key global-map (kbd "<C-M-S-<>")  'undefined)
;; (define-key global-map (kbd "<C-M-S->>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-?>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-`>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-1>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-2>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-3>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-4>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-5>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-6>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-7>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-8>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-9>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-0>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-->")  'undefined)
;; (define-key global-map (kbd "<C-M-S-=>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-~>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-!>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-@>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-#>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-$>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-%>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-^>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-&>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-*>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-(>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-)>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-_>")  'undefined)
;; (define-key global-map (kbd "<C-M-S-+>")  'undefined)

;; (define-key global-map (kbd "<H-a>")  'undefined)
;; (define-key global-map (kbd "<H-b>")  'undefined)
;; (define-key global-map (kbd "<H-c>")  'undefined)
;; (define-key global-map (kbd "<H-d>")  'undefined)
;; (define-key global-map (kbd "<H-e>")  'undefined)
;; (define-key global-map (kbd "<H-f>")  'undefined)
;; (define-key global-map (kbd "<H-g>")  'undefined)
;; (define-key global-map (kbd "<H-h>")  'undefined)
;; (define-key global-map (kbd "<H-i>")  'undefined)
;; (define-key global-map (kbd "<H-j>")  'undefined)
;; (define-key global-map (kbd "<H-k>")  'undefined)
;; (define-key global-map (kbd "<H-l>")  'undefined)
;; (define-key global-map (kbd "<H-m>")  'undefined)
;; (define-key global-map (kbd "<H-n>")  'undefined)
;; (define-key global-map (kbd "<H-o>")  'undefined)
;; (define-key global-map (kbd "<H-p>")  'undefined)
;; (define-key global-map (kbd "<H-q>")  'undefined)
;; (define-key global-map (kbd "<H-r>")  'undefined)
;; (define-key global-map (kbd "<H-s>")  'undefined)
;; (define-key global-map (kbd "<H-t>")  'undefined)
;; (define-key global-map (kbd "<H-u>")  'undefined)
;; (define-key global-map (kbd "<H-v>")  'undefined)
;; (define-key global-map (kbd "<H-w>")  'undefined)
;; (define-key global-map (kbd "<H-x>")  'undefined)
;; (define-key global-map (kbd "<H-y>")  'undefined)
;; (define-key global-map (kbd "<H-z>")  'undefined)
;; (define-key global-map (kbd "<H-[>")  'undefined)
;; (define-key global-map (kbd "<H-]>")  'undefined)
;; (define-key global-map (kbd "<H-\\>") 'undefined)
;; (define-key global-map (kbd "<H-;>")  'undefined)
;; (define-key global-map (kbd "<H-'>")  'undefined)
;; (define-key global-map (kbd "<H-,>")  'undefined)
;; (define-key global-map (kbd "<H-.>")  'undefined)
;; (define-key global-map (kbd "<H-/>")  'undefined)
;; (define-key global-map (kbd "<H-{>")  'undefined)
;; (define-key global-map (kbd "<H-}>")  'undefined)
;; (define-key global-map (kbd "<H-|>")  'undefined)
;; (define-key global-map (kbd "<H-:>")  'undefined)
;; (define-key global-map (kbd "<H-\">") 'undefined)
;; (define-key global-map (kbd "<H-<>")  'undefined)
;; (define-key global-map (kbd "<H->>")  'undefined)
;; (define-key global-map (kbd "<H-?>")  'undefined)
;; (define-key global-map (kbd "<H-`>")  'undefined)
;; (define-key global-map (kbd "<H-1>")  'undefined)
;; (define-key global-map (kbd "<H-2>")  'undefined)
;; (define-key global-map (kbd "<H-3>")  'undefined)
;; (define-key global-map (kbd "<H-4>")  'undefined)
;; (define-key global-map (kbd "<H-5>")  'undefined)
;; (define-key global-map (kbd "<H-6>")  'undefined)
;; (define-key global-map (kbd "<H-7>")  'undefined)
;; (define-key global-map (kbd "<H-8>")  'undefined)
;; (define-key global-map (kbd "<H-9>")  'undefined)
;; (define-key global-map (kbd "<H-0>")  'undefined)
;; (define-key global-map (kbd "<H-->")  'undefined)
;; (define-key global-map (kbd "<H-=>")  'undefined)
;; (define-key global-map (kbd "<H-~>")  'undefined)
;; (define-key global-map (kbd "<H-!>")  'undefined)
;; (define-key global-map (kbd "<H-@>")  'undefined)
;; (define-key global-map (kbd "<H-#>")  'undefined)
;; (define-key global-map (kbd "<H-$>")  'undefined)
;; (define-key global-map (kbd "<H-%>")  'undefined)
;; (define-key global-map (kbd "<H-^>")  'undefined)
;; (define-key global-map (kbd "<H-&>")  'undefined)
;; (define-key global-map (kbd "<H-*>")  'undefined)
;; (define-key global-map (kbd "<H-(>")  'undefined)
;; (define-key global-map (kbd "<H-)>")  'undefined)
;; (define-key global-map (kbd "<H-_>")  'undefined)
;; (define-key global-map (kbd "<H-+>")  'undefined)

;; (define-key global-map (kbd "<H-S-a>")  'undefined)
;; (define-key global-map (kbd "<H-S-b>")  'undefined)
;; (define-key global-map (kbd "<H-S-c>")  'undefined)
;; (define-key global-map (kbd "<H-S-d>")  'undefined)
;; (define-key global-map (kbd "<H-S-e>")  'undefined)
;; (define-key global-map (kbd "<H-S-f>")  'undefined)
;; (define-key global-map (kbd "<H-S-g>")  'undefined)
;; (define-key global-map (kbd "<H-S-h>")  'undefined)
;; (define-key global-map (kbd "<H-S-i>")  'undefined)
;; (define-key global-map (kbd "<H-S-j>")  'undefined)
;; (define-key global-map (kbd "<H-S-k>")  'undefined)
;; (define-key global-map (kbd "<H-S-l>")  'undefined)
;; (define-key global-map (kbd "<H-S-m>")  'undefined)
;; (define-key global-map (kbd "<H-S-n>")  'undefined)
;; (define-key global-map (kbd "<H-S-o>")  'undefined)
;; (define-key global-map (kbd "<H-S-p>")  'undefined)
;; (define-key global-map (kbd "<H-S-q>")  'undefined)
;; (define-key global-map (kbd "<H-S-r>")  'undefined)
;; (define-key global-map (kbd "<H-S-s>")  'undefined)
;; (define-key global-map (kbd "<H-S-t>")  'undefined)
;; (define-key global-map (kbd "<H-S-u>")  'undefined)
;; (define-key global-map (kbd "<H-S-v>")  'undefined)
;; (define-key global-map (kbd "<H-S-w>")  'undefined)
;; (define-key global-map (kbd "<H-S-x>")  'undefined)
;; (define-key global-map (kbd "<H-S-y>")  'undefined)
;; (define-key global-map (kbd "<H-S-z>")  'undefined)
;; (define-key global-map (kbd "<H-S-[>")  'undefined)
;; (define-key global-map (kbd "<H-S-]>")  'undefined)
;; (define-key global-map (kbd "<H-S-\\>") 'undefined)
;; (define-key global-map (kbd "<H-S-;>")  'undefined)
;; (define-key global-map (kbd "<H-S-'>")  'undefined)
;; (define-key global-map (kbd "<H-S-,>")  'undefined)
;; (define-key global-map (kbd "<H-S-.>")  'undefined)
;; (define-key global-map (kbd "<H-S-/>")  'undefined)
;; (define-key global-map (kbd "<H-S-{>")  'undefined)
;; (define-key global-map (kbd "<H-S-}>")  'undefined)
;; (define-key global-map (kbd "<H-S-|>")  'undefined)
;; (define-key global-map (kbd "<H-S-:>")  'undefined)
;; (define-key global-map (kbd "<H-S-\">") 'undefined)
;; (define-key global-map (kbd "<H-S-<>")  'undefined)
;; (define-key global-map (kbd "<H-S->>")  'undefined)
;; (define-key global-map (kbd "<H-S-?>")  'undefined)
;; (define-key global-map (kbd "<H-S-`>")  'undefined)
;; (define-key global-map (kbd "<H-S-1>")  'undefined)
;; (define-key global-map (kbd "<H-S-2>")  'undefined)
;; (define-key global-map (kbd "<H-S-3>")  'undefined)
;; (define-key global-map (kbd "<H-S-4>")  'undefined)
;; (define-key global-map (kbd "<H-S-5>")  'undefined)
;; (define-key global-map (kbd "<H-S-6>")  'undefined)
;; (define-key global-map (kbd "<H-S-7>")  'undefined)
;; (define-key global-map (kbd "<H-S-8>")  'undefined)
;; (define-key global-map (kbd "<H-S-9>")  'undefined)
;; (define-key global-map (kbd "<H-S-0>")  'undefined)
;; (define-key global-map (kbd "<H-S-->")  'undefined)
;; (define-key global-map (kbd "<H-S-=>")  'undefined)
;; (define-key global-map (kbd "<H-S-~>")  'undefined)
;; (define-key global-map (kbd "<H-S-!>")  'undefined)
;; (define-key global-map (kbd "<H-S-@>")  'undefined)
;; (define-key global-map (kbd "<H-S-#>")  'undefined)
;; (define-key global-map (kbd "<H-S-$>")  'undefined)
;; (define-key global-map (kbd "<H-S-%>")  'undefined)
;; (define-key global-map (kbd "<H-S-^>")  'undefined)
;; (define-key global-map (kbd "<H-S-&>")  'undefined)
;; (define-key global-map (kbd "<H-S-*>")  'undefined)
;; (define-key global-map (kbd "<H-S-(>")  'undefined)
;; (define-key global-map (kbd "<H-S-)>")  'undefined)
;; (define-key global-map (kbd "<H-S-_>")  'undefined)
;; (define-key global-map (kbd "<H-S-+>")  'undefined)

;; (define-key global-map (kbd "<s-a>")  'undefined)
;; (define-key global-map (kbd "<s-b>")  'undefined)
;; (define-key global-map (kbd "<s-c>")  'undefined)
;; (define-key global-map (kbd "<s-d>")  'undefined)
;; (define-key global-map (kbd "<s-e>")  'undefined)
;; (define-key global-map (kbd "<s-f>")  'undefined)
;; (define-key global-map (kbd "<s-g>")  'undefined)
;; (define-key global-map (kbd "<s-h>")  'undefined)
;; (define-key global-map (kbd "<s-i>")  'undefined)
;; (define-key global-map (kbd "<s-j>")  'undefined)
;; (define-key global-map (kbd "<s-k>")  'undefined)
;; (define-key global-map (kbd "<s-l>")  'undefined)
;; (define-key global-map (kbd "<s-m>")  'undefined)
;; (define-key global-map (kbd "<s-n>")  'undefined)
;; (define-key global-map (kbd "<s-o>")  'undefined)
;; (define-key global-map (kbd "<s-p>")  'undefined)
;; (define-key global-map (kbd "<s-q>")  'undefined)
;; (define-key global-map (kbd "<s-r>")  'undefined)
;; (define-key global-map (kbd "<s-s>")  'undefined)
;; (define-key global-map (kbd "<s-t>")  'undefined)
;; (define-key global-map (kbd "<s-u>")  'undefined)
;; (define-key global-map (kbd "<s-v>")  'undefined)
;; (define-key global-map (kbd "<s-w>")  'undefined)
;; (define-key global-map (kbd "<s-x>")  'undefined)
;; (define-key global-map (kbd "<s-y>")  'undefined)
;; (define-key global-map (kbd "<s-z>")  'undefined)
;; (define-key global-map (kbd "<s-[>")  'undefined)
;; (define-key global-map (kbd "<s-]>")  'undefined)
;; (define-key global-map (kbd "<s-\\>") 'undefined)
;; (define-key global-map (kbd "<s-;>")  'undefined)
;; (define-key global-map (kbd "<s-'>")  'undefined)
;; (define-key global-map (kbd "<s-,>")  'undefined)
;; (define-key global-map (kbd "<s-.>")  'undefined)
;; (define-key global-map (kbd "<s-/>")  'undefined)
;; (define-key global-map (kbd "<s-{>")  'undefined)
;; (define-key global-map (kbd "<s-}>")  'undefined)
;; (define-key global-map (kbd "<s-|>")  'undefined)
;; (define-key global-map (kbd "<s-:>")  'undefined)
;; (define-key global-map (kbd "<s-\">") 'undefined)
;; (define-key global-map (kbd "<s-<>")  'undefined)
;; (define-key global-map (kbd "<s->>")  'undefined)
;; (define-key global-map (kbd "<s-?>")  'undefined)
;; (define-key global-map (kbd "<s-`>")  'undefined)
;; (define-key global-map (kbd "<s-1>")  'undefined)
;; (define-key global-map (kbd "<s-2>")  'undefined)
;; (define-key global-map (kbd "<s-3>")  'undefined)
;; (define-key global-map (kbd "<s-4>")  'undefined)
;; (define-key global-map (kbd "<s-5>")  'undefined)
;; (define-key global-map (kbd "<s-6>")  'undefined)
;; (define-key global-map (kbd "<s-7>")  'undefined)
;; (define-key global-map (kbd "<s-8>")  'undefined)
;; (define-key global-map (kbd "<s-9>")  'undefined)
;; (define-key global-map (kbd "<s-0>")  'undefined)
;; (define-key global-map (kbd "<s-->")  'undefined)
;; (define-key global-map (kbd "<s-=>")  'undefined)
;; (define-key global-map (kbd "<s-~>")  'undefined)
;; (define-key global-map (kbd "<s-!>")  'undefined)
;; (define-key global-map (kbd "<s-@>")  'undefined)
;; (define-key global-map (kbd "<s-#>")  'undefined)
;; (define-key global-map (kbd "<s-$>")  'undefined)
;; (define-key global-map (kbd "<s-%>")  'undefined)
;; (define-key global-map (kbd "<s-^>")  'undefined)
;; (define-key global-map (kbd "<s-&>")  'undefined)
;; (define-key global-map (kbd "<s-*>")  'undefined)
;; (define-key global-map (kbd "<s-(>")  'undefined)
;; (define-key global-map (kbd "<s-)>")  'undefined)
;; (define-key global-map (kbd "<s-_>")  'undefined)
;; (define-key global-map (kbd "<s-+>")  'undefined)

;; (define-key global-map (kbd "<s-S-a>")  'undefined)
;; (define-key global-map (kbd "<s-S-b>")  'undefined)
;; (define-key global-map (kbd "<s-S-c>")  'undefined)
;; (define-key global-map (kbd "<s-S-d>")  'undefined)
;; (define-key global-map (kbd "<s-S-e>")  'undefined)
;; (define-key global-map (kbd "<s-S-f>")  'undefined)
;; (define-key global-map (kbd "<s-S-g>")  'undefined)
;; (define-key global-map (kbd "<s-S-h>")  'undefined)
;; (define-key global-map (kbd "<s-S-i>")  'undefined)
;; (define-key global-map (kbd "<s-S-j>")  'undefined)
;; (define-key global-map (kbd "<s-S-k>")  'undefined)
;; (define-key global-map (kbd "<s-S-l>")  'undefined)
;; (define-key global-map (kbd "<s-S-m>")  'undefined)
;; (define-key global-map (kbd "<s-S-n>")  'undefined)
;; (define-key global-map (kbd "<s-S-o>")  'undefined)
;; (define-key global-map (kbd "<s-S-p>")  'undefined)
;; (define-key global-map (kbd "<s-S-q>")  'undefined)
;; (define-key global-map (kbd "<s-S-r>")  'undefined)
;; (define-key global-map (kbd "<s-S-s>")  'undefined)
;; (define-key global-map (kbd "<s-S-t>")  'undefined)
;; (define-key global-map (kbd "<s-S-u>")  'undefined)
;; (define-key global-map (kbd "<s-S-v>")  'undefined)
;; (define-key global-map (kbd "<s-S-w>")  'undefined)
;; (define-key global-map (kbd "<s-S-x>")  'undefined)
;; (define-key global-map (kbd "<s-S-y>")  'undefined)
;; (define-key global-map (kbd "<s-S-z>")  'undefined)
;; (define-key global-map (kbd "<s-S-[>")  'undefined)
;; (define-key global-map (kbd "<s-S-]>")  'undefined)
;; (define-key global-map (kbd "<s-S-\\>") 'undefined)
;; (define-key global-map (kbd "<s-S-;>")  'undefined)
;; (define-key global-map (kbd "<s-S-'>")  'undefined)
;; (define-key global-map (kbd "<s-S-,>")  'undefined)
;; (define-key global-map (kbd "<s-S-.>")  'undefined)
;; (define-key global-map (kbd "<s-S-/>")  'undefined)
;; (define-key global-map (kbd "<s-S-{>")  'undefined)
;; (define-key global-map (kbd "<s-S-}>")  'undefined)
;; (define-key global-map (kbd "<s-S-|>")  'undefined)
;; (define-key global-map (kbd "<s-S-:>")  'undefined)
;; (define-key global-map (kbd "<s-S-\">") 'undefined)
;; (define-key global-map (kbd "<s-S-<>")  'undefined)
;; (define-key global-map (kbd "<s-S->>")  'undefined)
;; (define-key global-map (kbd "<s-S-?>")  'undefined)
;; (define-key global-map (kbd "<s-S-`>")  'undefined)
;; (define-key global-map (kbd "<s-S-1>")  'undefined)
;; (define-key global-map (kbd "<s-S-2>")  'undefined)
;; (define-key global-map (kbd "<s-S-3>")  'undefined)
;; (define-key global-map (kbd "<s-S-4>")  'undefined)
;; (define-key global-map (kbd "<s-S-5>")  'undefined)
;; (define-key global-map (kbd "<s-S-6>")  'undefined)
;; (define-key global-map (kbd "<s-S-7>")  'undefined)
;; (define-key global-map (kbd "<s-S-8>")  'undefined)
;; (define-key global-map (kbd "<s-S-9>")  'undefined)
;; (define-key global-map (kbd "<s-S-0>")  'undefined)
;; (define-key global-map (kbd "<s-S-->")  'undefined)
;; (define-key global-map (kbd "<s-S-=>")  'undefined)
;; (define-key global-map (kbd "<s-S-~>")  'undefined)
;; (define-key global-map (kbd "<s-S-!>")  'undefined)
;; (define-key global-map (kbd "<s-S-@>")  'undefined)
;; (define-key global-map (kbd "<s-S-#>")  'undefined)
;; (define-key global-map (kbd "<s-S-$>")  'undefined)
;; (define-key global-map (kbd "<s-S-%>")  'undefined)
;; (define-key global-map (kbd "<s-S-^>")  'undefined)
;; (define-key global-map (kbd "<s-S-&>")  'undefined)
;; (define-key global-map (kbd "<s-S-*>")  'undefined)
;; (define-key global-map (kbd "<s-S-(>")  'undefined)
;; (define-key global-map (kbd "<s-S-)>")  'undefined)
;; (define-key global-map (kbd "<s-S-_>")  'undefined)
;; (define-key global-map (kbd "<s-S-+>")  'undefined)

(define-key global-map (kbd "<jd:bks>")
  (lambda ()
    (interactive)
    (setq jd:company-select nil)
    (delete-backward-char 1)))
(define-key global-map (kbd "<jd:S-bks>")
  (lambda ()
     (interactive)
     (setq jd:company-select nil)
     (delete-backward-char 1)))
(define-key global-map (kbd "<jd:C-bks>")
  (lambda ()
     (interactive)
     (setq jd:company-select nil)
     (jd:delete-word-backward)))
;; (define-key global-map (kbd "<jd:C-S-bks>")   'undefined)
(define-key global-map (kbd "<jd:M-bks>")     'delete-char)
;; (define-key global-map (kbd "<jd:M-S-bks>")   'undefined)
(define-key global-map (kbd "<jd:C-M-bks>")   'jd:incredibly-smart-backspace)
;; (define-key global-map (kbd "<jd:C-M-S-bks>") 'undefined)
;; (define-key global-map (kbd "<jd:s-bks>")     'undefined)
;; (define-key global-map (kbd "<jd:s-S-bks>")   'undefined)
;; (define-key global-map (kbd "<jd:H-bks>")     'undefined)
;; (define-key global-map (kbd "<jd:H-S-bks>")   'undefined)

;; (define-key global-map (kbd "<jd:esc>")       'undefined)
;; (define-key global-map (kbd "<jd:S-esc>")     'undefined)
;; (define-key global-map (kbd "<jd:C-esc>")     'undefined)
;; (define-key global-map (kbd "<jd:C-S-esc>")   'undefined)
;; (define-key global-map (kbd "<jd:M-esc>")     'undefined)
;; (define-key global-map (kbd "<jd:M-S-esc>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-esc>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-S-esc>") 'undefined)
;; (define-key global-map (kbd "<jd:s-esc>")     'undefined)
;; (define-key global-map (kbd "<jd:s-S-esc>")   'undefined)
;; (define-key global-map (kbd "<jd:H-esc>")     'undefined)
;; (define-key global-map (kbd "<jd:H-S-esc>")   'undefined)

(define-key global-map (kbd "<jd:ret>")       'newline)
;; (define-key global-map (kbd "<jd:S-ret>")     'undefined)
;; (define-key global-map (kbd "<jd:C-ret>")     'undefined)
;; (define-key global-map (kbd "<jd:C-S-ret>")   'undefined)
(define-key global-map (kbd "<jd:M-ret>")     'open-line)
;; (define-key global-map (kbd "<jd:M-S-ret>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-ret>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-S-ret>") 'undefined)
;; (define-key global-map (kbd "<jd:s-ret>")     'undefined)
;; (define-key global-map (kbd "<jd:s-S-ret>")   'undefined)
;; (define-key global-map (kbd "<jd:H-ret>")     'undefined)
;; (define-key global-map (kbd "<jd:H-S-ret>")   'undefined)

(define-key global-map (kbd "<jd:spc>")       'jd:self-insert-space)
(define-key global-map (kbd "<jd:S-spc>")     'jd:self-insert-space)
;; (define-key global-map (kbd "<jd:C-spc>")     'undefined)
;; (define-key global-map (kbd "<jd:C-S-spc>")   'undefined)
(define-key global-map (kbd "<jd:M-spc>")
  (lambda ()
    (interactive)
    (select-window (get-buffer-window))
    (jd:macro-swap-buffers)
    (select-window (get-buffer-window))))
;; (define-key global-map (kbd "<jd:M-S-spc>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-spc>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-S-spc>") 'undefined)
;; (define-key global-map (kbd "<jd:s-spc>")     'undefined)
;; (define-key global-map (kbd "<jd:s-S-spc>")   'undefined)
;; (define-key global-map (kbd "<jd:H-spc>")     'undefined)
;; (define-key global-map (kbd "<jd:H-S-spc>")   'undefined)

(define-key global-map (kbd "<jd:tab>") 'jd:incredibly-smart-tab)
;; (define-key global-map (kbd "<jd:S-tab>")     'undefined)
(define-key global-map (kbd "<jd:C-tab>")     'jd:window-forward)
(cond
 ((string-equal system-type "darwin")
  (define-key global-map (kbd "<C-tab>")   'jd:window-backward))
 ((string-equal system-type "gnu/linux")
  (if (string-match-p "Windows" (getenv "PATH"))
      (define-key global-map (kbd "<jd:C-S-tab>")   'jd:window-backward)
    (define-key global-map (kbd "<jd:C-S-tab>")   'jd:window-backward))))
;; (define-key global-map (kbd "<jd:M-tab>")     'undefined)
;; (define-key global-map (kbd "<jd:M-S-tab>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-tab>")   'undefined)
;; (define-key global-map (kbd "<jd:C-M-S-tab>") 'undefined)
;; (define-key global-map (kbd "<jd:s-tab>")     'undefined)
;; (define-key global-map (kbd "<jd:s-S-tab>")   'undefined)
;; (define-key global-map (kbd "<jd:H-tab>")     'undefined)
;; (define-key global-map (kbd "<jd:H-S-tab>")   'undefined)

(define-key global-map (kbd "<C-h> a") 'counsel-apropos)
(define-key global-map (kbd "<C-h> b") 'describe-bindings)
(define-key global-map (kbd "<C-h> c") 'apropos-command)
(define-key global-map (kbd "<C-h> d") 'apropos-documentation)
;; (define-key global-map (kbd "<C-h> e") 'undefined)
(define-key global-map (kbd "<C-h> f") 'counsel-describe-function)
;; (define-key global-map (kbd "<C-h> g") 'undefined)
;; (define-key global-map (kbd "<C-h> h") 'undefined)
;; (define-key global-map (kbd "<C-h> i") 'undefined)
;; (define-key global-map (kbd "<C-h> j") 'undefined)
(define-key global-map (kbd "<C-h> k") 'describe-key)
(define-key global-map (kbd "<C-h> l") 'view-lossage)
(define-key global-map (kbd "<C-h> m") 'describe-mode)
;; (define-key global-map (kbd "<C-h> n") 'undefined)
;; (define-key global-map (kbd "<C-h> o") 'undefined)
(define-key global-map (kbd "<C-h> p") 'describe-package)
;; (define-key global-map (kbd "<C-h> q") 'undefined)
;; (define-key global-map (kbd "<C-h> r") 'undefined)
(define-key global-map (kbd "<C-h> s") 'describe-symbol)
;; (define-key global-map (kbd "<C-h> t") 'undefined)
;; (define-key global-map (kbd "<C-h> u") 'undefined)
(define-key global-map (kbd "<C-h> v") 'counsel-describe-variable)
;; (define-key global-map (kbd "<C-h> w") 'undefined)
;; (define-key global-map (kbd "<C-h> x") 'undefined)
(define-key global-map (kbd "<C-h> y") 'jd:describe-keymap)
;; (define-key global-map (kbd "<C-h> z") 'undefined)

;; (define-key global-map (kbd "<C-x> a")        'undefined)
;; (define-key global-map (kbd "<C-x> b")        'undefined)
;; (define-key global-map (kbd "<C-x> c")        'undefined)
;; (define-key global-map (kbd "<C-x> d")        'undefined)
;; (define-key global-map (kbd "<C-x> e")        'undefined)
;; (define-key global-map (kbd "<C-x> f")        'undefined)
;; (define-key global-map (kbd "<C-x> g")        'undefined)
;; (define-key global-map (kbd "<C-x> h")        'undefined)
;; (define-key global-map (kbd "<C-x> i")        'undefined)
;; (define-key global-map (kbd "<C-x> j")        'undefined)
;; (define-key global-map (kbd "<C-x> k")        'undefined)
;; (define-key global-map (kbd "<C-x> l")        'undefined)
;; (define-key global-map (kbd "<C-x> m")        'undefined)
;; (define-key global-map (kbd "<C-x> n")        'undefined)
(define-key global-map (kbd "<C-x> o")        'jd:copy-line-and-goto-end)
;; (define-key global-map (kbd "<C-x> p")        'undefined)
;; (define-key global-map (kbd "<C-x> q")        'undefined)
(define-key global-map (kbd "<C-x> r")        'point-to-register)
;; (define-key global-map (kbd "<C-x> s")        'undefined)
;; (define-key global-map (kbd "<C-x> t")        'undefined)
(define-key global-map (kbd "<C-x> u")        'jd:copy-line-and-goto-beg)
;; (define-key global-map (kbd "<C-x> v")        'undefined)
;; (define-key global-map (kbd "<C-x> w")        'undefined)
;; (define-key global-map (kbd "<C-x> x")        'undefined)
;; (define-key global-map (kbd "<C-x> y")        'undefined)
;; (define-key global-map (kbd "<C-x> z")        'undefined)
(define-key global-map (kbd "<C-x> <jd:bks>") 'jd:delete-line)
(define-key global-map (kbd "<C-x> <jd:tab>") 'jd:indent-region)
(define-key global-map (kbd "<C-x> <f4>")     'kmacro-edit-macro)

;; (define-key global-map (kbd "<C-x> <C-a>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-b>") 'undefined)
(define-key global-map (kbd "<C-x> <C-c>") 'save-buffers-kill-terminal)
;; (define-key global-map (kbd "<C-x> <C-d>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-e>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-f>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-g>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-h>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-i>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-j>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-k>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-l>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-m>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-n>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-o>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-p>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-q>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-r>") 'undefined)
(define-key global-map (kbd "<C-x> <C-s>") 'write-file)
;; (define-key global-map (kbd "<C-x> <C-t>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-u>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-v>") 'undefined)
(define-key global-map (kbd "<C-x> <C-w>") 'kill-buffer)
;; (define-key global-map (kbd "<C-x> <C-x>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-y>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-z>") 'undefined)

;; (define-key global-map (kbd "<C-x> <C-S-a>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-b>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-c>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-d>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-e>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-f>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-g>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-h>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-i>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-j>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-k>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-l>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-m>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-n>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-o>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-p>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-q>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-r>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-s>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-t>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-u>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-v>") 'undefined)
(define-key global-map (kbd "<C-x> <C-S-w>") 'delete-frame)
;; (define-key global-map (kbd "<C-x> <C-S-x>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-y>") 'undefined)
;; (define-key global-map (kbd "<C-x> <C-S-z>") 'undefined)

;; (define-key global-map (kbd "<C-x> <M-a>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-b>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-c>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-d>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-e>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-f>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-g>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-h>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-i>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-j>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-k>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-l>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-m>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-n>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-o>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-p>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-q>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-r>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-s>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-t>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-u>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-v>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-w>") 'undefined)
(define-key global-map (kbd "<C-x> <M-x>") 'eval-expression)
;; (define-key global-map (kbd "<C-x> <M-y>") 'undefined)
;; (define-key global-map (kbd "<C-x> <M-z>") 'undefined)

(define-key global-map (kbd "<C-x> 1")  (lambda () (interactive) (point-to-register 1)))
(define-key global-map (kbd "<C-x> 2")  (lambda () (interactive) (point-to-register 2)))
(define-key global-map (kbd "<C-x> 3")  (lambda () (interactive) (point-to-register 3)))
(define-key global-map (kbd "<C-x> 4")  (lambda () (interactive) (point-to-register 4)))
(define-key global-map (kbd "<C-x> 5")  (lambda () (interactive) (point-to-register 5)))
(define-key global-map (kbd "<C-x> 6")  (lambda () (interactive) (point-to-register 6)))
(define-key global-map (kbd "<C-x> 7")  (lambda () (interactive) (point-to-register 7)))
(define-key global-map (kbd "<C-x> 8")  (lambda () (interactive) (point-to-register 8)))
(define-key global-map (kbd "<C-x> 9")  (lambda () (interactive) (point-to-register 9)))
(define-key global-map (kbd "<C-x> 0")  'jd:reset-registers)

;; (define-key global-map (kbd "<f1>")  'undefined)
(define-key global-map (kbd "<f2>")  'eshell)
(define-key global-map (kbd "<f3>")  'kmacro-start-macro)
(define-key global-map (kbd "<f4>")  'kmacro-end-or-call-macro)
;; (define-key global-map (kbd "<f5>")  'undefined)
;; (define-key global-map (kbd "<f6>")  'undefined)
;; (define-key global-map (kbd "<f7>")  'undefined)
;; (define-key global-map (kbd "<f8>")  'undefined)
;; (define-key global-map (kbd "<f9>")  'undefined)
;; (define-key global-map (kbd "<f10>") 'undefined)
;; (define-key global-map (kbd "<f11>") 'undefined)
;; (define-key global-map (kbd "<f12>") 'undefined)

(define-key global-map (kbd "<down>")  'next-line)
(define-key global-map (kbd "<left>")  'backward-char)
(define-key global-map (kbd "<right>") 'forward-char)
(define-key global-map (kbd "<up>")    'previous-line)

(define-key global-map (kbd "<mouse-1>")                      'mouse-set-point)
(define-key global-map (kbd "<down-mouse-1>")                 'mouse-drag-region)
(define-key global-map (kbd "<drag-mouse-1>")                 'mouse-set-region)
;; (define-key global-map (kbd "<vertical-line> <mouse-1>")      'undefined)
(define-key global-map (kbd "<vertical-line> <down-mouse-1>") 'mouse-drag-vertical-line)
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-1>") 'undefined)
(define-key global-map (kbd "<mode-line>     <mouse-1>")      'mouse-select-window)
(define-key global-map (kbd "<mode-line>     <down-mouse-1>") 'mouse-drag-mode-line)
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-1>") 'undefined)

;; (define-key global-map (kbd "<mouse-2>")                      'undefined)
;; (define-key global-map (kbd "<down-mouse-2>")                 'undefined)
;; (define-key global-map (kbd "<drag-mouse-2>")                 'undefined)
;; (define-key global-map (kbd "<vertical-line> <mouse-2>")      'undefined)
;; (define-key global-map (kbd "<vertical-line> <down-mouse-2>") 'undefined)
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-2>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <mouse-2>")      'undefined)
;; (define-key global-map (kbd "<mode-line>     <down-mouse-2>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-2>") 'undefined)

;; (define-key global-map (kbd "<mouse-3>")                      'undefined)
;; (define-key global-map (kbd "<down-mouse-3>")                 'undefined)
;; (define-key global-map (kbd "<drag-mouse-3>")                 'undefined)
;; (define-key global-map (kbd "<vertical-line> <mouse-3>")      'undefined)
;; (define-key global-map (kbd "<vertical-line> <down-mouse-3>") 'undefined)
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-3>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <mouse-3>")      'undefined)
;; (define-key global-map (kbd "<mode-line>     <down-mouse-3>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-3>") 'undefined)

(define-key global-map (kbd "<mouse-4>")                      'mwheel-scroll)
;; (define-key global-map (kbd "<down-mouse-4>")                 'undefined)
;; (define-key global-map (kbd "<drag-mouse-4>")                 'undefined)
;; (define-key global-map (kbd "<vertical-line> <mouse-4>")      'undefined)
;; (define-key global-map (kbd "<vertical-line> <down-mouse-4>") 'undefined)
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-4>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <mouse-4>")      'undefined)
;; (define-key global-map (kbd "<mode-line>     <down-mouse-4>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-4>") 'undefined)

(define-key global-map (kbd "<mouse-5>")                      'mwheel-scroll)
;; (define-key global-map (kbd "<down-mouse-5>")                 'undefined)
;; (define-key global-map (kbd "<drag-mouse-5>")                 'undefined)
;; (define-key global-map (kbd "<vertical-line> <mouse-5>")      'undefined)
;; (define-key global-map (kbd "<vertical-line> <down-mouse-5>") 'undefined)
;; (define-key global-map (kbd "<vertical-line> <drag-mouse-5>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <mouse-5>")      'undefined)
;; (define-key global-map (kbd "<mode-line>     <down-mouse-5>") 'undefined)
;; (define-key global-map (kbd "<mode-line>     <drag-mouse-5>") 'undefined)

(define-key global-map (kbd "<C-x> <mouse-1>")
  (lambda (jd:event)
    (interactive "e")
    (let ((jd:buffer-i (window-buffer (car (elt jd:event 1))))
          (jd:buffer-ii (window-buffer (get-buffer-window))))
      (set-window-buffer (get-buffer-window) jd:buffer-i)
      (set-window-buffer (car (elt jd:event 1)) jd:buffer-ii))))

(define-key global-map (kbd "<wheel-left>")  (lambda () (interactive) (scroll-right 1)))
(define-key global-map (kbd "<wheel-right>") (lambda () (interactive) (scroll-left  1)))

(setq minibuffer-local-map (make-sparse-keymap))
(define-key minibuffer-local-map (kbd "<C-g>") 'minibuffer-keyboard-quit)
(define-key minibuffer-local-map (kbd "<C-M-i>") 'previous-history-element)
(define-key minibuffer-local-map (kbd "<C-M-k>") 'next-history-element)
(define-key minibuffer-local-map (kbd "<jd:ret>") 'exit-minibuffer)
(define-key minibuffer-local-map (kbd "<jd:tab>") 'minibuffer-complete)

(provide 'jd:global-keybindings.el)
