;; Customization variables.
(defvar eshell-hist-event-designator)
(defvar eshell-hist-ignoredups)
(defvar eshell-hist-load-hook)
(defvar eshell-hist-match-partial)
(defvar eshell-hist-modifier)
(defvar eshell-hist-move-to-end)
(defvar eshell-hist-rebind-keys-alist)
(defvar eshell-hist-unload-hook)
(defvar eshell-hist-word-designator)
(defvar eshell-history-file-name)
(defvar eshell-history-size)
(defvar eshell-input-filter)
(defvar eshell-save-history-on-exit)

(jd:provide-feature jd:em-hist-st)
