;; Customization variables.
(defvar eshell-cmpl-autolist)
(defvar eshell-cmpl-command-name-function)
(defvar eshell-cmpl-compare-entry-function)
(defvar eshell-cmpl-cycle-completions)
(defvar eshell-cmpl-cycle-cutoff-length)
(defvar eshell-cmpl-dir-ignore)
(defvar eshell-cmpl-expand-before-complete)
(defvar eshell-cmpl-file-ignore)
(defvar eshell-cmpl-ignore-case)
(defvar eshell-cmpl-load-hook)
(defvar eshell-cmpl-man-function)
(defvar eshell-cmpl-recexact)
(defvar eshell-cmpl-restore-window-delay)
(defvar eshell-cmpl-suffix-list)
(defvar eshell-cmpl-use-paring)
(defvar eshell-command-completion-function)
(defvar eshell-command-completions-alist)
(defvar eshell-default-completion-function)
(defvar eshell-no-completion-during-jobs)
(defvar eshell-show-lisp-alternatives)
(defvar eshell-show-lisp-completions)

(jd:provide-feature jd:em-cmpl-st)
