(defun jd:c++-mode-hook ()
  (company-mode 1)
  (electric-pair-mode 1)
  (font-lock-mode 1)
  (idle-highlight-mode 1)
  (yas-minor-mode 1)
  (lsp)
  (set (make-local-variable 'company-backends)
       '((company-lsp :separate company-dabbrev-code :separate company-yasnippet)))
  (set (make-local-variable 'compile-command)
       (concat "clang++ -g -Wall -Wextra -std=c++17 -o prog " buffer-file-name " && ./prog")))

(add-hook 'c++-mode-hook 'jd:c++-mode-hook)

(provide 'jd:cc-mode-st)
