(setq-default awk-mode-map (make-sparse-keymap))
(setq-default c-c++-menu (make-sparse-keymap))
(setq-default c-awk-menu (make-sparse-keymap))
(setq-default c-c-menu (make-sparse-keymap))
(setq-default c-idl-menu (make-sparse-keymap))
(setq-default c-java-menu (make-sparse-keymap))
(setq-default c-mode-base-map (make-sparse-keymap))
(setq-default c-mode-map (make-sparse-keymap))
(setq-default c-objc-menu (make-sparse-keymap))
(setq-default c-pike-menu (make-sparse-keymap))
(setq-default idl-mode-map (make-sparse-keymap))
(setq-default java-mode-map (make-sparse-keymap))
(setq-default objc-mode-map (make-sparse-keymap))
(setq-default pike-mode-map (make-sparse-keymap))

(setq-default c++-mode-map (make-sparse-keymap))
(define-key c++-mode-map (kbd "#") 'c-electric-pound)
(define-key c++-mode-map (kbd "(") 'c-electric-paren)
(define-key c++-mode-map (kbd ")") 'c-electric-paren)
(define-key c++-mode-map (kbd "*") 'c-electric-star)
(define-key c++-mode-map (kbd ",") 'c-electric-semi&comma)
(define-key c++-mode-map (kbd "/") 'c-electric-slash)
(define-key c++-mode-map (kbd ":") 'c-electric-colon)
(define-key c++-mode-map (kbd ";") 'c-electric-semi&comma)
(define-key c++-mode-map (kbd "<") 'c-electric-lt-gt)
(define-key c++-mode-map (kbd ">") 'c-electric-lt-gt)
(define-key c++-mode-map (kbd "{") 'c-electric-brace)
(define-key c++-mode-map (kbd "}") 'c-electric-brace)
(define-key c++-mode-map (kbd "<C-b>") 'compile)
(define-key c++-mode-map (kbd "<C-;>") 'c-mark-function)
(define-key c++-mode-map (kbd "<jd:tab>") 'c-indent-line-or-region)

(provide 'jd:cc-mode-kb.el)
