(setq-default abbrev-map (make-sparse-keymap))
(setq-default ctl-x-r-map (make-sparse-keymap))
(setq-default goto-map (make-sparse-keymap))
(setq-default mode-line-buffer-identification-keymap (make-sparse-keymap))
(setq-default mode-line-coding-system-map (make-sparse-keymap))
(setq-default mode-line-column-line-number-mode-map (make-sparse-keymap))
(setq-default mode-line-input-method-map (make-sparse-keymap))
(setq-default mode-line-major-mode-keymap (make-sparse-keymap))
(setq-default mode-line-minor-mode-keymap (make-sparse-keymap))
(setq-default mode-line-mode-menu (make-sparse-keymap))
(setq-default mode-specific-map (make-sparse-keymap))
(setq-default narrow-map (make-sparse-keymap))
(setq-default search-map (make-sparse-keymap))

(provide 'jd:bindings-kb.el)
