;; Faces.
(defvar custom-button)
(defvar custom-button-mouse)
(defvar custom-button-pressed)
(defvar custom-button-pressed-unraised)
(defvar custom-button-unraised)
(defvar custom-changed)
(defvar custom-comment)
(defvar custom-comment-tag)
(defvar custom-documentation)
(defvar custom-face-tag)
(defvar custom-group-subtitle)
(defvar custom-group-tag)
(defvar custom-group-tag-1)
(defvar custom-invalid)
(defvar custom-link)
(defvar custom-modified)
(defvar custom-rogue)
(defvar custom-saved)
(defvar custom-set)
(defvar custom-state)
(defvar custom-themed)
(defvar custom-variable-button)
(defvar custom-variable-tag)
(defvar custom-visibility)

;; Customization variables.
(defvar Custom-mode-hook)
(defvar custom-browse-only-groups)
(defvar custom-browse-order-groups)
(defvar custom-browse-sort-alphabetically)
(defvar custom-buffer-done-kill)
(defvar custom-buffer-indent)
(defvar custom-buffer-order-groups)
(defvar custom-buffer-sort-alphabetically)
(defvar custom-buffer-style)
(defvar custom-buffer-verbose-help)
(defvar custom-face-default-form)
(defvar custom-file)
(defvar custom-group-tag-faces)
(defvar custom-guess-doc-alist)
(defvar custom-guess-name-alist)
(defvar custom-magic-show)
(defvar custom-magic-show-button)
(defvar custom-magic-show-hidden)
(defvar custom-menu-nesting)
(defvar custom-menu-order-groups)
(defvar custom-menu-sort-alphabetically)
(defvar custom-raised-buttons)
(defvar custom-reset-button-menu)
(defvar custom-search-field)
(defvar custom-unlispify-remove-prefixes)
(defvar custom-variable-default-form)

(setq-default custom-unlispify-menu-entries nil)
(setq-default custom-unlispify-tag-names nil)

(defun jd:Custom-mode-hook ()
  (electric-pair-mode 1)
  (font-lock-mode 1)
  (idle-highlight-mode 1))

(add-hook 'Custom-mode-hook 'jd:Custom-mode-hook)

(jd:provide-feature jd:cus-edit-st)
