(define-key term-raw-map (kbd "<C-S-v>") 'jd:term-paste)
(define-key term-raw-map (kbd "<M-j>") 'jd:term-backward-char)
(define-key term-raw-map (kbd "<M-k>") 'jd:term-next-line)
(define-key term-raw-map (kbd "<M-l>") 'jd:term-forward-char)
(define-key term-raw-map (kbd "<M-o>") 'jd:term-end-of-line)
(define-key term-raw-map (kbd "<M-u>") 'jd:term-beginning-of-line)
(define-key term-raw-map (kbd "<C-M-i>") 'jd:term-previous-input)
(define-key term-raw-map (kbd "<C-M-j>") 'jd:term-backward-word)
(define-key term-raw-map (kbd "<C-M-k>") 'jd:term-next-input)
(define-key term-raw-map (kbd "<C-M-l>") 'jd:term-forward-word)
(define-key term-raw-map (kbd "<C-c> <C-\\>") 'term-quit-subjob)
(define-key term-raw-map (kbd "<C-c> <C-c>") 'term-interrupt-subjob)
(define-key term-raw-map (kbd "<C-c> <C-d>") 'term-send-eof)
(define-key term-raw-map (kbd "<C-c> <C-l>") 'jd:term-clear-buffer)
(define-key term-raw-map (kbd "<C-c> <C-q>") 'term-continue-subjob)
(define-key term-raw-map (kbd "<C-c> <C-s>") 'term-stop-subjob)
(define-key term-raw-map (kbd "<jd:bks>") 'term-send-backspace)
(define-key term-raw-map (kbd "<jd:ret>") 'jd:term-send-input)
(define-key term-raw-map (kbd "<jd:tab>") 'jd:incredibly-smart-tab-term-mode)
(define-key term-raw-map (kbd "<jd:C-bks>") 'jd:term-delete-backward-word)
(define-key term-raw-map (kbd "<jd:C-spc>") 'jd:goto-process-mark)

(jd:provide-feature jd:term-kb)
