;; Customization variables.
(defvar pcomplete-autolist)
(defvar pcomplete-command-completion-function)
(defvar pcomplete-command-name-function)
(defvar pcomplete-compare-entry-function)
(defvar pcomplete-cycle-completions)
(defvar pcomplete-cycle-cutoff-length)
(defvar pcomplete-default-completion-function)
(defvar pcomplete-dir-ignore)
(defvar pcomplete-expand-before-complete)
(defvar pcomplete-file-ignore)
(defvar pcomplete-help)
(defvar pcomplete-ignore-case)
(defvar pcomplete-man-function)
(defvar pcomplete-parse-arguments-function)
(defvar pcomplete-recexact)
(defvar pcomplete-restore-window-delay)
(defvar pcomplete-suffix-list)
(defvar pcomplete-termination-string)
(defvar pcomplete-try-first-hook)
(defvar pcomplete-use-paring)

(jd:provide-feature jd:pcomplete-st)
