;; Faces.
(defvar match)
(defvar query-replace)

;; Customization variables.
(defvar case-replace)
(defvar list-matching-lines-buffer-name-face)
(defvar list-matching-lines-current-line-face)
(defvar list-matching-lines-default-context-lines)
(defvar list-matching-lines-face)
(defvar list-matching-lines-jump-to-current-line)
(defvar list-matching-lines-prefix-face)
(defvar occur-excluded-properties)
(defvar occur-hook)
(defvar occur-mode-find-occurrence-hook)
(defvar occur-mode-hook)
(defvar query-replace-from-history-variable)
(defvar query-replace-from-to-separator)
(defvar query-replace-highlight)
(defvar query-replace-lazy-highlight)
(defvar query-replace-show-replacement)
(defvar query-replace-skip-read-only)
(defvar query-replace-to-history-variable)
(defvar read-regexp-defaults-function)
(defvar replace-char-fold)
(defvar replace-lax-whitespace)
(defvar replace-regexp-lax-whitespace)

(provide 'jd:replace-st)
