(defun jd:eshell-clear-buffer ()
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)
    (eshell-send-input))
  (beginning-of-line)
  (backward-delete-char 1)
  (end-of-line))

(defun jd:eshell-ack-or-send-input ()
  (interactive)
  (if (get-char-property (point) 'face)
      (progn
	(let ((value (get-char-property (point) 'face)))
	  (cond ((equal (cdr (car value)) "green3")
		 (let ((file (thing-at-point 'filename 'no-properties)))
		   (find-file file)
		   (forward-line (- (line-number-at-pos)))))
		((equal (cdr (car value)) "yellow3")
		 (let ((line (thing-at-point 'word 'no-properties)))
		   (beginning-of-line)
		   (while (not (equal (cdr (car (get-char-property (point) 'face))) "green3"))
		     (forward-line -1))
		   (let ((file (thing-at-point 'filename 'no-properties)))
		     (find-file file)
		     (forward-line (string-to-number line))))))))
    (eshell-send-input)))

(provide 'jd:esh-mode-st.el)
