;; Faces.
(defvar speedbar-button-face)
(defvar speedbar-directory-face)
(defvar speedbar-file-face)
(defvar speedbar-highlight-face)
(defvar speedbar-selected-face)
(defvar speedbar-separator-face)
(defvar speedbar-tag-face)

;; Customization variables.
(defvar speedbar-after-create-hook)
(defvar speedbar-before-delete-hook)
(defvar speedbar-before-popup-hook)
(defvar speedbar-before-visiting-file-hook)
(defvar speedbar-before-visiting-tag-hook)
(defvar speedbar-default-position)
(defvar speedbar-directory-button-trim-method)
(defvar speedbar-fetch-etags-arguments)
(defvar speedbar-fetch-etags-command)
(defvar speedbar-file-unshown-regexp)
(defvar speedbar-frame-parameters)
(defvar speedbar-frame-plist)
(defvar speedbar-hide-button-brackets-flag)
(defvar speedbar-ignored-directory-expressions)
(defvar speedbar-ignored-modes)
(defvar speedbar-indentation-width)
(defvar speedbar-load-hook)
(defvar speedbar-mode-hook)
(defvar speedbar-mode-specific-contents-flag)
(defvar speedbar-obj-do-check)
(defvar speedbar-query-confirmation-method)
(defvar speedbar-reconfigure-keymaps-hook)
(defvar speedbar-scanner-reset-hook)
(defvar speedbar-select-frame-method)
(defvar speedbar-show-unknown-files)
(defvar speedbar-smart-directory-expand-flag)
(defvar speedbar-sort-tags)
(defvar speedbar-supported-extension-expressions)
(defvar speedbar-tag-group-name-minimum-length)
(defvar speedbar-tag-hierarchy-method)
(defvar speedbar-tag-regroup-maximum-length)
(defvar speedbar-tag-split-minimum-length)
(defvar speedbar-timer-hook)
(defvar speedbar-track-mouse-flag)
(defvar speedbar-update-flag dframe-have-timer-flag)
(defvar speedbar-use-imenu-flag)
(defvar speedbar-vc-directory-enable-hook)
(defvar speedbar-vc-do-check)
(defvar speedbar-vc-in-control-hook)
(defvar speedbar-verbosity-level)
(defvar speedbar-visiting-file-hook)
(defvar speedbar-visiting-tag-hook)

(setq-default speedbar-directory-unshown-regexp "^\\(CVS\\|RCS\\|SCCS\\|\\.\\.*$\\)\\'")
(setq-default speedbar-use-tool-tips-flag nil)

(jd:provide-feature jd:speedbar-st)
